### ISSUE TITLE
megafs: support live refresh

### ISSUE THREAD

**Issue by crass** [megous/megatools#10]
Since megafs is a potentially long running process, it would be nice if there was a way to have it refresh ts file handle data with mega without shutting down.

The solution that comes immediately to mind is to have a mega_session_refresh called in a thread created from a signal handler.  So you could do something like "pkill -HUP megafs" to have it refresh.  It looks like this might require some locking of the file handle list in the session object.  This method might be *nix specific.

**Comment by megous** [comment]
Megafs support was dropped.
