### ISSUE TITLE
Unusable when there is too many files

### ISSUE THREAD

**Issue by Saoneth** [megous/megatools#100]
When you have 10k+ files on MEGA using any of these tools takes like 5 minutes just to load. I think megatools shouldn't decrypt key and attributes for every node every time it starts. It should decrypt them on demand.

**Comment by megous** [comment]
Megatools doesn't decrypt everything on each run. It just decrypts the cache file. Anyway that wouldn't be performance issue at all.

What version of megatools are you using?
What CPU?

**Comment by Saoneth** [comment]
As I was logged on windows, I checked it with latest build for x64. My CPU: i5-4670K @ 4GHz. 
```
>timecmd megals --config mega.ini /Root/test --reload
/Root/test
/Root/test/.mega.ico
command took 0:0:47.00 (47.00s total)
```
```
>timecmd megals --config mega.ini /Root/test
/Root/test
/Root/test/.mega.ico
command took 0:0:42.00 (42.00s total)
```
```
>timecmd megals --config mega.ini /Root/test
command took 0:0:42.00 (42.00s total)
```
Megals took 30% of my CPU every time. And I guess you're right 'cause there is 5 secounds difference between using --reload and not using it.

**Comment by megous** [comment]
Are you using 1.9.94?

**Comment by megous** [comment]
megals --version

**Comment by Saoneth** [comment]
```
>megals --version
megatools 1.9.94 - command line tools for Mega.co.nz

Written by Ondřej Jirman <megous@megous.com>, 2013
Go to http://megatools.megous.com for more information
```

**Comment by megous** [comment]
I suppose Windows is slow at something megatools calls very often, because I have reports that 1.9.94 works quickly on Linux with this many files.

I'm not sure what it might be without performance profiling. We'll see what happens with redesign in 2.0.

Perhaps calling megals with --debug might pinpoint the place where the slowdown happens more accurately.

**Comment by Saoneth** [comment]
It is certainly not the case, because I'm usung linux too, and the problem exist there too.

**Comment by megous** [comment]
That's good. This means it should be easy to make a profile. Can you please:

1] CFLAGS="-pg -g" ./configure && make
2] run the megals (watch it consume CPU time)
3] run gprof on the profile output

and post the results.

**Comment by Saoneth** [comment]
I think there is something wrong with cache.
First run (without cache):
```
$ time ./megals /Root/test
/Root/test
/Root/test/.mega.ico

real	0m3.992s
user	0m0.457s
sys	0m0.018s
```
Second run (with cache):
```
$ time ./megals /Root/test
/Root/test
/Root/test/.mega.ico

real	2m23.439s
user	2m22.844s
sys	0m0.381s
```

**Comment by Saoneth** [comment]
Also, I compiled it the way you you said, but gprof returns:
```
a.out: No such file or directory
```

**Comment by megous** [comment]
Hmm, thanks for the hint.

Gprof needs two parameters:

  gprof path/to/megals path/to/gmon.out

**Comment by Saoneth** [comment]
I can't really find gmon.out though..

**Comment by Saoneth** [comment]
I made test directory for you, it contains 10k empty files. Just import it to your MEGA account.
(https://mega.co.nz/#F!bA8RjbIR!j7GxVkr-1mQxpusxoZ9gkQ)
You'll see that after cache is generated megals slows down by ~3+ minutes.

**Comment by megous** [comment]
Thanks for the test data. I imported the folder. I'll do the profile myself. Yours only shows the ls.c file where none of the interesting stuff happens.

**Comment by megous** [comment]
Fixed. Thanks for the report.
