### ISSUE TITLE
megamv.exe Destination file already exists

### ISSUE THREAD

**Issue by 01B10194E1F9F79001D2AD9DDD02FA51** [megous/megatools#101]
I tried to rename files with megamv.exe

megamv.exe --username mymail@gmail.com --password 12345678 --ignore-config-file --reload /Root/README.TXT /Root/Test.txt

It always returns "Destination file already exists: /Root/README.TXT".
But /Root/README.TXT should be the source file and /Root/Test.txt the destination file.
Switch the parameters will give me the error "Source file doesn't exists: /Root/Test.txt"

Used this version http://megatools.megous.com/builds/megatools-1.9.94-win32.zip on a new mega acc with just a single file (README.TXT) on it.

edit: parameter /Root/test/test2.txt /Root/test2/test2.txt returns
mv /Root/test/test2.txt /Root/test2//Root/test2/test2.txt

Obviously the directory // does not exist and nothing changed at all

**Comment by megous** [comment]
Megamv is not implemented in 1.9.X.

http://megatools.megous.com/man/megamv.html

This is fixed in 2.0.
