### ISSUE TITLE
megaput creates high cpu usage on windows

### ISSUE THREAD

**Issue by x0b** [megous/megatools#102]
The windows build can cause high cpu usage when executed on command line (cmd.exe, Windows 7 x64).

Steps to reproduce
1. Upload a file with megaput by executing it with cmd.exe
2. conhost.exe now uses a lot of cpu power (20% on my system). 
When you minimize the cmd window, the cpu usage drops (on my system to 2-3%, about the same as megaput.exe).

I noticed that some letters are "flickering" on the cmd window which might be related to the problem.
I found two workarounds :
* redirecting standard output to >nul
* suppressing upload output with --no-progress

Both workarounds reduce the cpu usage to almost zero. 
I think there is something wrong in the way megaput communicates with cmd.exe.

**Comment by 01B10194E1F9F79001D2AD9DDD02FA51** [comment]
Seems like STDOUT stream is written in loop without any delay and even if there was no change at all.

If I upload a big file It returns lines like 
"16% - 110,1 MiB of 674,3 MiB"
"16% - 110,1 MiB of 674,3 MiB"
"16% - 110,1 MiB of 674,3 MiB"
"16% - 110,1 MiB of 674,3 MiB"
"16% - 110,1 MiB of 674,3 MiB"

 every few millisecond until it switches to  

"16% - 110,2 MiB of 674,3 MiB" 

output to a file should show what I mean ;)

**Comment by megous** [comment]
Megatools does exactly what curl does. I made it so that on windows, the reporting is limited to once per second.
