### ISSUE TITLE
Name conflict with official client

### ISSUE THREAD

**Issue by yan12125** [megous/megatools#103]
This package contains a binary named megasync, which is located at /usr/bin/megasync on my Linux box. However, the official client has /usr/bin/megasync, too. I can't use both of them simultaneously. Could you rename megasync to some different name?

**Comment by PeterDaveHello** [comment]
You can use both of them simultaneously by using them with full path, or alias I think.

**Comment by yan12125** [comment]
If I install megatools after megasync, /usr/bin/megasync is overwritten, which is annoying. I have to rename one of them, and do the same thing each time one of them is upgraded.

**Comment by megous** [comment]
I can of course rename the tool, as there's no reason to fight the official client, even though it's much younger. Megatools 2.0 are all namespaced to `megatools <command> ...`, so there should be no more clashes in the future.

**Comment by PeterDaveHello** [comment]
:+1:

**Comment by yan12125** [comment]
Thanks a lot!

**Comment by megous** [comment]
Any suggestions? megacopy?

**Comment by yan12125** [comment]
As stated above, something like "megatools sync" is a great option. Now I think it's better to merge all commands into a single binary rather than to rename one existing file.

**Comment by megous** [comment]
That's already done in 2.0, in stable I will only rename the single binary in order to avoid the conflict.

**Comment by yan12125** [comment]
Sorry I didn't notice the dev branch. I'll try it. In addition, could you create a package megatools-dev or megatools-dev-git on AUR?

**Comment by megous** [comment]
Yes, I will. FYI, status of the dev branch is here: https://github.com/megous/megatools/issues/84

**Comment by yan12125** [comment]
Sorry but I can't wait. Notify me if you want to take the ownership of the package.

https://aur.archlinux.org/packages/megatools-dev-git/

**Comment by megous** [comment]
Good job. :+1:

**Comment by megous** [comment]
Fixed in 1.9.95
