### ISSUE TITLE
Removing files by "FS node" / "Handle"

### ISSUE THREAD

**Issue by jota-mylogins** [megous/megatools#104]
Sorry for my bad english.
Actually this is not an issue, is a doubt.
But I did not know whether to use the email contact or the Issues System.
Sorry if I have not made ​​the right decision.

Here the doubt:
I have this warning.
WARNING: Skipping FS node f2tnZlqS because it is missing name.
This file is not accesible only use space in my MEGA cloud. And I want to delete it.
Is there any way to delete files or folders by "FS node" / "Handle", not by names.
Will could implement this tool?

**Comment by megous** [comment]
Megatools 2.0 in the dev branch has a command called fixup which does exactly that. It takes the list of nodes it can't decrypt and deletes them. You can try it. But be careful and use --dry-run first.

**Comment by jota-mylogins** [comment]
Thanks for quickly response.
I'll give it a try.

**Comment by jota-mylogins** [comment]
Is there a compiled version for Windows? I cant see it.

**Comment by megous** [comment]
No there isn't. Windows is not supported yet in the dev branch.

**Comment by jota-mylogins** [comment]
Ok I try with archlinux.

**Comment by megous** [comment]
That should work well, I develop on Arch Linux. :)

**Comment by jota-mylogins** [comment]
ArchLinux is awesome!

**Comment by megous** [comment]
:+1:

**Comment by jota-mylogins** [comment]
OK, Im gonna try with ArchLinux, if there any proble compiling I post them.

**Comment by jota-mylogins** [comment]
I downloaded the the right branch repository using git.
git clone -b dev https://github.com/megous/megatools megatoolsgit
./autogen.sh
Error -> I need re2c
make
Error in json.gen.c-> json.c
http://pastebin.com/HzYsGBGM

**Comment by jota-mylogins** [comment]
After install the dependencies re2c and gobject-introspection
I just try to install with yaourt. 
yaourt -S megatools-dev-git
And I have the same error compiling.
/bin/sh: line 1: 14936 Violación de segmento ('core' generado) /usr/bin/re2c -s -o sjson/sjson.gen.c sjson/sjson.c
Makefile:1062 fallo en las instrucciones para el objetivo 'sjson/sjson.gen.c'
make: *** [sjson/sjson.gen.c] Error 139

Any suggest?

**Comment by jota-mylogins** [comment]
Maybe is better open an new issue.
The principal issue Removing files by "FS node" / "Handle" was solved.
