### ISSUE TITLE
Error Compiling Megatools dev Branch in ArchLinux

### ISSUE THREAD

**Issue by jota-mylogins** [megous/megatools#106]
I have all dependencies installed:
 - curl
 - fuse
 - glib-networking
 - git
 - gobject-introspection
 - re2c
I just try to install with yaourt.
yaourt -S megatools-dev-git
And I have this error compiling.

/bin/sh: line 1: 14936 Violación de segmento ('core' generado) /usr/bin/re2c -s -o sjson/sjson.gen.c sjson/sjson.c
Makefile:1062 fallo en las instrucciones para el objetivo 'sjson/sjson.gen.c'
make: *** [sjson/sjson.gen.c] Error 139

Any suggest?

**Comment by megous** [comment]
Yes, the version of re2c in archlinux is broken. You need to downgrade re2c to 0.13.6.

**Comment by jota-mylogins** [comment]
Thanks I will give a try.

**Comment by jota-mylogins** [comment]
OK it works, now is compiled. Thanks
