### ISSUE TITLE
ERROR: invalid base value

### ISSUE THREAD

**Issue by jota-mylogins** [megous/megatools#107]
When I tray any command except megadf, megatools return this errors.
TypeError: invalid base value
          duk_hobject_props.c:2042
          anon /js/session.js:342 preventsyield
          apply native strict preventsyield
          anon /js/libs/gw.js:215 preventsyield
          apply native strict preventsyield
          anon /js/libs/gw.js:167
          anon /js/session.js:421 preventsyield
          apply native strict preventsyield
          dispatch /js/defer.js:17 preventsyield
          apply native strict preventsyield
          dispatch /js/defer.js:46 preventsyield
          [...]

If I can get a verbose error report, please tell me how and I post it if needed.
Thanks!

**Comment by megous** [comment]
Thanks for the report. I've been ill last week. Sorry for the delay.

This means that you have nodes in your filesystem with empty name, but which can be decrypted. importNode function doesn't deal with this edge case gracefully.

I'll fix it.

**Comment by jota-mylogins** [comment]
Dont worry, health comes first.
I did it, well megatools didi it. 
It finally work. Now I can delete this, NO_NAME files using "megatools fixup"
The command apparently works, but return this: (its a screenshot)
http://i.imgur.com/okHdRYd.png
In the capture we can see the return of megatools fixup,
After that I run megatools fixup -n, and nothing returns, so it work
But I think that error can help you to improve the code.

Thanks, if you are interested I can send you some captures with the whole command, becauses I have the same "bad files" in another mega account.

Thanks good job, now my mega account is not oversized by this "NO_NAME files".

**Comment by jota-mylogins** [comment]
Ok, I finally take the screenshot with all the process.
I think this may interest you.
I did the process from the beggining in two different account. In both megatools fixup the "NO_NAME files".

In the first, the command fixup, not return any error.
http://i.imgur.com/jBRisSy.png
Maybe you can fix, the "megatools df" output. Especifically the conversion of negative numbers.
In the output from fixup, not errors only information.

In the second there are the same errors as in my previous comment. But you can see it, now much better.
http://i.imgur.com/TX4C2yQ.png
http://i.imgur.com/W7am1wx.png

I think that with this screenshots you can find the issue and improve the code.
Thanks, megatools is awesome.

**Comment by megous** [comment]
Those were useful screenshots. I identified all the issues. Thanks. :+1:

**Comment by megous** [comment]
BTW, how does it happen that you have more space used than is the total available space?

**Comment by megous** [comment]
Fixup doesn't return anything because that's the default for all commands that are not informational (mv, cp, rm, ...) if there's no error they are completely silent. Unless you use --verbose.

Exception is when you use --dry-run, because that will imply --verbose. It would make no sense otherwise, because --dry-run turns fixup into an informational command.
