### ISSUE TITLE
Error Upload from CURL

### ISSUE THREAD

**Issue by purexo** [megous/megatools#108]
Hello, since two days my savscripts are broken.

Upload :
ERROR: Upload failed for 'siteswebbdd2015-03-06.tar.bz2': Data upload failed: CURL error: Failed sending data to the peer
ERROR: Upload failed for 'apache2015-03-06.tar.bz2': Data upload failed: CURL error: Failed sending data to the peer
ERROR: Upload failed for 'BDD2015-03-06.tar.bz2': Data upload failed: CURL error: Failed sending data to the peer
ERROR: Upload failed for '/root/savsite.sh': Data upload failed: CURL error: Server returned nothing (no headers, no data)
Fin Upload :

I don't know what to do.

**Comment by megous** [comment]
Seems like mega server is dropping connections.

**Comment by megous** [comment]
Does it work now?

**Comment by purexo** [comment]
it's random, some time it work, some time not
