### ISSUE TITLE
Add current speed displayed

### ISSUE THREAD

**Issue by John-Gee** [megous/megatools#109]
Hello,

I found this toolsuite last week and loved it!
Thanks for it.

Here a few additions that I think would be great.

In this case, printing the downloading (or upload) speed.
Right now I am using nethogs to know that, but that seems overkill, curl should be able to give you that information.
Once you have the speed, an ETA could be great as well.

**Comment by megous** [comment]
Hi, showing speed should work.

**Comment by John-Gee** [comment]
Awesome!
