### ISSUE TITLE
megafs/megasync: support file metadata

### ISSUE THREAD

**Issue by crass** [megous/megatools#11]
Currently Mega can not be used as a true backup medium because file metadata is not preserved (eg. file permissions, xattrs, etc..).  It would be nice for this data to be optionally uploaded with the file when using megafs or megasync.

One implementation could be to upload a secondary file  called <filename>.metadata with this information.  As far as I know there's no mechanism native to mega which allows arbitrary data to be associated with a file handle.

**Comment by megous** [comment]
Sync functionality is tracked by issue #20
