### ISSUE TITLE
Match the browser's speed

### ISSUE THREAD

**Issue by John-Gee** [megous/megatools#110]
Hi,

The few times I've used megadl, I felt it was slower than just downloading the files through my browser (chromium).
In simple numbers, in the browser I reach my full speed, 1.5Mb/s but with megadl at best 1Mb/s.
I am not sure why...
The upload speed for megadl for one file is around 15kb/s, so nowhere near enough to slow down my download...
CPU and RAM wise there's also a lot of room...

I am on Arch Linux, using your AUR package.
Thanks!

**Comment by megous** [comment]
Megatools uses only one connection to do the download. Mega.co.nz uses multiple connections. That may make a difference, depending on your network conditions/geographical location.

**Comment by John-Gee** [comment]
Oh I see.
I've seen something related to multiple connections in your backlog for 2.0, would that fix this?

Though, even running a few instances of megatools in parallel (for multiple files), I still don't get above that 1Mb/s total.


Thanks!

**Comment by megous** [comment]
It depends on how mega.co.nz handles spreading connections between multiple data centers (if they have multiple at this point).

Even though you're running two instances, you may be just getting connection to a single data center.

But I don't know, I don't think this is well documented.

**Comment by megous** [comment]
> I've seen something related to multiple connections in your backlog for 2.0, would that fix this?

Yes.

**Comment by John-Gee** [comment]
Got it, cool thanks!

**Comment by zodman** [comment]
+1

**Comment by kashu** [comment]
`I've seen something related to multiple connections in your backlog for 2.0, would that fix this?`
**multiple connections**, I can't wait it...
Thanks!

**Comment by megous** [comment]
Megatools can now upload with multiple parallel connections.

**Comment by John-Gee** [comment]
How about downloading?

**Comment by megous** [comment]
Serial, but I think it's certainly more efficient than the browser. I can download ~80 MiB/s.

**Comment by John-Gee** [comment]
Alright, then good enough!

**Comment by PaulWoitaschek** [comment]
For me megadl gives like 250kbs whereas chrome gives about 4,5 MB / s.
Tested on arch linux using the latest version from the AUR.

**Comment by megous** [comment]
megadl just does the download in 256MiB chunks from whatever URL mega's gives it for download. There's no limit on the megatools side.
