### ISSUE TITLE
Error code not set correctly when using megaput and upload-file is missing

### ISSUE THREAD

**Issue by papst01** [megous/megatools#113]
using version 1.9.94 on Debian Wheezy on a 32bit arm platform:
If I put wrong credentials into the .megarc a "megaput" will not work (that is ok) and I get a error code = 1:
root@camerlengo:~# dbus-launch megaput --path=/Root/test/file.7z /tmp/file.7z
ERROR: Can't login to mega.co.nz: API call 'us' failed: Server returned error ENOENT
root@camerlengo:~# echo $?
1

BUT:
If I do this with correct credentials, but the file which should be uploaded does not exist I get not the error code 1 as assumed:
ERROR: Upload failed for '/tmp/file.7z': Can't read local file /tmp/file.7z: Error opening file: No such file or directory
root@camerlengo:~# echo $?
0

[edit: former error messages problem does not exist - my fault.... I removed this section]

**Comment by megous** [comment]
Fixed in 1.9.98
