### ISSUE TITLE
File overwrite feature when downloading from directory link

### ISSUE THREAD

**Issue by Konstantinusz** [megous/megatools#114]
When downloading with tool "megadl", files are never overwritten. It would be helpful to add this feature, maybe with an option, it would be extremely useful when downloading a Mega directory and redirect it to a named pipe (fifo) in Linux, made with command "mkfifo". For example I can make a fifo "mkfifo movie.avi" and when downloading megadl would overwrite that file / fifo, and send its output to the named pipe, which could be immediately processed with "ffmpeg", for example when encoding or adding / modifying audio streams etc.

When downloading from a simple Mega file link it is not a problem, because one can use "--path -" to send the output to the standard output  and redirect it with ">" into a named pipe.

**Comment by megous** [comment]
You can use megadl --path - too.
