### ISSUE TITLE
Doesn't start in Win Xp 

### ISSUE THREAD

**Issue by dimmer123** [megous/megatools#115]
When I start any tool I get en error "The procedure entry point if_nametoindex could not be located in the DLL IPHLPAPI.DLL" WIn XP Service Pack 3.

**Comment by megous** [comment]
You may retry with 1.9.95. It should work now. I'll close the issue then.

**Comment by dimmer123** [comment]
Thank you. It works!

**Comment by megous** [comment]
Excellent. :+1:
