### ISSUE TITLE
Build static binaries for individual components

### ISSUE THREAD

**Issue by djmattyg007** [megous/megatools#116]
I have very little interest in using mega as a hosting service myself. However, from time to time I find myself needing to download large files from the service that someone else has shared on it. `megadl` is a great tool for this, but I don't really have a use for the rest of the megatools suite. Is there any way I can build a statically linked binary of just `megadl` so everything is nice and self-contained? If not, would it be difficult to add this support?

**Comment by megous** [comment]
It's not easily possible, AFAIK, since gio uses dynamically loaded .so module to load TLS socket code from glib-networking package.

**Comment by djmattyg007** [comment]
It could still be linked dynamically against glib-networking. It would just be all of the megatools code.

**Comment by megous** [comment]
I'm not sure how much code are you trying to build statically. If you just want to build libmega.so statically into each tool, all you need is to pass --disable-shared --enable-static to configure script.

**Comment by djmattyg007** [comment]
Ah, right. It's not obvious that passing --enable-static by itself isn't enough to disable shared library compilation.
