### ISSUE TITLE
Windows: Trailing whitespace in username and/or password in mega.ini causing error.

### ISSUE THREAD

**Issue by acquire** [megous/megatools#117]
Seems like you cannot have any trailing whitespace when entering username and/or password in mega.ini otherwise it causes this error:

<tt>ERROR: Can't login to mega.co.nz: API call 'us' failed: Server returned error ENOENT</tt>

**Comment by megous** [comment]
Yes, whitespace is included in the option value. I believe it is documented.
Dne 13. 4. 2015 6:47 napsal uživatel "acquire" <notifications@github.com>:

**Comment by megous** [comment]
Ah, it's not documented. Megatools 2.0 have less "magical" ini file syntax, so these issues should not happen anymore.
