### ISSUE TITLE
ERROR: Can't login to mega.co.nz: API call 'us' failed: Server returned error ESID

### ISSUE THREAD

**Issue by keyneko** [megous/megatools#118]
Hello, when i megaput a png to MEGA use my my owner account, i got the error returns:

ERROR: Can't login to mega.co.nz: API call 'us' failed: Server returned error ESID, 
OR
ERROR: Can't login to mega.co.nz: API call 'us' failed: Server returned error EARGS

so pls kindly tell me, what's the wrong with it, and how can i to do, tks!

**Comment by megous** [comment]
Not sure. Can you post output with --debug=api, preferably anonymized a bit.

**Comment by keyneko** [comment]
Hi, megous, thanks for your quickly reply! 
maybe i think this occur to my account, i just parked my account recently, for i forgot password.  now I create a new account for testing, and megaput use this new account, there not report the error any more.

add --debug=api, get debug info as follows:
root@localhost:~/Downloads# megaput  --debug=api -u keyneko@live.cn tsps_mac_openNI_Kinect_1.3.3.zip
-> [{
	"a": "ug"
}]
<- -15
-> [{
	"a": "us",
	"user": "keyneko@live.cn",
	"uh": "TsBIBREyyTQ"
}]
<- -15
ERROR: Can't login to mega.co.nz: API call 'us' failed: Server returned error ESID

**Comment by keyneko** [comment]
Ah, forgot to say, use my parked account, i can both log in mega and megaput through local terminal, there seems to be nothing wrong with my account. But it is not running in the server terminal...

**Comment by megous** [comment]
Can you please try this fixed tarball:

https://mega.co.nz/#!7RdXCY6B!5VqanbSa3nparOn9jPn46BrCTy3LhIe05fcroQdxhp4

**Comment by keyneko** [comment]
This is really amazing, I re installed, it worked!
Thank you!

**Comment by megous** [comment]
Cool. :)

**Comment by jeka1** [comment]
reboot your Linux and have a fun =)

**Comment by megous** [comment]
Hahaha. :+1:
