### ISSUE TITLE
API call 'uc' failed: Server returned error EEXIST

### ISSUE THREAD

**Issue by alvgarci** [megous/megatools#119]
Hi:

Just install megatools from homebrew formula and I obtain this error when I'm trying to register my account:

API call 'uc' failed: Server returned error EEXIST

MacBook Pro:~ $ megareg --register --email test@gmail.com --name "name" --password "test"
ERROR: Registration failed: API call 'uc' failed: Server returned error EEXIST

Any help?

I'm now in OSX 10.10.2

Thanks

**Comment by megous** [comment]
Email is probably already registered.

**Comment by alvgarci** [comment]
Right.. you're right. Thanks. After a fast review of the doc you post here, I was not aware that the account needs to be not created. Also I taught that was a mandatory step for using the rest of the tools. Thanks for the response.

**Comment by alvgarci** [comment]
Other question: is there any way to obtain by the full url for downloading  the files previously we upload?

**Comment by megous** [comment]
You can use megals --export

**Comment by alvgarci** [comment]
You're my hero. Thanks a lot. Last question.. why I have this "WARNING: Skipping FS node s8lRUBwR because it has malformed attributes Segmentation fault: 11".. but repeating the command.. just works fine?

**Comment by megous** [comment]
I'm not sure why the segfault happens. Can you run megatools in a debugger? Do you have gdb available?

  gdb
  file path/to/crashing/command
  r
  .... wait for the crash
  bt

> "WARNING: Skipping FS node s8lRUBwR because it has malformed attributes"

This means that megatools failed to parse this node's attributes (maybe the key was invalid).

**Comment by megous** [comment]
Segfault is worrying, but I can't see any obvious issue in the code, so I'm closing this as lacking feedback.
