### ISSUE TITLE
libtool wrong generated

### ISSUE THREAD

**Issue by matteomazza** [megous/megatools#121]
megatools version:  megatools-1.9.95
system version:		Linux 3.2.0-4-amd64 #1 SMP Debian 3.2.63-2+deb7u1 x86_64 GNU/Linux

output of Make:
	$ make
	  GEN    mega/mega-marshal.list
	  GEN    mega/mega-marshal.c
	  GEN    mega/mega-marshal.h
	  GEN    mega/mega-enum-types.c
	  GEN    mega/mega-enum-types.h
	  CC       mega/libmega_la-mega-aes-key.lo
	  CC       mega/libmega_la-mega-rsa-key.lo
	  CC       mega/libmega_la-mega-chunked-cbc-mac.lo
	  CC       mega/libmega_la-mega-http-client.lo
	  CC       mega/libmega_la-mega-http-io-stream.lo
	  CC       mega/libmega_la-mega-http-input-stream.lo
	  CC       mega/libmega_la-mega-http-output-stream.lo
	  CC       mega/libmega_la-mega-aes-ctr-encryptor.lo
	  CC       mega/libmega_la-utils.lo
	  CC       mega/libmega_la-mega-marshal.lo
	  CC       mega/libmega_la-mega-enum-types.lo
	  CCLD     libmega.la
	./libtool: line 7905: func_munge_path_list: command not found
	  CC       tools/df.o
	  CC       libtools/sjson.gen.o
	  CC       libtools/http.o
	  CC       libtools/oldmega.o
	  CC       libtools/tools.o
	  CCLD     megadf
	./libtool: line 7905: func_munge_path_list: command not found
	  CC       tools/dl.o
	  CCLD     megadl
	./libtool: line 7905: func_munge_path_list: command not found
	  CC       tools/get.o
	  CCLD     megaget
	./libtool: line 7905: func_munge_path_list: command not found
	  CC       tools/ls.o
	  CCLD     megals
	./libtool: line 7905: func_munge_path_list: command not found
	  CC       tools/mkdir.o
	  CCLD     megamkdir
	./libtool: line 7905: func_munge_path_list: command not found
	  CC       tools/put.o
	  CCLD     megaput
	./libtool: line 7905: func_munge_path_list: command not found
	  CC       tools/reg.o
	  CCLD     megareg
	./libtool: line 7905: func_munge_path_list: command not found
	  CC       tools/rm.o
	  CCLD     megarm
	./libtool: line 7905: func_munge_path_list: command not found
	  CC       tools/copy.o
	  CCLD     megacopy
	./libtool: line 7905: func_munge_path_list: command not found
	
	

	
make check  output nothing. its return code is 0
	
	
after make install, if I try to run megaput (or some other megatool) of course the output is this:
	$ megaput
	megaput: error while loading shared libraries: libmega.so.0: cannot open shared object file: No such file or directory
	
	
	
	
___________________________________________________________________________________________________________________________________

looking at libtool  at line 7904 / 7905:

	# Definition is injected by LT_CONFIG during libtool generation.
    func_munge_path_list sys_lib_dlsearch_path "$LT_SYS_LIBRARY_PATH"

but in my file, this is the only occurence of "func_munge_path_list"

libtool is generated after the ./configure step, but in the libtool configurations inside the configure scripts does not appear any "func_munge_path_list"

**Comment by megous** [comment]
The issue is probably something else. Check that libmega is in your
LD_LIBRARY_PATH or path specified in ld.so.conf, and can be loaded by the
linker when you run megatools binaries.

**Comment by matteomazza** [comment]
# cat /etc/ld.so.conf.d/libc.conf
# libc default configuration
/usr/local/lib

# ls /usr/local/lib/libmega.so*
/usr/local/lib/libmega.so  /usr/local/lib/libmega.so.0  /usr/local/lib/libmega.so.0.0.0

How can I check if the linker can load it?

**Comment by megous** [comment]
The binary will run ok if it is loaded correctly.

**Comment by matteomazza** [comment]
as I said in the first post,
the binary don't run because it can not load the library

$ megaput
megaput: error while loading shared libraries: libmega.so.0: cannot open shared object file: No such file or directory

**Comment by megous** [comment]
It means it can't find it. You can try running it under strace, to see where the error "libmega.so.0: cannot open shared object file: No such file or directory" comes from. Ie where the linker tries to open the library.

Running the library should work with:
  
  LD_LIBRARY_PATH=/usr/local/lib /usr/local/bin/megals 

for example.

**Comment by megous** [comment]
Also after (if?) you changed /etc/ld.so.conf, did you run ldconfig?

**Comment by megous** [comment]
I assume this is working now.

**Comment by matteomazza** [comment]
no. I moved the binary back in the compilation folder to use it.

Il giorno 12:19 gio 28/mag/2015 Ondřej Jirman <notifications@github.com> ha
scritto:

**Comment by megous** [comment]
Then the solution is obviously as described above. All you need is to setup library loading paths correctly on your system.

Megatools build and work on default debian system without issues.

Alternatively just disable shared library when building megatools by using --disable-shared --enable-static parameters to configure.

**Comment by matteomazza** [comment]
I have never changed any of the above configurations. I've only installed
and configured some other software.
I can static compile them yes... but it is not a way to solve the problem,
it is a way to not have that problem...

Il giorno gio 28 mag 2015 alle ore 12:31 Ondřej Jirman <
notifications@github.com> ha scritto:

**Comment by megous** [comment]
I think you just need to run ldconfig to update ld.so.cache file, or use the LD_LIBRARY_PATH environment variable as described above. You didn't say whether you tried any of this.

See "man ld.so" if you want to know more.

If that fails, you can use strace to determine what linker tries to do, if you want to solve the issue, and not just work around it.

**Comment by matteomazza** [comment]
the problem is that, for now, I don't have time.
Maybe in the future I can open again a bug to solve this problem, is it ok?

Il giorno gio 28 mag 2015 alle ore 14:38 Ondřej Jirman <
notifications@github.com> ha scritto:

**Comment by megous** [comment]
Sure that's ok. I hope that it will work. :)

**Comment by exandeer** [comment]
System version: Linux 3.13.0-67-generic #110-Ubuntu SMP Fri Oct 23 13:25:18 UTC 2015 i686 i686 i686 GNU/Linux (Vultr VPS)

Hi,
I found that this method from <a href=http://askubuntu.com/questions/547481/is-there-a-form-to-upload-files-to-megamega-co-nz-from-ubuntu-serverssh>Ask Ubuntu</a> works:
<pre>sudo apt-get install libtool libglib2.0-dev gobject-introspection libgmp3-dev nettle-dev asciidoc glib-networking
wget http://megatools.megous.com/builds/megatools-1.9.94.tar.gz
zcat megatools-1.9.94.tar.gz > megatools-1.9.94.tar
tar -xf megatools-1.9.94.tar   
cd megatools-1.9.94/
./configure
make
sudo make install
sudo ldconfig</pre> 

then I want to compile the 1.9.95 version, so I cleaning all the stuff:
<pre>sudo make uninstall
sudo make clean
cd ..
sudo rm -rf megatools*</pre>

I repeat the method above except change 1.9.94 to 1.9.95 and then the error occurs.

**Comment by TheWizIL** [comment]
exandeer: Same here. Problem is only in last version.
1.9.94 working perfect, 1.9.95 error "/libtool: line 7905: func_munge_path_list: command not found"

**Comment by omgbox** [comment]
Add the Path
this works for 
> **Ubuntu 12.04**

> export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/:/usr/local/bin/

i've added it in /home/User/.megarc

in ~/.megarc

**Comment by megous** [comment]
You probably meant .bashrc or something similar, because .megarc is an INI file.
