### ISSUE TITLE
Building issue on arm

### ISSUE THREAD

**Issue by typhoon71** [megous/megatools#123]
I'm building megatools on a raspberri pi.

When I "make" I get:
/libtool: line 7905: func_munge_path_list: command not found

Strange enough, after I "sudo make install" megatools does appear to work (megadl does).
What does it mean? Thanks.

**Comment by megous** [comment]
It's just some harmless issue with autotools that are in arch linux currently. Safe to ignore, AFAIK.

**Comment by typhoon71** [comment]
well, I'm building on raspian but it's good to know it's safe.
works quite well btw.
