### ISSUE TITLE
Build error on Ubuntu 14.04

### ISSUE THREAD

**Issue by pepa65** [megous/megatools#125]
I cloned the git repo, I installed the dependencies mentioned in the README for Ubuntu, I ran `autogen.sh`, I did `./configure --enable-docs-build` and then `make`:
[...]
```
CCLD     megadf
/usr/bin/ld: libtools/oldmega.o: undefined reference to symbol 'g_input_stream_get_type'
//usr/lib/x86_64-linux-gnu/libgio-2.0.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[1]: *** [megadf] Error 1
make: *** [all] Error 2
```

**Comment by megous** [comment]
Weird error. Not sure how that can happen. Can you please make V=1

**Comment by megous** [comment]
Also, I suppose, building from tarball works, so this is jsut Ubuntu having autotools that are broken, or megatools doing something that only breaks autotools that are present in Ubuntu.

**Comment by pepa65** [comment]
`make V=1`
```
libtool: link: gcc -pthread -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I./libtools -I./mega -I. -g -O2 -Wno-pointer-sign -Wno-unused-variable -o .libs/megadf tools/df.o libtools/sjson.gen.o libtools/http.o libtools/oldmega.o libtools/tools.o  ./.libs/libmega.so -pthread
/usr/bin/ld: libtools/oldmega.o: undefined reference to symbol 'g_input_stream_get_type'
//usr/lib/x86_64-linux-gnu/libgio-2.0.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[1]: *** [megadf] Error 1
make: *** [all] Error 2
```
I will try building from tarball.

**Comment by pepa65** [comment]
From tarball: `./autogen.sh` then `./configure` and `make`: same thing
```
  CC       libtools/oldmega.o
libtools/oldmega.c: In function ‘update_pathmap’:
libtools/oldmega.c:1434:15: warning: variable ‘prev’ set but not used [-Wunused-but-set-variable]
   GSList *i, *prev, *next;
               ^
  CC       libtools/tools.o
  CCLD     megadf
/usr/bin/ld: libtools/oldmega.o: undefined reference to symbol 'g_input_stream_get_type'
//usr/lib/x86_64-linux-gnu/libgio-2.0.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[1]: *** [megadf] Error 1
make: *** [all] Error 2
```

**Comment by megous** [comment]
There's no autogen.sh in official tarball. 

Here's the tarball: http://megatools.megous.com/builds/megatools-1.9.95.tar.gz

**Comment by megous** [comment]
libtool: link: gcc -pthread -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I./libtools -I./mega -I. -g -O2 -Wno-pointer-sign -Wno-unused-variable -o .libs/megadf tools/df.o libtools/sjson.gen.o libtools/http.o libtools/oldmega.o libtools/tools.o  ./.libs/libmega.so -pthread

Libtool doesn't link with required libraries. -lglib-2.0, etc. That's why the error happens.

**Comment by pepa65** [comment]
From the proper tarball (I downloaded the zip from here before...) it builds. Lots of
`./libtool: line 7905: func_munge_path_list: command not found` though.

Anything I can do about libtool linking the required libraries?

**Comment by megous** [comment]
Those messages are harmless. 

> Anything I can do about libtool linking the required libraries?

I don't know.

**Comment by megous** [comment]
I tried ./autogen.sh on uptodate ubuntu 14.10 and make failed with libtool version mismatch, even though only a single version of libtool was installed by me and there's no libtool in the git. A little crazy.

**Comment by megous** [comment]
Not worth fixing for me. If some other developer will want to work on megatools on Ubuntu, he should be able to fix this. Or if people want to run git version (not recommended at all), they should know what they're doing, and how to fix issues.

For normal users, official tarball should work fine.

**Comment by megous** [comment]
DSO missing from command line error fixed.
