### ISSUE TITLE
stream from mega ?

### ISSUE THREAD

**Issue by lucas794** [megous/megatools#129]
Hey hello , first , i want to say THANKS YOU for this tool , its amazing and i love it.

Also , can be any way to stream a video that you have in your mega account ? Can be it done with the newest version ? (1.9.95)?

Also , i want to update my version (current i have 1.9.93) , how i can update this to 1.9.95 ?

Thanks you

**Comment by megous** [comment]
You can build from source code, the guide is in the README file.

To stream use megaget or megadl and specify --path -. Details are in the man pages for megadl and megaget.
