### ISSUE TITLE
Fedora Build Issues

### ISSUE THREAD

**Issue by gbcox** [megous/megatools#131]
Hello,
I'm packaging megatools for Fedora and a few issues came up during review and I was wondering if you might be able to assist me in figuring them out.  Thanks!
1.  The build log shows two complaints from the debuginfo generator: 
cpio: megatools-1.9.95/sjson.c: Cannot stat: No such file or directory
cpio: megatools-1.9.95/sjson.gen.c: Cannot stat: No such file or directory
2.  rpmlint is giving me the following warnings that weren't resolved by -Wl,--as-needed:
megatools.x86_64: W: unused-direct-shlib-dependency /usr/lib64/libmega.so.0.0.0 /lib64/libpthread.so.0
3.  I was told that I can get debuginfo by adding this to the end of %install:
ln -s libtools/sjson.gen.c
ln -s libtools/sjson.c - but sjson.c does not appear to be available

**Comment by megous** [comment]
Hi,

1.
```
cpio: megatools-1.9.95/sjson.c: Cannot stat: No such file or directory
cpio: megatools-1.9.95/sjson.gen.c: Cannot stat: No such file or directory
```

Seems like there's wrong path in your spec file somewhere.  sjson.c is not directly in the source code root directory, it's under libtools.

2. I'm not sure why is this a problem. libpthread is pulled in by glib2 (via pkg-config), not by megatools themselves, and it is used.

3. This doesn't make sense to me. Both files are available in the official tarball at:

http://megatools.megous.com/builds/megatools-1.9.95.tar.gz

And thanks for trying to package for Fedora. :+1:

**Comment by gbcox** [comment]
Thanks for the quick reply... I looked in libtools and didn't find sjson.c 
I did find sjson.h - is this correct?  If so, not sure why debuginfo is having an issue.  I did
try creating a symbolic link renaming sjson.h to sjson.c and that appeared to solve the issue.  Just
want to make sure I'm not missing something here...

**Comment by megous** [comment]
I see. sjson.c is only in git. It is not necessary to build megatools from the tarball, so it's not included.

**Comment by megous** [comment]
```
I did try creating a symbolic link renaming sjson.h to sjson.c and that appeared to solve the issue. Just
want to make sure I'm not missing something here...
```
This is not a right way to solve the issue. I'm not sure why any of this would be necessary, anyway.

**Comment by gbcox** [comment]
Ok, I'll delete that symbolic link - it was only for test purposes.  Fedora generates a rpm for debugging purposes for all packages by default.  It's looking for sjson.c so it can build it.  Here is the url that explains it:  https://fedoraproject.org/wiki/Packaging:Debuginfo?rd=Packaging/Debuginfo

**Comment by megous** [comment]
I guess it looks for sjson.c because there are #line comments in sjson.gen.c referencing this file.

**Comment by gbcox** [comment]
Thanks, I appreciate you taking the time to look into it.
