### ISSUE TITLE
Username with dash doesn't work on CLI

### ISSUE THREAD

**Issue by thiagoc** [megous/megatools#133]
Example: mega-user@domain.com. The interesting thing is that it works when I put on .megarc.

**Comment by megous** [comment]
Please try running this:

  megals -u mega-test@test.cz --debug

This should output something like
```
-> [{
	"a": "us",
	"user": "mega-test@test.cz",
	"uh": "iAVXHSs1uIQ"
}]
```

You may also compare this with the output of the same user placed in the .megarc file.

**Comment by thiagoc** [comment]
```
thiagoc@tyrion:~$ megals -u m8r-ep93as@mailinator.com --ignore-config-file --debug 
Enter password for (m8r-ep93as@mailinator.com): 
Good, signing in...
-> [{
	"a": "us",
	"user": "m8r-ep93as@mailinator.com",
	"uh": "i-OKunGH2kc"
}]
<- [
	-9
]
ERROR: Can't login to mega.co.nz: API call 'us' failed: Server returned error ENOENT
```

When I run `megals --debug` it doesn't print anything related to debug, only the normal output.

**Comment by megous** [comment]
That's because it's using the cached login information. Though it seems the username is passed correctly to the mega API. Weird.

**Comment by megous** [comment]
It may be password issue though. UH is calculated from the password and the username, so if username is correct, password is probably passed incorrectly.

That would be confirmed if you'd see different "uh", when using .megarc and the same password.

**Comment by thiagoc** [comment]
There's one detail: the password have 512 chars. I doesn't have special chars, but it could be a problem. What do you think?

**Comment by megous** [comment]
That might be an issue. How are you passing the password exactly? Does it work when using --password? Is only the interactive password entry broken?

**Comment by thiagoc** [comment]
Yes, it worked when using the --password parameter. It's a problem with the
interactive password entry.

**Comment by megous** [comment]
Ok, thank you. That's enough information for me. :)
