### ISSUE TITLE
Why I can mount using megafs but can't umount using a normal user?

### ISSUE THREAD

**Issue by thiagoc** [megous/megatools#134]
Is this a bug or a feature?

**Comment by thiagoc** [comment]
On Linux: 

```
thiagoc@tyrion:~$ megafs test_dir/

thiagoc@tyrion:~$ ls -l test_dir/
total 0
drwxr-xr-x 1 root root 0 Dez 31  1969 Contacts
drwxr-xr-x 1 root root 0 Jun 23 12:15 Inbox
drwxr-xr-x 1 root root 0 Jun 23 12:15 Root
drwxr-xr-x 1 root root 0 Jun 23 12:15 Trash

thiagoc@tyrion:~$ mount
megafs on /home/thiagoc/test_dir type fuse.megafs (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)

thiagoc@tyrion:~$ umount test_dir/
umount: test_dir/: Permission denied

**Comment by thiagoc** [comment]
Actually the problem is that the mounted dir and all files/directories under it are owned by root:root.

**Comment by megous** [comment]
You can kill megafs. That should be the same as umount.

**Comment by thiagoc** [comment]
The problem is that I can't access/read files:

```
innovare@tyrion:~$ cp megafs/Root/Caixa/CoWygykPSNJ00004.SFP .
cp: cannot open 'megafs/Root/Caixa/CoWygykPSNJ00004.SFP' for reading: Operation not supported

**Comment by megous** [comment]
Also you should be able to use fuse options to tinker with file ownership and other things. See for example man sshfs section called "FUSE options". You can use the same options with megafs.

**Comment by megous** [comment]
That's not implemented.

**Comment by thiagoc** [comment]
hmm, ok. You could look at this project to implement this: https://github.com/matteoserva/MegaFuse
