### ISSUE TITLE
Problem with configure.ac

### ISSUE THREAD

**Issue by dendisuhubdy** [megous/megatools#136]
~/megatools$ ./autogen.sh
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I m4
configure.ac:13: warning: macro 'AM_PROG_LIBTOOL' not found in library
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf
autoreconf: running: /usr/bin/autoheader
autoreconf: running: automake --add-missing --copy --no-force
Makefile.am:19: error: Libtool library used but 'LIBTOOL' is undefined
Makefile.am:19:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
Makefile.am:19:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
Makefile.am:19:   If 'LT_INIT' is in 'configure.ac', make sure
Makefile.am:19:   its definition is in aclocal's search path.
autoreconf: automake failed with exit status: 1

I think there LT_INIT was supposed to be somewhere in configure.ac. I'm working on 14.04 Ubuntu LTS.

**Comment by megous** [comment]
Please read the readme file and use the official installation method.
