### ISSUE TITLE
megaput - forced upload - overwrite existing file

### ISSUE THREAD

**Issue by ronky** [megous/megatools#142]
Ahoj Ondro,

one question, I didn't see any switch for a forced upload / overwrite existing file in megaput. Do I have to always use delete the file first? Or is this possibility in some other command?

Thanks.
Martin

**Comment by megous** [comment]
Yes, you can do that. I think I have --force option implemented for 2.0 in the dev branch, but I'm not sure. I haven't looked at the code for quite some time.

**Comment by CODeRUS** [comment]
question from 2015, but still
no `--force` options here :)

**Comment by moccajoghurt** [comment]
I am missing that feature too.
