### ISSUE TITLE
change mega.con.nz to mega.nz

### ISSUE THREAD

**Issue by y77ae** [megous/megatools#147]
Hi.

megareg not support mega.co.nz, please change mega.nz

change for new domain.

Thanks.

**Comment by megous** [comment]
Hi, what do you mean?

**Comment by igortrix** [comment]
Hi, change tools/reg.c:

reg.diff 
--- tools/reg.c 2015-04-15 16:44:16.000000000 -0300
+++ tools/reg.c.new     2015-09-04 02:32:15.606261543 -0300
@@ -135,7 +135,7 @@
       return 1;
     }
 
-    gc_regex_unref GRegex* r = g_regex_new("^(?:https?://mega.co.nz/#confirm)?([a-z0-9_-]{80,150})$", G_REGEX_CASELESS, 0, NULL);
+    gc_regex_unref GRegex* r = g_regex_new("^(?:https?://mega.nz/#confirm)?([a-z0-9_-]{80,150})$", G_REGEX_CASELESS, 0, NULL);
     gc_match_info_unref GMatchInfo* m = NULL;
 
     g_assert(r != NULL);

**Comment by memiux** [comment]
> We have launched the new MEGA beta webclient onto our new domain: https://mega.nz/

https://twitter.com/megaprivacy/status/558086492036550659

**Comment by megous** [comment]
Yeah, seems that they discontinued the old website after all.

**Comment by qgustavor** [comment]
Seems it got fixed on 9da13bba560cf92fefb4be43c33e1c3551486032, it isn't?

Also a point about the issue title: as long it's possible don't remove `mega.co.nz` support in future updates to avoid breaking older links.

**Comment by megous** [comment]
Both formats are supproted now. I have to go through the rest of the code though, to see if change is necessary elsewhere too. But I'm too busy atm, to do it.
