### ISSUE TITLE
ERROR: Can't login to mega.co.nz: API call 'us' failed: Server returned error EARGS

### ISSUE THREAD

**Issue by williamwmd** [megous/megatools#148]
[root@bak ~]# megals -u teste@test.com --debug=api
Enter password for (teste@test.com):
Good, signing in...
-> [{
        "a": "us",
        "user": "teste@test.com",
        "uh": "ZRYLXX5Q198"
}]
<- [
        -2
]
ERROR: Can't login to mega.co.nz: API call 'us' failed: Server returned error EARGS

The same error is happening in Ubuntu and Fedora 22
On Fedora:
yum -y install gcc make glib2-devel libcurl-devel openssl-devel gmp-devel tar
yum install megatools

**Comment by megous** [comment]
Weird error. Similar API request works fine for me. Can you login using other method of password entry?

**Comment by williamwmd** [comment]
I'm using the digitalocean, I created a Droplet to test.
The following are the details:

Ubutu: Ubuntu 14.04 x64
Ip: 45.55.64.210
User: root
Password: megatools

Can connect and install whatever it takes

I've run the following commands:

apt-get update
apt-get -y install build-essential libglib2.0-dev libssl-dev libcurl4-openssl-dev libgirepository1.0-dev glib-networking
wget http://megatools.megous.com/builds/megatools-1.9.95.tar.gz
tar xzf megatools-1.9.95.tar.gz
cd megatools-1.9.95
./configure && make && make install && ldconfig
megals -u teste@test.com -p test --debug=api
Result: #ERROR: Can't login to mega.co.nz: API call 'us' failed: Server returned error ENOENT

**Comment by megous** [comment]
Mega usually returns confusing errors. ENOENT means that either password is incorrect or username is incorrect. I can't login with teste@test.com even with mega.co.nz website. That account doesn't exist probably.

**Comment by megous** [comment]
You can remove the virtual server, I can test this locally.

**Comment by williamwmd** [comment]
You are right. It was trouble with my username and password.
Thank you for your help.

**Comment by VD171** [comment]
This still happening.
Any solution?
