### ISSUE TITLE
tool to import public mega links into mega drive

### ISSUE THREAD

**Issue by Ryex** [megous/megatools#151]
if you visit the mega link of a file it gives you the option to import it into your account. can a tool be written to do the same thing in megatools?

**Comment by amper5and** [comment]
Hi, just wondering if importing public links is being worked on now or if it is planned for any specific future release?

**Comment by megous** [comment]
Megatools 2.0 is not being worked on. I'm just maintaining the stable version.

**Comment by megous** [comment]
Though this seems to be implemented in 2.0, so this issue can be closed. 

See: https://github.com/megous/megatools/blob/dev/js/tools/import.js
