### ISSUE TITLE
[Request] Duplicate file name finder / cleaner

### ISSUE THREAD

**Issue by ViperCode7** [megous/megatools#154]
Hi

I do some remote uploading from a server with Go4up and a lot of times I get duplicate files, same content, but that's not the worst part, the worst part is same file name. In windows at least we get a numbering (1) added to file names but here... checked the files they're intact and exactly the same only twice and the duplicate file skip is enabled in the account. Was wondering if there's a way to speed up finding duplicates using this toolset? If not could such a feature be added, especially to megarm?

**Comment by megous** [comment]
Files with the same name in a folder are automatically renamed, so that they can be accessed using unique path.

Content duplicity prevention is best done before upload. Just keep list of content hashes of all files you upload and check against it before uploading a new file using some script.

**Comment by ViperCode7** [comment]
Not quite, this is what a listing looks like:
/Root/114_046.rar
/Root/114_046.rar
/Root/114_047.rar
/Root/114_047.rar
/Root/114_048.rar
/Root/114_048.rar
/Root/114_049.rar
/Root/114_049.rar
/Root/114_050.rar
/Root/114_051.rar
/Root/114_052.rar
/Root/114_053.rar
/Root/114_053.rar
/Root/114_054.rar
/Root/114_055.rar
/Root/114_056.rar
/Root/114_057.rar

Note the duplicate files...

**Comment by megous** [comment]
Ok, thanks. Looks like a regression.

**Comment by ViperCode7** [comment]
Any progress or a date when a fix will be rolled out?

**Comment by megous** [comment]
No, I'm quite busy with regular work.

**Comment by megous** [comment]
dup of #111
