### ISSUE TITLE
Cross-compiling megatools for embedded systems

### ISSUE THREAD

**Issue by tiagoapimenta** [megous/megatools#161]
I have my own system based on [CLFS](http://clfs.org/view/clfs-embedded/arm/) book, thus there is no *glib*, instead there are *musl*, I did the following:

    PKG_CONFIG_PATH=${BUILD}/cross-tools/${BUILD_TARGET}/lib/pkgconfig ./configure \
    --prefix=${BUILD}/targetfs/usr/local \
    --build=${BUILD_HOST} --host=${BUILD_TARGET} \
    --disable-glibtest

But it still tests `glib`:

    checking for GLIB - version >= 2.32.0... no
    *** Could not run GLIB test program, checking why...
    *** The test program failed to compile or link. See the file config.log for the
    *** exact error that occured. This usually means GLIB is incorrectly installed.
    configure: error: Glib 2.32.0 or later is required to build megatools

On my environment the build tools is prefixed by `arm-linux-musleabihf-`

Is it possible to make `megatools` *clib* independent?

**Comment by megous** [comment]
Hi, glib is not libc, it is an utility library build on top of libc. I suppose you should be able to use glib with musl or any other libc.

**Comment by tiagoapimenta** [comment]
My mistake, it works, great job!
