### ISSUE TITLE
Ability to move remote files

### ISSUE THREAD

**Issue by alopezf1987** [megous/megatools#162]
Hi,

Thank you so much for releasing this tool, which is actually quite useful. I'd like to move remote files, for example: **megamv /Root/Backups/Data.tar.gz /Root/Old**

Can you tell me how to edit the code in order to add this new functionality?

Regards.

**Comment by megous** [comment]
You can try the dev branch. It contains implementation of megatools mv.

**Comment by alopezf1987** [comment]
Thanks, how can I compile the source code under Windows?

**Comment by megous** [comment]
The source code uses autotools, so you would need msys or something similar + all the dependencies (there's 14 of them). It's fairly standard procedure and it's A LOT of work.

But be warned, that dev branch doesn't support windows at all at the moment.

I cross-build megatools for windows on linux.

It's much simpler to do it on linux, and only choice if you want to use the dev branch.

**Comment by alopezf1987** [comment]
Thank you very much, but we need the binaries for Win32, so I'll wait for a new release. While this is done, I'll use [megacmd](https://www.google.com "t3rm1n4l's megacmd").

Regards!
