### ISSUE TITLE
curl error on windows

### ISSUE THREAD

**Issue by steom** [megous/megatools#164]
megaput install.wim
install.wim: 0% - 272,0 KiB of 2,5 GiB
ERROR: Upload failed for 'install.wim': Data upload failed: CURL error: Failure when receiving data from the peer

**Comment by megous** [comment]
Transient issue?

**Comment by steom** [comment]
systematic with large files

testbed win7 32bit 2gb ram

**Comment by megous** [comment]
dup of #236
