### ISSUE TITLE
Why megaput cannot read from stdin?

### ISSUE THREAD

**Issue by izderadicka** [megous/megatools#165]
I've been trying to use megaput with standard input in piped script.   It does not seem to have such possibility?   - or no argument  does not work.   megaget can output to stdout, so it would be nice to have similar possibility for megaput.
Named pipes are also not working.

**Comment by megous** [comment]
It is not possible, because the size of input is not known beforehand. Size is required for mega.nz API, before you can start upload.

**Comment by izderadicka** [comment]
On 27.11.2015 21:27, Ondřej Jirman wrote:
>
> It is not possible, because the size of input is not known beforehand. 
> Size is required for mega.nz API, before you can start upload.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/megous/megatools/issues/165#issuecomment-160200388>.
>
OK I see, diky Ondro
I.
