### ISSUE TITLE
Homebrew: SHA256 mismatch

### ISSUE THREAD

**Issue by L3viathan** [megous/megatools#168]
When I try to install megatools using Homebrew, it successfully downloads the dependencies, but then fails to install megatools itself:

```
==> Downloading http://megatools.megous.com/builds/megatools-1.9.95.tar.gz
==> Downloading from https://megatools.megous.com
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: a46a560c8769b40f073fd27b321d6b89f8ac0f0ca73e6ed83047c2619fe6b437
Actual: 1d9501470d4f8f50aa463cfd33ec67785182c4295fa818e8dd2018f758bc21bc
Archive: /Library/Caches/Homebrew/megatools-1.9.95.tar.gz
To retry an incomplete download, remove the file above.
```

**Comment by megous** [comment]
Hi, you can fix that by changing url to https:// version.

I should fix the http -> https redirect in the meantime, so that it
preserves the requested path.

regards,
  o.

2015-12-16 19:47 GMT+01:00 Jonathan Oberländer <notifications@github.com>:

> When I try to install megatools using Homebrew, it successfully downloads
> the dependencies, but then fails to install megatools itself:
>
> ==> Downloading http://megatools.megous.com/builds/megatools-1.9.95.tar.gz
> ==> Downloading from https://megatools.megous.com
> ######################################################################## 100.0%
> Error: SHA256 mismatch
> Expected: a46a560c8769b40f073fd27b321d6b89f8ac0f0ca73e6ed83047c2619fe6b437
> Actual: 1d9501470d4f8f50aa463cfd33ec67785182c4295fa818e8dd2018f758bc21bc
> Archive: /Library/Caches/Homebrew/megatools-1.9.95.tar.gz
> To retry an incomplete download, remove the file above.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/megous/megatools/issues/168>.
>



-- 
Ondřej Jirman, http://megous.com, 799 794 947

**Comment by megous** [comment]
Should be fixed for quite a while now.
