### ISSUE TITLE
ERROR: Can't login to mega.co.nz: API call 'us' failed: Server returned error ESID

### ISSUE THREAD

**Issue by sasousuke** [megous/megatools#170]
Hello, when i megaput a file to MEGA use my owner account, i got the error returns:
ERROR: Can't login to mega.co.nz: API call 'us' failed: Server returned error ESID
sasousuke: ~ $ megals --version
megatools 1.9.95 - command line tools for Mega.co.nz
 
Written by Ond?ej Jirman <megous@megous.com>, 2013
Go to http://megatools.megous.com for more information
sasousuke: ~ $ megals --debug=api
-> [{   
        "a": "ug"
}]
<- -15
-> [{   
        "a": "us",
        "user": "sasousuke@gmail.com",
        "uh": "7LsKSXoWlc8"
}]
<- -15
ERROR: Can't login to mega.co.nz: API call 'us' failed: Server returned error ESID

**Comment by omgbox** [comment]
re-compile megatools again,   

make sure settings file megarc is correct
username is your user change it. 

it should be under /root/.megarc  or ~/home/username/.megarc 

[Login]
Username = xxxxxxx@xxx.com
Password = XXXXX

i had this stupid problem today, and just discovered how to fix it. hope this helps. there is better api tools in ruby called rmega-dl   look it up on google. easier to setup. and downloads from urls.txt

**Comment by sasousuke** [comment]
Thanks for this tip. I download again the source, recompilling all and work very well. :D (y)
Salu2

**Comment by megous** [comment]
ESID means wrong password or username in mega.nz's API lingo.
