### ISSUE TITLE
Event not found error on ubuntu

### ISSUE THREAD

**Issue by ashutosh2k12** [megous/megatools#171]
I am trying to download a single file https://mega.nz/#!XIAVEKRK!Ix0TVFEftlSA6jJ4jYaBBv1UIdyg_cau9_v-nUVOLfw

```
./megaget https://mega.nz/#!XIAVEKRK!Ix0TVFEftlSA6jJ4jYaBBv1UIdyg_cau9_v-nUVOLfw
-bash: !XIAVEKRK!Ix0TVFEftlSA6jJ4jYaBBv1UIdyg_cau9_v-nUVOLfw: event not found
```

I also tried .co.nz for same link which failed too. i.e https://mega.co.nz/#!XIAVEKRK!Ix0TVFEftlSA6jJ4jYaBBv1UIdyg_cau9_v-nUVOLfw

**Comment by ashutosh2k12** [comment]
Looks like the link has to be wrapped within single braces. Still getting "remote file not found error", while the file still exists

**Comment by megous** [comment]
.co link should work

**Comment by pafgoncalves** [comment]
This has nothing to do with megatools. It's the shell that is interpreting the !
Try:
<code>./megaget 'https://mega.nz/#!XIAVEKRK!Ix0TVFEftlSA6jJ4jYaBBv1UIdyg_cau9_v-nUVOLfw'</code>

**Comment by megous** [comment]
You're right, thanks for helping out. :+1:
