### ISSUE TITLE
Curl error

### ISSUE THREAD

**Issue by 4ng3lp** [megous/megatools#173]
Hi,
i have a strange error. Many commands seem to work properly but megaput (and megacp) doesn't work
~/tmp/megatools-1.9.95 # megaput Makefile
Makefile: 42% - 32,0 KiB of 75,2 KiB
Makefile: 42% - 32,0 KiB of 75,2 KiB
Makefile: 42% - 32,0 KiB of 75,2 KiB
ERROR: Upload failed for 'Makefile': Data upload failed: CURL error: Failed sending data to the peer.

thank's!

**Comment by megous** [comment]
Dup #164 .
