### ISSUE TITLE
megamkdir should create parent directories if not exist

### ISSUE THREAD

**Issue by CramericaIndustries** [megous/megatools#174]
megamkdir should make parent directories as needed

example:
  megamkdir /Root/test1/test2/test3/test4/
throws an error "Parent directory doesn't exist" if at least one of the test1-3 dirs do not exist

it should have an option like unix's mkdir:
  mkdir -p /test1/test2/test3/test4

**Comment by megous** [comment]
Already implemented:

https://github.com/megous/megatools/blob/dev/js/tools/mkdir.js

**Comment by CramericaIndustries** [comment]
can you please provide an example?
'megamkdir --help'    tells me that    '-p'   is for providing the password
and when I do
  megamkdir --parents /Root/a/b/c/d
it says
  "ERROR: Option parsing failed: Unknown option --parents"

**Comment by megous** [comment]
It is in the dev branch, not in stable. Example is in the file I linked.

**Comment by CramericaIndustries** [comment]
ah okay of course I got the stable, thx.
