### ISSUE TITLE
API call 'f' failed: Invalid response JSON

### ISSUE THREAD

**Issue by pettersonfaria** [megous/megatools#178]
$megadl 'https://mega.nz/#F!AY42TLzQ!9QXhoN1cO_w7ewEBXkHoMw'
ERROR: Can't open folder 'https://mega.nz/#F!AY42TLzQ!9QXhoN1cO_w7ewEBXkHoMw': API call 'f' failed: Invalid response JSON

Any suggestion?

**Comment by megous** [comment]
Is it persistent? I copied the f response from the browser and it parses ok with sjson which megatools uses. It's not even too big, just 300kB.

**Comment by pettersonfaria** [comment]
Yes, persist. I try in windows and linux with 1.9.96 version.
Did you try this command ?
$ megadl <previous url>

**Comment by megous** [comment]
Oh, I see what's going on. Mega is sending gzipped response, even though megatools is not advertising support for gzip compression in the http header.

Perhaps they only do it for large responses.

**Comment by pettersonfaria** [comment]
So, I can only wait for? :(
Is it a possible new feature or no way?

**Comment by megous** [comment]
I would need to write support for gzipped responses.

**Comment by megous** [comment]
It's fairly easy, I suppose.

**Comment by pettersonfaria** [comment]
Ok, I'll waiting for.
Let me know, when you get!
If possible, use this link that I used to test, please ;)

**Comment by loren321** [comment]
I'm having the same issue when I try `megadl 'https://mega.nz/#F!uQwwEbQR!OLb1tEyOhV24c7RduIW_xA'
`
Is there a workarond?

**Comment by stivennoni77** [comment]
Same issue, we gotta wait for the gzip patch

**Comment by megous** [comment]
Should work now. Try the 1.9.97 version.

**Comment by megous** [comment]
Windows build is also improved: the included libcurl now uses windows schannel  for SSL, which means that OS supplied certificates are used for verification.

Perhaps not an improvement to some, because this allows crap like antispyware, antivirus and such to intercept SSL connections made by megatools without notice, while previously you'd get an error when using such programs while connecting to mega with megatools.

**Comment by loren321** [comment]
Thanks

**Comment by stivennoni77** [comment]
@loren321 Is it fixed for you ?

**Comment by WeissJT** [comment]
I just installed megatools on ArchLinux and I'm getting this error.
$ megadl --debug api,fs,cache 'https://mega.nz/#F!hpBCSbCC!vZNs1Qhip_UJQPSSdoZjUg'
-> [{
	"a": "f",
	"c": 1,
	"r": 1
}]
ERROR: Can't open folder 'https://mega.nz/#F!hpBCSbCC!vZNs1Qhip_UJQPSSdoZjUg': API call 'f' failed: Invalid response JSON

**Comment by megous** [comment]
Please try the git master version.

**Comment by WeissJT** [comment]
Thanks, it's working now.

**Comment by nionis** [comment]
how did you build the git master version ?

**Comment by megous** [comment]
1. download https://github.com/megous/megatools/archive/master.zip
2. extract
3. install dependencies
4. ./autogen.sh && make   (if something fails goto 3.)
5. make install (will install into /usr/local/*)

**Comment by nionis** [comment]
thanks!
