### ISSUE TITLE
Add upload resume support / save state in case of crash

### ISSUE THREAD

**Issue by crass** [megous/megatools#18]
A nice feature for megaput and megasync would be to save the upload state periodically, such that the upload can be resumed.  This is particularly helpful for when the program crashes near the end of a long upload.

Shouldn't be too hard to implement.  I'd suggest creating a state file with the same basename as the uploaded file so that the program can automatically resume.  I think all the state file needs is (offset, aes_key, nonce/iv, mac, upload url).  It might be good to put file size and/or the mac of the first N bytes for file verification.

I did some preliminary work on this with the old api, but haven't looked to see how hard it might be in the new one.

**Comment by cornop** [comment]
:thumbsup:

**Comment by megous** [comment]
This is implemented during transfer now. Megatools will re-upload parts of the file that failed to upload for non-fatal reasons. Full resume after a complete upload failure is probably not realistic for mega.nz api. It's not clear what the validity of mega's temporary upload URLs is and generally their api is quite picky and failure states are not well docummented.
