### ISSUE TITLE
Can't open local file for writing: Error opening file: File name too long

### ISSUE THREAD

**Issue by PotcFdk** [megous/megatools#183]
Sometimes, when using megadl, I get this error when trying to download a file with that has a really long file name:
`ERROR: Download failed for '[url]': Can't open local file [filename] for writing: Error opening file [path to filename]: File name too long`

Apparently megadl doesn't have a command line parameter to specify a custom file name, which could have been considered a workaround.

Can a `-o` parameter be added, and possibly a better solution to the problem above (if there is one)?

**Comment by megous** [comment]
How long is the filename?

**Comment by megous** [comment]
Also, is this on windows or linux?

**Comment by PotcFdk** [comment]
Here is an example file https://mega.nz/#!lZ5Q3IKL!zxQx19YwYHyJmOI13wIiualXVW5PYmwpqyXpDes1Xww
>windows or linux?

GNU/Linux

**Comment by megous** [comment]
There are various limits on maximum path size, filename size, etc.

**Comment by PotcFdk** [comment]
Well, _obviously_ there are various limits. That's what this bug report is all about. If there were no limits, this bug wouldn't exist.
Please re-read the bug report, as there seems to be at least one way to enable users to still download a file in such a case; whereas doing nothing leads to people being completly unable to download certain files.
