### ISSUE TITLE
I can not download this encrypted link

### ISSUE THREAD

**Issue by steam7** [megous/megatools#185]
![untitle1231d](https://cloud.githubusercontent.com/assets/16367828/13211003/8040d04a-d913-11e5-9b3f-dae73c0454b4.JPG)

this is the link
https://mega.nz/#N!CA8SCYzI!vf_VIlNK6mAfsvt-wCcn2SXCN-zeJEZ23z5ysGkqNuI=###n=eds3WDpb

and the original
https://mega.nz/#F!eds3WDpb!imq91_iprHOmEvc7shWZ_Q

**Comment by megous** [comment]
How did you get the N! link?

**Comment by steam7** [comment]
with Mipony 

![desctop screenshot](https://cloud.githubusercontent.com/assets/16367828/13234043/7c25a472-d995-11e5-8e70-e457ddbc9450.png)

**Comment by megous** [comment]
Nothing happens when you put the link in the browser. This is non-standard link.

It will not be supported by megatools.
