### ISSUE TITLE
megaput stuck at 100%

### ISSUE THREAD

**Issue by fturco** [megous/megatools#187]
I'm trying to upload my backup archive to Mega using `megaput` but it gets stuck at 100 %, without returning to the shell prompt.

    $ megaput backup-2016-02-29.tar.xz.gpg 
    backup-2016-02-29.tar.xz.gpg: 100% - 76.3 MiB of 76.3 MiB

From the web interface I cannot see the file, so I think it hasn't been uploaded.

I tried to add the `--debug` option, but I'm reluctant to paste the output here because I fear there may be personal informations in the debug output. Am I wrong?

**Comment by megous** [comment]
Upload happens in three phases.
1) get upload endpoint for the data
2) upload file data, this returns data handle to be used in 3)
3) add node to the filesystem (associate filename with the data)

This looks like 3) hangs up. Does this happen for other uploads too? How long it stays at 100%? Megatools will retry the operation with exponential backoff, so if mega servers are busy, it may hang for up to 8 minutes I think.

**Comment by fturco** [comment]
I tried again but this time I measured the time needed for the upload to finish. For a file of 77 MiB it needed more than 39 minutes. I simply didn't wait enough before.

**Comment by megous** [comment]
That seems excessively long.

**Comment by fturco** [comment]
Tried yet another time. Same file. It goes from 0 to 100% in 11 minutes, then it is stuck at 100% for another 17 minutes, for a total of 28 minutes.

**Comment by Cysioland** [comment]
Same happens for me with `megacopy` in upload mode.

**Comment by megous** [comment]
Not much to do if the server is slow to respond.
