### ISSUE TITLE
Network speed is Intermittent

### ISSUE THREAD

**Issue by kashu** [megous/megatools#188]
My issue: 
1) Network speed is Intermittent when use **magedl** to download a public folder(directory link).
2) Always stucked when download one public folder's files

OS: `Xubuntu 14.04.4 LTS 64-bit`
Version: `megatools-1.9.97.tar.gz`
Installation method: `compile from tarball`

I tried several times.
When I use `megadl` to download a public **directory link** from mega.nz, I found the **network speed is intermittent and very slow**. It seems that the network is extremely **unstable**.

But, when I use the `Chromium web browser` to down it, the network speed is **perfect**.
And, when I  use `magedl` command to download a **individual file**, the network speed is **also very fast**.

Appreciated for developing such a set of cool tools.

**Comment by zodman** [comment]
take a look at: https://github.com/megous/megatools/issues/110#issuecomment-78215626

**Comment by kashu** [comment]
@zodman 
Thank you. Got it.

`I've seen something related to multiple connections in your backlog for 2.0, would that fix this?`
**multiple connections**, I can't wait it...
