### ISSUE TITLE
Build breaks with "You need to use --enable-docs-build if building from git tree"

### ISSUE THREAD

**Issue by RealDolos** [megous/megatools#190]
I don't want to build the docs at all.

**Comment by megous** [comment]
So just comment out the code in Makefile.am temporarily.

**Comment by RealDolos** [comment]
That's what I temporarily did. Permanently this should be fixed, tho, so @megous reopen this issue pls

**Comment by RealDolos** [comment]
As in, --disable-docs-build should work (or a similar option should be present) to disable doc building

**Comment by megous** [comment]
I guess, it should work so that you can build docs from git and from official tarball, even if make dist from the git was done with disabled docs build.

**Comment by megous** [comment]
I tried to fix it but it's just too complicated for no real benefit.

**Comment by Craeckie** [comment]
For those having trouble with this, you can remove the docs-section of the Makefile:
`sed -i '/# {{{ docs/,/# }}}/d' Makefile.am`
After that run bash autogen.sh and you are good to go :)

**Comment by wdlkmpx** [comment]
I think a have fix for this in https://github.com/wdlkmpx/megatools/commit/0932db2f11dff3395130270c6585d76f778ad6fb

It works here when
1) asciidoc is not installed/asiidoc is broken
2) asciidoc generates all the man pages

I'm not sure if it's good enough to create a pull request... perhaps megous can test it and create a release tarball to see it it works as expected..

**Comment by megous** [comment]
Hi, with your solution make will not update manpages if the txt files are changed. I can lead to inconsistent results when doing the release, because I can forget running autogen.sh before make distcheck.

I fixed the issue in the master branch, so that dist packages work regardless of --enable/disable-docs used on configure time.

You can now simply pass --disable-docs to autogen.sh when building from git.

**Comment by wdlkmpx** [comment]
Yeah I can confirm it works now. I was practicing shell scripting haha. Thanks.

**Comment by megous** [comment]
Thanks too! :)
