### ISSUE TITLE
megatools on raspberry pi 2

### ISSUE THREAD

**Issue by pyraylos** [megous/megatools#196]
hi. my raspberry is running xbian. i tried to install megatools from source and after running "configure" i get the error:
checking for LIBCURL... no
configure: error: Package requirements (libcurl) were not met:
No package 'libcurl' found
Consider adjusting the PKG_CONFIG_PATH environment variable if you installed software in a non-standard prefix.

then i did an "apt-get install libcurl3" and the output was:
libcurl3 is already the newest version.

i searched for any libcurl devel package and found only the "libcurl4-openssl-dev" package. trying to install that i got the error:
The following packages have unmet dependencies:
 libcurl4-openssl-dev : Depends: libcurl3 (= 7.38.0-4+deb8u2) but 7.37.1-1 is to be installed

any help?

**Comment by megous** [comment]
Did you try running the command from the README?

**Comment by pyraylos** [comment]
which command? if you mean this command for dependencies:
 apt-get -y install build-essential libglib2.0-dev libssl-dev libcurl4-openssl-dev libgirepository1.0-dev

then yes i already did that.

**Comment by megous** [comment]
Seems like it didn't succeed though, given the error message above. I'd ask xbian support for what may be going wrong, and why installation of libcurl4-openssl-dev fails, if I were you.

**Comment by pyraylos** [comment]
ok. thanks for the reply.
