### ISSUE TITLE
Remote file not found error

### ISSUE THREAD

**Issue by ashutosh2k12** [megous/megatools#200]
I am trying to download a link with megaget on ubuntu LTS 14.04. Here is the command:

`./megaget 'https://mega.nz/#!XIAVEKRK...'`

This was working earlier on on Dec 25, 2015. While I tried today, it is giving me this error:
```
ERROR: Download failed for 'https://mega.nz/#!XIAVEKRK....': Remote file not found: https://mega.nz/#!XIAVEKRK...
```
I also tried putting `.co` extension but it didn't worked. Any ideas?

**Comment by megous** [comment]
Hi, the correct command for exported links is megadl.
