### ISSUE TITLE
[dev branch]: make: *** [src/js-misc.gen.c] Error 127

### ISSUE THREAD

**Issue by tukusejssirs** [megous/megatools#201]
#### Issue Description
I wanted to test current dev branch, but when I wanted to run the `make` command, I’ve got this output:
```bash
  GEN      src/js-misc.gen.c
/bin/sh: -s: command not found
Makefile:1067: recipe for target 'src/js-misc.gen.c' failed
make: *** [src/js-misc.gen.c] Error 127
```
Here’s [make -d output](https://github.com/megous/megatools/files/253475/make_-d_output.txt).

#### What I Did
```bash
git clone <repository>
cd <src-dir>
./autogen.sh
./configure --enable-docs-build
make
```

#### Additional Info
**distro**: Arch Linux
**bash**: GNU bash, version 4.3.42(1)-release (x86_64-unknown-linux-gnu)
**make**: GNU Make 4.1
**gcc**: gcc version 5.3.0 (GCC)
**pkg-config**: 0.29.1
**curl**: curl 7.48.0 (x86_64-pc-linux-gnu) libcurl/7.48.0 OpenSSL/1.0.2h zlib/1.2.8 libidn/1.32 libssh2/1.7.0

#### Dependencies (from `README` file)
```bash
:: Synchronising package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
warning: pkg-config-0.29.1-1 is up to date -- skipping
warning: gcc-5.3.0-5 is up to date -- skipping
warning: make-4.1-3 is up to date -- skipping
warning: glib2-2.48.0-2 is up to date -- skipping
warning: curl-7.48.0-1 is up to date -- skipping
warning: gmp-6.1.0-3 is up to date -- skipping
warning: nettle-3.2-2 is up to date -- skipping
 there is nothing to do
```

**Comment by megous** [comment]
Dependencies are for the regular build. If you runb autogen.sh, you need more.

Try isntalling re2c.

**Comment by tukusejssirs** [comment]
Okay, installing `re2c` solved this issue. But could you, then, update/modify [dev/README](https://github.com/megous/megatools/blob/dev/README)?
