### ISSUE TITLE
FEATURE REQUEST: sync multiple separate folders & sync from shared with me folders of other users with full read-write access

### ISSUE THREAD

**Issue by tukusejssirs** [megous/megatools#202]
Although I know that `megatools sync` is not yet working/coded, I’d like to have the ability to sync many directories from mega to different locations on my local machine.

Also, I have full/read-write access to other mega accounts, so I’d like to have to ability to modify data saved in there accounts, too, and also sync some folders from their accounts.

Thank you in advance.

**Comment by megous** [comment]
Aside from "megatools sync" itself, this is better solved by scripting, than directly in megatools.
