### ISSUE TITLE
megaput: undefined symbol: tool_convert_filename

### ISSUE THREAD

**Issue by xZero707** [megous/megatools#203]
I'm trying to run megaput through cron but this error shows and command fails. 

Running "**megaput filename.ext**" normally in terminal works well -  as long as it isn't executed through **cron** or using **/usr/bin/megaput**.

Before "**megaput: undefined symbol: tool_convert_filename**" I had two different errors but I fixed them:

Error #1:
> error while loading shared libraries: libssl.so.1.0.2: cannot open shared object file: No such file or directory

- Fix: 

>  ln -s /usr/lib/x86_64-linux-gnu/libssl.so /usr/lib/libssl.so.1.0.2

Error #2:
> error while loading shared libraries: libcrypto.so.1.0.2: cannot open shared object file: No such file or directory

- Fix:

> ln -s /usr/lib/x86_64-linux-gnu/libcrypto.so /usr/lib/libcrypto.so.1.0.2

**Comment by xZero707** [comment]
Fix for this is to run **/usr/local/bin/megaput**. But why **/usr/bin/megaput** doesn't work as well?

**Comment by megous** [comment]
Do you have multiple installations of megatools in multiple places on the same machine? How did you install it?

**Comment by megous** [comment]
Anyway, you're just missing the correct LD_LIBRARY_PATH environment variable in your crontab. And unless you know what you're doing, you should use have just a single installation of megatools on your computer, otherwise you may end up with older binary using the newer libmega library, from the other installation, etc.

**Comment by xZero707** [comment]
No. It's very first installation. Installed by compiling from source:
```
./configure
make
make install
```

Anyway, it works now, just as expected. I really like this project, keep up good work!
I using it as part of automated backup script, so backup is always uploaded to Mega cloud.

**Comment by megous** [comment]
Very good. :) I got confused by you talking about multiple paths for the megaput binary.
