### ISSUE TITLE
Make uses /tmp

### ISSUE THREAD

**Issue by Jyree** [megous/megatools#206]
Hi, I wanna build megatools on my pi, but through pariotioning of my disk /tmp has only 1MB of free space in the best case of course. So, how can fix it? Get such errs in make log
`libtools/oldmega.c:4144:1: fatal error: error writing to /tmp/ccBHN50X.s: No space left on device
`
I'm trying to build the latest version of sources i got from site

**Comment by megous** [comment]
Mount ramdisk over /tmp for the build? It's crude, but it should work.
