### ISSUE TITLE
Add support for OpenSSL 1.1.0

### ISSUE THREAD

**Issue by bertogg** [megous/megatools#208]
Looks like Megatools can't be built with OpenSSL 1.1.

Here's the list of API changes:

https://wiki.openssl.org/index.php/1.1_API_Changes

**Comment by megous** [comment]
There doesn't seem to be anything relevant to megatools on that list. Megatools only use libcrypto, not libssl. Are there any changes in libcrypto? What build errors are you getting?

**Comment by bertogg** [comment]
These are the errors (and warnings):

```
mega/mega-rsa-key.c: In function 'mega_rsa_key_generate':
mega/mega-rsa-key.c:517:3: warning: 'RSA_generate_key' is deprecated [-Wdeprecated-declarations]
   key = RSA_generate_key(2048, RSA_3, NULL, NULL);
```

```
mega/mega-rsa-key.c:531:32: error: dereferencing pointer to incomplete type 'RSA {aka struct rsa_st}'
   rsa_key->priv->p = BN_dup(key->q);
                                ^
```

```
libtools/oldmega.c: In function 'rsa_key_gen':
libtools/oldmega.c:776:3: warning: 'RSA_generate_key' is deprecated [-Wdeprecated-declarations]
   key = RSA_generate_key(2048, RSA_3, NULL, NULL);
```

```
libtools/oldmega.c:787:20: error: dereferencing pointer to incomplete type 'RSA {aka struct rsa_st}'
   k->p = BN_dup(key->q);
                    ^
```

```
libtools/oldmega.c: In function 'put_process_data':
libtools/oldmega.c:2943:5: warning: implicit declaration of function 'AES_ctr128_encrypt' [-Wimplicit-function-declaration]
     AES_ctr128_encrypt(data->buffer->data, buffer, bytes_read, &data->k, data->iv, data->ecount, &data->num);
     ^
```

```
libtools/tools.c: In function 'openssl_locking_callback':
libtools/tools.c:106:14: error: 'CRYPTO_LOCK' undeclared (first use in this function)
   if (mode & CRYPTO_LOCK)
              ^
```

**Comment by megous** [comment]
Thank you. Hmm, seems like the api chnaged quite a bit in libcrypto too.

I guess there's still some time, before 1.1.0 starts hitting the distributions. I'll work on it when it gets into [testing] repo of Arch Linux. Until then, it's probably too soon.

The dev branch of megatools no longer uses openssl, so this only is relevant for stable version.

**Comment by bertogg** [comment]
Yeah, in the Debian case there's still some months, but the OpenSSL maintainer has already explained the situation so package maintainers have time to notify the upstream developers.

**Comment by megous** [comment]
Good to know the approximate timing. Thank you.

**Comment by megous** [comment]
Fixed.

**Comment by bertogg** [comment]
Hey, do you expect to make a release soon? The Debian freeze is getting closer and I'm wondering if I should wait for a new release, or try to backport your patch to 1.1.97.

**Comment by megous** [comment]
Hi, I'll make new release in a few days, if that helps.

**Comment by bertogg** [comment]
Yes, thanks!

**Comment by megous** [comment]
Released :)
