### ISSUE TITLE
Getting an error trying to download a folder

### ISSUE THREAD

**Issue by cyian-1756** [megous/megatools#209]
When ever I try to download from this (WARNING: copyrighted and nfsw content) https://mega.nz/#F!AYZA3SgJ!Sx-uBoUmQEj3Bfg3NmOFLQ link using megadl I get 

`ERROR: Can't open folder 'https://mega.nz/#F!AYZA3SgJ!Sx-uBoUmQEj3Bfg3NmOFLQ': API call 'f' failed: Invalid response JSON` 

I'm using version 1.9.97 on ubuntu 16.04 installed from the ubuntu repos.

**Comment by megous** [comment]
I'll release new stable version soon, where this is fixed. You can try building megatools from the pre-release package, if you want. Here: https://github.com/megous/megatools/releases/download/1.9.98-pre1/megatools-1.9.98.tar.gz
