### ISSUE TITLE
Curl error

### ISSUE THREAD

**Issue by masterkey12338** [megous/megatools#211]
ERROR: Upload failed for 'test.txt' Data upload failed: CURL error: Send failed since rewinding of the data stream failed

what does this error mean?
im using the windows binary on a 64 bit machine 8GB ram

**Comment by masterkey12338** [comment]
C:\Users\Nicky\Desktop\Black-Hat 32bit Rewrite>megaput.exe --config mega.ini tes
t.txt

** (megaput.exe:14684): CRITICAL **: decode_node_attrs: assertion 'attrs != NULL
' failed
WARNING: Skipping FS node VMw0iYoT because it has malformed attributes

** (megaput.exe:14684): CRITICAL **: decode_node_attrs: assertion 'attrs != NULL
' failed
WARNING: Skipping FS node JMQ1XY4K because it has malformed attributes

** (megaput.exe:14684): CRITICAL **: decode_node_attrs: assertion 'attrs != NULL
' failed
WARNING: Skipping FS node kAwwXarI because it has malformed attributes

** (megaput.exe:14684): CRITICAL **: decode_node_attrs: assertion 'attrs != NULL
' failed
WARNING: Skipping FS node BFhBDTiQ because it has malformed attributes

** (megaput.exe:14684): CRITICAL **: decode_node_attrs: assertion 'attrs != NULL
' failed
WARNING: Skipping FS node 0NInDSoZ because it has malformed attributes

** (megaput.exe:14684): CRITICAL **: decode_node_attrs: assertion 'attrs != NULL
' failed
WARNING: Skipping FS node xFYiTIga because it has malformed attributes

** (megaput.exe:14684): CRITICAL **: decode_node_attrs: assertion 'attrs != NULL
' failed
WARNING: Skipping FS node QUJR3RRa because it has malformed attributes
Uploaded test.txt

i also gets this error

**Comment by megous** [comment]
Latter warnings are just that. Warnings. Megatools was not able to decode all nodes in the mega's filesystem.

The first error is from libcurl. I don't think it's error in megatools.
