### ISSUE TITLE
make error while compiling for headless Debian Jessie armel

### ISSUE THREAD

**Issue by zohebs** [megous/megatools#217]
hey @megous -
Am unable to get make run successfully using the git repo (megatools 1.9.98). here's what happens:

`zohebs@qnap:/usr/src/megatools$ **sudo ./autogen.sh**
zohebs@qnap:/usr/src/megatools$ **sudo ./configure**
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking whether make supports nested variables... (cached) yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for ranlib... ranlib
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.16... yes
checking for GLIB - version >= 2.32.0... yes (version 2.42.1)
checking for OPENSSL... yes
checking for LIBCURL... yes
checking for a2x... /usr/bin/a2x
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands

Configured features:

  docs build: yes
  warnings: no

Run make now.

NOTE: On FreeBSD, you need to use GNU make (gmake)

zohebs@qnap:/usr/src/megatools$ **sudo make**
  GEN      docs/megadf.1
  GEN      docs/megadf.1
a2x: WARNING: --destination-dir option is only applicable to HTML based outputs
a2x: ERROR: "xmllint" --nonet --noout --valid "/usr/src/megatools/docs/megadf.xml" returned non-zero exit status 127
Makefile:1172: recipe for target 'docs/megadf.1' failed
make: *** [docs/megadf.1] Error 1`

please help, thank you

**Comment by Jalle19** [comment]
Getting the same on Debian Wheezy (x86)

**Comment by Jalle19** [comment]
Running `./configure --disable-docs` fixes it.

**Comment by zohebs** [comment]
That worked @Jalle19. Many thanx :)
