### ISSUE TITLE
API call 'g' failed: HTTP POST failed: CURL error: Couldn't resolve host name

### ISSUE THREAD

**Issue by lpallard1** [megous/megatools#219]
When I try to download from publicly accessible folders, I randomly get this error message:

ERROR: Download failed for 'https://mega.nz/XXXXXXXXXXXXXXXXXXXXXXX': API call 'g' failed: HTTP POST failed: CURL error: Couldn't resolve host name

If I add a "co" between the "mega" and "nz" in the address it will work.  Sometimes its working without the "co".  Basically, if I get the error message shown above, I modify the address (add or remove the "co") and it will work.

Running:
megatools 1.9.97 - command line tools for Mega.nz

**Comment by megous** [comment]
Adding .co doesn't matter. It is stripped anyway. You have intermittent issues with domain name resolution on your system.

You may try setting up caching DNS server on your computer, or something like that.

**Comment by megous** [comment]
Or you may try using different DNS servers.

**Comment by blotsome** [comment]
I had this issue, slightly different error "API call 'g' failed: HTTP POST failed: CURL error: Couldn't connect to server" and found Pi-Hole was blocking this, so I had to whitelist the domain lu.api.mega.co.nz

**Comment by megous** [comment]
@blotsome Just be aware, that megatools is now using g.api.mega.co.nz.
