### ISSUE TITLE
megacopy on linux doesn't handle correctly utf-8 in directory names

### ISSUE THREAD

**Issue by marcellmars** [megous/megatools#220]
on Debian (4.6.0-1-rt-amd64)
Package: megatools
Version: 1.9.97-1

megacopy does recognize already existing directories if not utf-8 (and correctly doesn't upload files already upoaded). if directory names contains non Latin characters it uploads the duplicate version of directory with its whole content (all files).

**Comment by megous** [comment]
File names in mega.nz should be UTF-8, because that's what JSON mandates, and JSON is used for the metadata and file name.

Megatools does filename re-encoding based on your locale settings. Can you please share those?
