### ISSUE TITLE
megreg is broken

### ISSUE THREAD

**Issue by RealDolos** [megous/megatools#221]
because verify links are now loooong... remove the `150` from the regex

**Comment by megous** [comment]
I tried creating new account and I get strlen(verify_link) == 128

**Comment by RealDolos** [comment]
Well, here is an example of what I am getting:
```text
https://mega.nz/#confirmaW2JyIYsZuaf3ORHUHdYiccj2Ka6Uf13vQhn4V6lekbewFRTsAQAUkGxbL-nNVFtZWdhci45YmU5Zzg3YTk1ZmY0MKViYjQ5ZjU5MTAzNjc4N2EwMEBhaXJtYWlsLmNjCW1lZ2FyLjliZTkzODdhOTVIZjQwZWJiNDlmNTkxMDM3Nzg3YTAwIDliZTkzODdhOTVmZjQwZWJiNDlmNTkxMDM2Nzg3YTAwElPPr3FSkcg 
```
260 chars

I think they are encoding the email and/or password in that and I generate long ones ;)

**Comment by megous** [comment]
Ah, you're right. I'll extend the limit. Thank you.
