### ISSUE TITLE
API call 'g' failed: HTTP POST failed: CURL error: Problem with the SSL CA cert

### ISSUE THREAD

**Issue by zkxs** [megous/megatools#222]
Built megatools-1.9.97 from source on Ubuntu 14.04.4. I get the following error:

```
michael@HAL-9000:~/tmp$ megadl 'https://mega.nz/#!nB13lT6b!39Yy9P7iC7HsgyMMI_JrzteYtqA3qUEzPuqCzpl6JDk'

ERROR: Download failed for 'https://mega.nz/#!nB13lT6b!39Yy9P7iC7HsgyMMI_JrzteYtqA3qUEzPuqCzpl6JDk': API call 'g' failed: HTTP POST failed: CURL error: Problem with the SSL CA cert (path? access rights?)
```

The link is to a non-sensitive file of my own creation, so no need to redact it.  I've tested this with four links so far, and get the same error for all of them. If I run `curl https://mega.nz/#!nB13lT6b!39Yy9P7iC7HsgyMMI_JrzteYtqA3qUEzPuqCzpl6JDk` it works fine.

**Comment by megous** [comment]
Looks like libcurl (?) configuration error. Megatools can't access 

    $ url-config --ca

file.

**Comment by zkxs** [comment]
It should be able to access that just fine.

```
michael@HAL-9000:~$ curl-config --ca
/etc/ssl/certs/ca-certificates.crt
michael@HAL-9000:~$ namei -m /etc/ssl/certs/ca-certificates.crt
f: /etc/ssl/certs/ca-certificates.crt
 drwxr-xr-x /
 drwxr-xr-x etc
 drwxr-xr-x ssl
 drwxr-xr-x certs
 -rw-r--r-- ca-certificates.crt
```

I've also tried running megadl as sudo, to no avail.

**Comment by megous** [comment]
So perhaps it's a libcurl configuration error. It may be trying to access different file. You can try strace to see what file it tries to access.

**Comment by zkxs** [comment]
After [some grepping](https://gist.github.com/zkxs/80ab5d5061891591bb5641860a0f803d), it appears to be looking for some things in `/etc/pki/nssdb/`.

**Comment by megous** [comment]
According to https://curl.haxx.se/docs/sslcerts.html

    RedHat ships with an additional module, libnsspem.so, which enables NSS to read the OpenSSL PEM CA bundle. 

So perhaps you need to install some PEM module on Ubuntu too? This doesn't look like megatools specific issue.

Last time I tried building on Ubuntu I didn't need to jump through hoops to make megatools work. Do you have some non-standard configuration?

**Comment by megous** [comment]
Also debian has various libcurl version in the repository, which use different ssl backends, so perhaps you may need to install the openssl or gnutls one?

**Comment by zkxs** [comment]
I think my Ubuntu configuration should be pretty standard.  The only tinkering I've done has been to the window manager.

It looks like the openssl and guntls libcurl versions are [both already installed](https://gist.github.com/zkxs/e1afefc82b016d6b6822adb5f37a9671).

Comparing the strace output for [megadl](https://gist.github.com/zkxs/740e6203f92cab76acecafeb1eaa7961) and [curl](https://gist.github.com/zkxs/252600be67b4a0ccd950a4c3f1e6e920) to the same https url (the one from my example), it looks like the significant difference is curl uses `libcurl.so.4` whereas megadl uses `libcurl-nss.so.4`

Is there a way I can build megatools to use the openssl libcurl instead of the nss version?

**Comment by megous** [comment]
Sorry, I have no clue. It's a debian packaging issue, which I know not much about.

Perhaps you can try Alberto Garcia's megatools package for debian sid, or look at how it is built.

**Comment by blotsome** [comment]
I had this issue, slightly different error "API call 'g' failed: HTTP POST failed: CURL error: Couldn't connect to server" and found Pi-Hole was blocking this, so I had to whitelist the domain lu.api.mega.co.nz

**Comment by darkistan** [comment]
When I start copying, I get the following error.
The command is as follows   megacopy --local /mnt/data/dump --remote /Root/SHADOW-SRV/HTZ
error.
ERROR: Upload failed for /Root/SHADOW-SRV/HTZ/vzdump-qemu-105-2021_09_28-23_15_1                                                                                                                                                             8.vma.zst: API call 'p' failed: HTTP POST failed: CURL error: SSL connect error F

Tell me what is the reason for the error?
