### ISSUE TITLE
Trailing spaces in .megarc should be ignored

### ISSUE THREAD

**Issue by fnorf** [megous/megatools#225]
I just ran into the `ERROR: Can't login to mega.nz: API call 'us' failed: Server returned error ENOENT` problem and both my username and password looked fine. Only when looking very closely at my config, I realised that I had a trailing space on my username.

Please trim the username and password in the config, I don't think whitespace would be allowed in those anyways.

**Comment by megous** [comment]
Space is a valid character. INI file is perhaps not the most transparent format from the prespective of the user (leading space is ignored, while trailing space is not + there are escaping rules for some characters), but the specification is quite clear:

https://developer.gnome.org/glib/stable/glib-Key-value-file-parser.html

> Space before and after the '=' character are ignored. Newline, tab, carriage return and backslash characters in value are escaped as \n, \t, \r, and \, respectively. To preserve leading spaces in values, these can also be escaped as \s.

Perhpas extending the docs might help.

**Comment by fnorf** [comment]
in the INI file yes, but not in a username or password for Mega.nz.

**Comment by megous** [comment]
You can have space in the password. You may or may not not be able to enter it using their web client (I haven't tried), but there's no technical reason you can't have it.

Email is of course different, and perhaps could be trimmed.
