### ISSUE TITLE
megaput returns 0 (EXIT_SUCCESS) despite error

### ISSUE THREAD

**Issue by bertogg** [megous/megatools#229]
A Debian user reported this:

In some cases, megaput returns a zero (EXIT_SUCCESS) exit status
even though the upload failed.

This could lead to data loss if users write scripts which
assume that the return value is meaningful
(e.g. "megaput myfile && rm -f myfile")

Example:

$ megaput Important_data.zip
ERROR: Upload failed for 'Important_data.zip': Data upload failed: CURL error:
Failure when receiving data from the peer
$ echo $?
0

**Comment by Son9o** [comment]
seconded on:
ERROR: Upload failed for 'log.log': File already exists: /Root/log.log
returns 0

**Comment by megous** [comment]
Thanks for the report. Fixed in 1.9.98
