### ISSUE TITLE
Bulk download 

### ISSUE THREAD

**Issue by giacomofabbri** [megous/megatools#230]
Hi guys! I'd like to know if there is a way to download more than one link, I mean, is there a way to put some links on a queue and the automatically download it??
If it's possible how?? Is there a way to put the megadl in background? So I can continue to use the terminal as usual, let me know, thanks guys!!

**Comment by didix16** [comment]
Hi. The answer is yes.
What is your OS? In Linux you can do the following:

megadl 'link1' 'link2' 'linkN' &
With the & at the end, the process will be executed  at background and then you will be able to continue using the terminal.

Hope it helps.

**Comment by megous** [comment]
Thanks for helping didix16.
