### ISSUE TITLE
Move/Rename files?

### ISSUE THREAD

**Issue by liar666** [megous/megatools#231]
Hi,

Thanks a 1000 times for this very great suite of tools ! Command synopsis are quite "counter intuitive"/"not as simple as could be" at times (eg. the --path/--remote or the way to get the share link) but it's easy to find the docs & get used to the syntax. 

I was trying to find how to rename/move a file with the megatools, and came across this entry:
https://github.com/megous/megatools/blob/dbdd81ce92fa501c2eb8f266647dc8e58512b794/NEWS
"- Remove megamv as it is not and will not be implemented in 1.9 branch"

Is there a reason why it has been removed? And a workaround to rename/move a file with branch 1.9 ?

**Comment by megous** [comment]
Hi, it was removed, because it was not implemented.

Rename/move is implemented in the dev branch.
