### ISSUE TITLE
megaput with find (xargs)

### ISSUE THREAD

**Issue by keerthionedge** [megous/megatools#232]
This is an enhancement request.
**Why:** My files are spread across all the places and i like to find and upload them by type and create date. (-print0 at end of the find don't give the results with quote (file & folder name have spaces in them), and i don't find an way to pass the the files with quote )
**How i do it now:** I take results of find and replace '\n' with open and close quote with space between them. and pass it as argument.
**Ideal way:** find ....... | xargs megaput --path /Root/.....

**Comment by megous** [comment]
Why would this not work? You need to pass -0 to xargs, so that it understands \0 terminated arguments list on its stdin.
