### ISSUE TITLE
megacopy – undocumented error: "ERROR: Skipping file <file>"

### ISSUE THREAD

**Issue by curusarn** [megous/megatools#233]
`megacopy` skips certain files, why? Error happens multiple times for same file. I couldn't find any documentation for the error.
eg.: `ERROR: Skipping file sp1/OTS/node_modules/.bin`
`ERROR: Skipping file sp1/OTS/node_modules/.bin`
`ERROR: Skipping file sp1/reactjs`
`ERROR: Skipping file sp1/reactjs`

**Comment by megous** [comment]
Hi, it's the first line in the description section: https://megatools.megous.com/man/megacopy.html

**Comment by curusarn** [comment]
Thanks for reply.
First line in the description section says:
> Sync remote and local directories. No files are ever overwritten or removed.

I get `ERROR: File already exists at <path>` when file exists.
What is the cause of this error: `ERROR: Skipping file <file>`?

**Comment by megous** [comment]
You're right. It's a different error. I changed it to warning.

The issue is that the file is neither a regular file nor a directory, so it is skipped.
