### ISSUE TITLE
Checking status (online/offline) of mega links?

### ISSUE THREAD

**Issue by failure-exit** [megous/megatools#234]
Hi!

I really like "megatools", so thanks for developing and sharing!

Is it possible to "just" check if a link is still valid (and if so, perhaps also get the file size)?
I don't think it can be done at the moment but maybe I overlooked something?

Thanks in advance for your help!

**Comment by megous** [comment]
Hi, you're right there's no command to do it.

**Comment by JayBrown** [comment]
I'd second that. I often have to check if published public download links on Mega and other sites are still alive, but without downloading them. So a simple command `megack <link>` with stdout `online` or `offline` would be awesome.

With single links it should be fine, but I don't know how this would work with public folders incl. several files. Maybe the command could simply output a list like

```
Mega folder: <FolderName>
#!9oI3gJqR!d7voSid89nkbFtUb7WpYmVXvuLyusqjGNBKn_dO9ELl        online
#!9oI3gJqR!d7voSid89nkbFtUb7WpYmVXvuLyusqjGNBKn_dO9ELJ        offline
#!9oI3gJqR!d7voSid89nkbFtUb7WpYmVXvuLyusqjGNBKn_dO9ELK        online
```
and then we could grep/awk the stuff ourselves.

Tried getting the source with curl, wget, lynx & w3m, and that doesn't work.

**Comment by megous** [comment]
This API call should be enough:

POST https://eu.api.mega.co.nz/cs
[{"a":"g", "g":1, "ssl":0, p:"9oI3gJqR"}]

Like this:
curl --data-ascii '[{"a":"g", "g":1, "ssl":0, p:"9oI3gJqR"}]' https://eu.api.mega.co.nz/cs

**Comment by megous** [comment]
-9 means not existing

**Comment by JayBrown** [comment]
Yeah, that's a step in the right direction. Cannot write the output to a variable, though… always returns -2 or [-2], whether online or offline.

Test for online file
```
CODE="xlRFxASR"
DUMP=$(/usr/bin/curl --data-ascii '[{"a":"g", "g":1, "ssl":0, "p":"$CODE"}]' https://eu.api.mega.co.nz/cs)
echo "$DUMP"
```

Test for offline file
```
CODE="9oI3gJqR"
DUMP=$(/usr/bin/curl --data-ascii '[{"a":"g", "g":1, "ssl":0, "p":"$CODE"}]' https://eu.api.mega.co.nz/cs)
echo "$DUMP"
```

It only works directly in the shell.

Online: `/usr/bin/curl --data-ascii '[{"a":"g", "g":1, "ssl":0, "p":"xlRFxASR"}]' https://eu.api.mega.co.nz/cs`
Offline: `/usr/bin/curl --data-ascii '[{"a":"g", "g":1, "ssl":0, "p":"9oI3gJqR"}]' https://eu.api.mega.co.nz/cs`

**Comment by megous** [comment]
Here's your answer:

    CODE=qweqwe echo '[{"a":"g", "g":1, "ssl":0, "p":"'$CODE'"}]'

**Comment by megous** [comment]
I'm glad it works.

**Comment by JayBrown** [comment]
Couldn't resist and scripted a quick workflow for macOS—never liked launching jDownloader all the time ;) —, and the `curl` thing is part of it. Thank you again, and especially big thanks for the megatools. Pretty awesome.

https://github.com/JayBrown/MEGA-D-l

**Comment by Salamander3** [comment]
Hey guys, i'm trying this with folder links without luck.
Folder links have an F before the !
It doesn't matter if i write it with or without the F i get -11 (Access violation) but these are public folders i'm using to test. Any idea how to get it to work? Thanks!

**Comment by megous** [comment]
Folder links have different API. Look at the mega.nz API docs, or through megatools code. You shoud be able to find out what it is exactly, and modify the cURL command above.
