### ISSUE TITLE
Can I download sequentially and in parallel under Windows?

### ISSUE THREAD

**Issue by membrillo2** [megous/megatools#237]
Hi, my friends.

In GNU/Linux I use the following for sequential downloads:

`$ megadl $(cat link_list.txt)`

Also in GNU/Linux I use the following for parallel downloads:

`$ cat link_list.txt | xargs -n1 -P4 megadl`

Can I do the same in Windows?

PD: `--speed-limit` option no works for me in Megatools 1.9.98 under Debian Jessie AMD64

Thanks in advance.

**Comment by megous** [comment]
No idea, but you can install mingw and get bash and other utils on windows too.

**Comment by membrillo2** [comment]
Well, I found how to download sequentially from a text file:

`for /f "delims=" %i in ('type link_list.txt') do megadl %i`

But parallel downloads seem harder...

Salute.

**Comment by membrillo2** [comment]
Well, I found how to download sequentially from a text file:

`for /f "delims=" %i in ('type links.txt') do megadl %i`

But parallel downloads seem harder...

Salute.

**Comment by megous** [comment]
I'm glad you found part of the solution, but please don't reopen this issue, it has nothing to do with megatools. It's a question for windows command line documentation.
