### ISSUE TITLE
ignoring .megarc

### ISSUE THREAD

**Issue by fustbariclation** [megous/megatools#240]
I've created ~/.megrc in both a user and a root directory.

I've re-booted the machine.

I've made the permissions 500. I've made sure the ownership is correct.

However, when I run 'megadf', it still asks for my email.

Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

megatools 1.9.97

**Comment by megous** [comment]
Does it work with `megadf --config ~/.megarc`? Is the content of the config file correct?

**Comment by kpirnie** [comment]
I'm having the same issue.   Even when specifying the `--config`

**Comment by megous** [comment]
Check that lines do not end with whitespace.

**Comment by Erusy** [comment]
Command output:
> $ megadf --config ~/.megarc
>ERROR: Failed to open config file: /home/user/.megarc: Key file contains line ';1MiB/s' which is not a key-value pair, group, or comment

Configuration example from manpage shipped with debian testing version (1.9.98-1):
>[Login]
>Username = user@mail
>Password = password
>[Network]
>; 1MiB/s
>SpeedLimit=1024
>; Use over TOR
>;Proxy = socks5://127.0.0.1:9050

It seems that .ini-format parser is not working correctly.
Deleting all comments does the trick, here is my working config:
>[Login]
>Username = user@mail
>Password = password
>[Network]
>SpeedLimit = 1024

**Comment by megous** [comment]
Comment character is # . See this for details of the format:

https://developer.gnome.org/glib/stable/glib-Key-value-file-parser.html
