### ISSUE TITLE
Symbol lookup error

### ISSUE THREAD

**Issue by avto** [megous/megatools#241]
Megatools not working. 
My version is megatools-1.9.98.
OS - Centos 6.7
Kernel - 2.6.32-642.4.2.el6.x86_64

megadf 
**megadf: symbol lookup error: megadf: undefined symbol: g_mutex_init**

megals
megals: symbol lookup error: megals: undefined symbol: g_mutex_init

**Comment by megous** [comment]
Please report this downstream to the binary package distributor. I can't help with this issue.

**Comment by dikkatdeli** [comment]
i get the same error how can we solve it ?

**Comment by megous** [comment]
You need to identify the person that packaged megatools for you and ask him.

**Comment by megous** [comment]
The most probable issue is that you're missing some dependency. Newer version of glib perhaps.

**Comment by megous** [comment]
Anyway, the packager has to fix this. I can't help.

**Comment by avto** [comment]
Here the solution!
copy that two lines to your bash script after #!/bin/bash

```
export LD_LIBRARY_PATH=/usr/local/glib-2.32/lib/  
export PKG_CONFIG_PATH=/usr/local/glib-2.32/lib/pkgconfig
```

**Comment by dikkatdeli** [comment]
@avto which bash script ?

**Comment by avto** [comment]
I am using a bash script to upload all backup files automatically to mega.cz if you don't use bash script. Login to your server and paste that commands one by one before use to mega commands. It will work!
```
export LD_LIBRARY_PATH=/usr/local/glib-2.32/lib/  
export PKG_CONFIG_PATH=/usr/local/glib-2.32/lib/pkgconfig
```

**Comment by megous** [comment]
The second line is unnecessary for running megatools.

**Comment by avto** [comment]
yea first one is enough.
