### ISSUE TITLE
password with special characters in megarc not working

### ISSUE THREAD

**Issue by albaldi** [megous/megatools#243]
Hi, I have a password with this special characters: |"_:]=!?\\-

I can log-in from the command line
`megadf -u my@ma.il -p 'p|a"_s:s]=w?o\r-d'`
or 
`megadf -u my@ma.il `
and then paste the password

but when
```
[Login]
Username = my@ma.il 
Password = p|a"_s:s]=w?o\\r-d
```
```
megadf --config megarc
ERROR: Can't login to mega.nz: API call 'us' failed: Server returned error ENOENT
```

Should I escaple more characters other then \ ?

thanks

**Comment by megous** [comment]
https://github.com/GNOME/glib/blob/master/glib/gkeyfile.c#L4191

Looks like you need to escape leading space as \s leading tab as \t and then \r, \n and ; (list separator) \ also has to be escaped as \\

**Comment by albaldi** [comment]
found it.
Was a extra space at the end.
My bad

thanks
