### ISSUE TITLE
Many dependencies to install

### ISSUE THREAD

**Issue by extensionsapp** [megous/megatools#244]
Hello.

I install megatools in this way:

```
aptitude clean
aptitude -y -q install build-essentials pkg-config libglib2.0-dev \
    libssl-dev libcurl4-openssl-dev libfuse-dev glib-networking gcc \
    asciidoc make
wget \
    https://megatools.megous.com/builds/megatools-1.9.98.tar.gz \
    -qO m.tar.gz && \
tar -xzf m.tar.gz && cd megatools* && ./configure && make && make install && ldconfig
```

<img width="465" alt="screenshot_1" src="https://cloud.githubusercontent.com/assets/8192379/21468564/5671a370-ca21-11e6-8dfe-9bc290594d53.png">

All the packages to install hold 1.5 GB of data. Is there any way to avoid the installation of such a large package dependencies?

**Comment by albaldi** [comment]
After building megatools you can remove all the dev packages.
Or if you are using debian/ubuntu you can use the precompiled packages in thos repo
Debian - https://packages.debian.org/stretch/megatools
Ubuntu - https://launchpad.net/ubuntu/+source/megatools

**Comment by extensionsapp** [comment]
@albaldi how to install in Debian 7/8 x64?

My sources.list
```
deb http://httpredir.debian.org/debian jessie main contrib non-free
deb-src http://httpredir.debian.org/debian jessie main contrib non-free
deb http://httpredir.debian.org/debian jessie-updates main contrib non-free
deb-src http://httpredir.debian.org/debian jessie-updates main contrib non-free
deb http://security.debian.org/ jessie/updates main contrib non-free
deb-src http://security.debian.org/ jessie/updates main contrib non-free
deb http://nginx.org/packages/debian/ jessie nginx
deb-src http://nginx.org/packages/debian/ jessie nginx
deb http://mirror.de.leaseweb.net/dotdeb/ jessie all
deb-src http://mirror.de.leaseweb.net/dotdeb/ jessie all
```

**Comment by albaldi** [comment]
@extensionsapp 
you are right, megatools are present in  _stretch_ (Debian 9).

You could try:
replace _jessie_ with _stretch_
```
apt-get update
apt-get install megatools 
```
and see if there aren't too dependencies 
not forget to replace _jessie_ back

Or you could download the deb from here
https://packages.debian.org/stretch/amd64/megatools/download
```
dpkg -i /path/megatools_1.9.98-1_amd64.deb
apt-get install --fix-missing
```
and cross your finger.

**Comment by extensionsapp** [comment]
@albaldi Hello. I have a problem in install.

```
# apt-get install libssl-dev
Чтение списков пакетов… Готово
Построение дерева зависимостей
Чтение информации о состоянии… Готово
Уже установлена самая новая версия libssl-dev.
обновлено 0, установлено 0 новых пакетов, для удаления отмечено 0 пакетов, и 1 пакетов не обновлено.
~# dpkg -i megatools_1.9.98-1_amd64.deb
Выбор ранее не выбранного пакета megatools.
(Чтение базы данных … на данный момент установлено 47820 файлов и каталогов.)
Подготовка к распаковке megatools_1.9.98-1_amd64.deb …
Распаковывается megatools (1.9.98-1) …
dpkg: зависимости пакетов не позволяют настроить пакет megatools:
 megatools зависит от libssl1.1 (>= 1.1.0), однако:
  Пакет libssl1.1 не установлен.

dpkg: ошибка при обработке пакета megatools (--install):
 проблемы зависимостей — оставляем не настроенным
Обрабатываются триггеры для man-db (2.7.0.2-5) …
При обработке следующих пакетов произошли ошибки:
 megatools
```

**Comment by albaldi** [comment]
Ok, megatool depend on:
ibc6 (>= 2.14) - Jessie use [libc6 (2.19-18+deb8u6)](https://packages.debian.org/jessie/libc6)  OK
libcurl3 (>= 7.16.2)  - Jessie use [libcurl3 (7.38.0-4+deb8u5)](https://packages.debian.org/jessie/libcurl3) OK
libglib2.0-0 (>= 2.35.9) - Jessie use [libglib2.0-0 (2.48.0-1~bpo8+1)](https://packages.debian.org/jessie-backports/libglib2.0-0)  OK

libssl1.1 (>= 1.1.0) - Jessie use [libssl1.0.0 (1.0.2j-1~bpo8+1) ](https://packages.debian.org/jessie-backports/libssl1.0.0) NOT OK

Now if you like to **RISK** you can download the libssl from  stretch, before doing so **have a backup**, because a lot of packages depends on libssl and changing it **could break something.**

https://packages.debian.org/stretch/amd64/libssl1.1/download
and install it with dpkg -i then reinstall megatools.

**Comment by extensionsapp** [comment]
@albaldi Thanks for the help, found a perfect way to:
```
VER=`lsb_release -cs`
sed -i s/${VER}/stretch/g /etc/apt/sources.list
apt-get update && apt-get -y -q install megatools
sed -i s/stretch/${VER}/g /etc/apt/sources.list
apt-get update
```

**Comment by megous** [comment]
The only sane way is to compile the megatools yourself, unless you want to mess up your distribution if you don't exactly know what you're doing by mixing up distribution sources.

You can probably reduce build deps quite a bit by not using build-essentials. You should only need make, pkg-config, gcc, binutils and library headers. asciidoc is not necessary. Many packages in build-essentials are not probably needed either.
