### ISSUE TITLE
Upload in background, --quiet option?

### ISSUE THREAD

**Issue by albaldi** [megous/megatools#245]
I run
`megacopy --local ~/Downloads/UP/ --remote /Root --reload --no-progress &
`
Worked fine except for the multiple 
```
F /Root/filename1.zip
F /Root/filename2.zip
etc
```
popping on my terminal.

Is there a quiet option?

**Comment by megous** [comment]
You can send stdout to /dev/null. Errors should still go to to stderr sou you shouldn't miss them.
