### ISSUE TITLE
man page error --speed-limit should be --limit-speed

### ISSUE THREAD

**Issue by albaldi** [megous/megatools#246]
Just tried  
`megacopy --reload --no-progress --speed-limit 80 ...`
and got a 

> ERROR: Option parsing failed: Unknown option --speed-limit

```
megacopy --help-network
Usage:
  megacopy [OPTION...] - synchronize local and remote mega.nz directories

Network Options:
  --limit-speed=SPEED         Limit transfer speed (KiB/s)
  --proxy=PROXY               Proxy setup string

```

man megacopy 

> --speed-limit <speed>
>            Set maximum allowed upload and download speed in KiB/s. This option overrides config file settings. 0 means no limit.

**Comment by megous** [comment]
Fixed. Thanks.
