### ISSUE TITLE
megatools_bash_completion

### ISSUE THREAD

**Issue by albaldi** [megous/megatools#250]
I write a simple bash_completion
```
#    Copyright (c) 2017 albaldi
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

_megatools()
{
    local cur prev opts
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    opts="--help --help-all --help-basic --help-network --help-auth --config --ignore-config-file --debug --version --limit-speed --proxy --username --password --no-ask-password --reload --names --recursive --long --header --human --export --mb --gb --total --used --free --remote --local --download --no-progress --dryrun --disable-previews --path --print-names --name --email --register --verify --scripted"
	
    case "${prev}" in
		--config)
			_filedir && [[ $cur == - || -z $cur ]] && COMPREPLY+=( - )
			return 0
			;;
		--local|--path)
			COMPREPLY=( $(compgen -f ${cur}) )
			return 0
			;;
		*)
		;;
	esac

    if [[ ${cur} == -* ]] ; then
        COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
        return 0
    fi
}
complete -F _megatools megacopy megadl megals megaput megarm megadf megaget megamkdir megareg

```

To install should be enough place it in 
`~/.bash_completion/`

KNOW ISSUES

- Not complete with = (example --con[tab] complete to --config and not --config=)
- --path complete only directory, even if megaget state _Local directory or file name, to save data to_
- Single - are not supported, because I'm lazy
- Only --config, --local, --path complete with their stuff.
- Completion complete all options for every command, even if is not supported by the command.

TODO
- add support for single -
- support only specific options for each command
- completion of PATH,OPTS,SPEED,PROXY etc for --debug , --limit-speed --proxy etc options
- completion of = for  --limit-speed, --config, --proxy, --username, --password etc

**Comment by megous** [comment]
Please license the script under GPLv 3 (you can copy license header from one of the megatools source files and just change my name for yours) and I will include it in the contrib/ folder in the megatools package. Distribution packagers will be perhaps able to pick it up from there and add it to the binary packages, so that completion works out of the box for users. Others will be able to improve on it too.

Thank you.

**Comment by albaldi** [comment]
fixed, btw I used the [Fair License ](http://fairlicense.org/) because is short.

**Comment by megous** [comment]
Committed, thank you.
