### ISSUE TITLE
Ignore local symlinks on upload

### ISSUE THREAD

**Issue by DaeMonSx** [megous/megatools#251]
It would be welcome to add a symlink option to command line.
For some this could be a good solution who are using megacopy to backup local folders.

At the moment the megacopy will try to copy all the symlinks as well, this prevents us from using megacopy as backup tool.

example: 
www folder contains a page/cloud with symlinks to all folders and files,
but i would like to have a copy on mega just with local www folder, not all the hard drive contents.

**Comment by megous** [comment]
Makes sense.

**Comment by megous** [comment]
Done.
