### ISSUE TITLE
use timestamp freom server on local file

### ISSUE THREAD

**Issue by artifexor** [megous/megatools#253]
Please use and set the timestamp from server on local file. At the moment the local timestamp is the timestamp of download time which is not ideal.

Because megals is able to detect the timestamp on server I think it is possible to set local file timestamp.

**Comment by artifexor** [comment]
I have an embryonic version which working fine with openssl 1.0 but failed with openssl 1.1. Waiting to find out how to compile with openssl 1.1 then trying to generate a pull request.

**Comment by megous** [comment]
Tracked as part of issue #20
