### ISSUE TITLE
"get download link" for directories?

### ISSUE THREAD

**Issue by liar666** [megous/megatools#255]
Hi,

I recently discored here, in a response in an issue, that it is possible to "get download link" **for files** using `megals -e`.
In the web app, "get download link" **for directories** is available in the exact same way as for files. Unfortunately, I did not find any way to get this information from the command line with megatools.
Why is that so?

Thanks in advance

**Comment by megous** [comment]
Because that requires implementation of file sharing APIs and those were never implemented in megatools.

**Comment by megous** [comment]
In particular, exported folders are just special case of shared folders with the encryption key put in url instead of being shared via public key cryptography over mega.nz API with other users.

**Comment by wlerin** [comment]
It would be [this method](https://github.com/meganz/sdk/blob/e8e66e9f030febfb35c9e4dd503d69091e28fc04/src/megaclient.cpp#L6817) in the MEGA SDK, yes?

**Comment by megous** [comment]
More like this:

https://github.com/megous/megatools/blob/dev/js/tools/share.js
