### ISSUE TITLE
Server returned error ETOOMANY

### ISSUE THREAD

**Issue by shubhank008** [megous/megatools#259]
Getting the following error and not able to use any of the Megatools commands anymore  
`ERROR: Can't login to mega.nz: API call 'us' failed: Server returned error ETOOMANY`

**Comment by megous** [comment]
You're being limited by mega.nz. Please contact their support for the details or wait a bit for the limit to expire.

**Comment by megous** [comment]
You may be doing too many login attempts, or created too many users. 'us' is an API call used during login.

**Comment by shubhank008** [comment]
Any reason why this might be happened ? I am using the following commands (via php) in order:  

megals (reload filesystem)
megamkdir (new dir)
megals (reload filesystem otherwise megaput doesnt see that dir)
megaput file1  
megals (reload filesytem so can see uploaded file)
megals (read above created directory for files to get their links)  

If I don't do megals in between, the next command does not see updated filesystem/directory, etc.

**Comment by megous** [comment]
Each megals --reload counts as repeated login.

**Comment by shubhank008** [comment]
@megous so only --reload counts as repeated login ? Is there anyway to update filesystem otherway then ?
Without updating it, I cannot execute/use commands in order and after each-another as the next command does not see results of previous command in file system

**Comment by megous** [comment]
I just tested megamkdir /Root/something && megals and it show the dir. Are you sure it's not working?

**Comment by megous** [comment]
You can't run megatools commands in parallel, that would break the cache (including multiple concurrent invocations of your entire script), otherwise it should work.

**Comment by shubhank008** [comment]
@megous yes I am, if it makes any difference I am using PHP and shell_exec to run my root commands (they are still one after another and not parallel) and at time of writing my backup script I did check it through and it was not reading created folder from my mega's filesystem  

same was with newly uploaded files too if I tried to get their links (by listing all files in directory) without megals --reload

**Comment by megous** [comment]
Sorry, I checked the code and --reload doesn't cause repeated login.

You may need to increase cache timeout in the megarc though, because megatools would try to login again after cache expires. By default that's only 10 minutes.

**Comment by shubhank008** [comment]
Does increasing cache affect multiple accounts in anyway ? I am passing my user/password as parameters in command directly since my script decides which account to use (we are using 4-5 accounts)  

PS: Sorry for bugging so much, what affect does setting cache lower or higher does on files/filesystem and accounts and how does it interact with --reload ?

**Comment by megous** [comment]
You may also try --debug=cache to see if cache is updated between megamkdir calls.

You can diff the output using diff command.

**Comment by megous** [comment]
Megatools writes fs and login data into cache file. Cache value determines the validity interval in minutes for this entire cache file.

You can have a single .megarc file and use command line options to specify account.
