### ISSUE TITLE
Download specific subdirectory of a "public"/shared folder?

### ISSUE THREAD

**Issue by kelvinss** [megous/megatools#260]
If I have a shared folder link (like `https://mega.nz/#F!HIlFDajT!HLiVvQQkSe1d0ogxZuaOJg`), I can download it running:
```
megadl https://mega.nz/#F!HIlFDajT!HLiVvQQkSe1d0ogxZuaOJg
```

But how do I download a specific folder inside the shared folder?

Something like this:

```
megadl https://mega.nz/#F!HIlFDajT!HLiVvQQkSe1d0ogxZuaOJg /subdirectory -p /my/local/folder
```

**Comment by kelvinss** [comment]
Ops, I guess this is duplicate of #254

**Comment by denyeo** [comment]
This doesn't seem possible yet, from what I see? @christarazi's patch doesn't seem to work on the Windows binary (version: megatools-1.9.98-win64). Can someone confirm?

**Comment by christarazi** [comment]
@denyeo The OS shouldn't matter here...maybe @megous has an explanation.

**Comment by megous** [comment]
It is in unreleased version of megatools. 1.9.99 will contain the patch.

**Comment by denyeo** [comment]
I see, thank you both for the confirmation! @megous @christarazi
