### ISSUE TITLE
megarm with asterisk (star)

### ISSUE THREAD

**Issue by DaeMonSx** [megous/megatools#261]
Working on bash script which will create the file with start and end time, so i can see on the mega server when was the start for update and the end.

can someone suggest me how can it be done with megarm?
i need to delete those files which ends with /tmp/last_update_on_${HOST}_*

thanks
...
UPDATED="/tmp/last_update_on_${HOST}_"  
TIME_END=$(date +"%Y-%m-%d_%H.%M")                                                                                                                              
echo "0" > ${UPDATED}__${TIME_START}__${TIME_END}.txt                                                                                                           
#megarm $ID ${UPDATED}__"*".txt                                                                
megaput $ID ${UPDATED}__${TIME_START}__${TIME_END}.txt  --path /Root                                                                                            
#rm $UPDATED   
..

**Comment by megous** [comment]
Try:

    megals /Root/some/dir | grep '/last_update_on_'

if this shows only the names of files you want to remove, then do:

    megarm $(megals /Root/some/dir | grep '/last_update_on_')

**Comment by DaeMonSx** [comment]
it works, thanks

TIME_END=$(date +"%Y-%m-%d_%H.%M")
echo "0" > ${UPDATED_L}__${TIME_START}__${TIME_END}.txt
#megals $ID /Root/ | grep $UPDATED_R #debug
megals $ID /Root/ | grep $UPDATED_R | xargs -r megarm $ID
megaput $ID ${UPDATED_L}__${TIME_START}__${TIME_END}.txt  --path /Root
