### ISSUE TITLE
Compiling errors with OpenSSL 1.1

### ISSUE THREAD

**Issue by artifexor** [megous/megatools#263]
I have errors relating to RSA structure member access when compiling with OpenSSL 1.1. As far as I understand there are some API changes within OpenSSL 1.1. Is there any plan on supporting OpenSSL 1.1? Or is there any idea how to compile with OpenSSL 1.1?

**Comment by megous** [comment]
What version of megatools do you try to compile?

**Comment by artifexor** [comment]
Sorry not mentioned. I am using latest master from github on a debian sid machine.

**Comment by megous** [comment]
Well, it should work. The port was done for the latest release.

Please specify what errors you're seeing exactly and the exact version of OpenSSL.

**Comment by megous** [comment]
I tried compiling on sid and it just throws some warnings. other than that the build succeeds.

**Comment by artifexor** [comment]
The requested informations:

The system:
```
# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.0 (stretch)
Release:	9.0
Codename:	stretch

# uname -a
Linux debiandev 4.9.0-1-amd64 #1 SMP Debian 4.9.6-3 (2017-01-28) x86_64 GNU/Linux
```

Installed ssl libraries. The 1.0 libssl installed because some packages still depend on that. libssl1.0-dev cannot installed because the default libssl-dev installed.
```
# dpkg-query -l libssl*
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                        Version            Architecture       Description
+++-===========================-==================-==================-===========================================================
ii  libssl-dev:amd64            1.1.0d-2           amd64              Secure Sockets Layer toolkit - development files
ii  libssl-doc                  1.1.0d-2           all                Secure Sockets Layer toolkit - development documentation
un  libssl1.0-dev               <none>             <none>             (no description available)
ii  libssl1.0.2:amd64           1.0.2k-1           amd64              Secure Sockets Layer toolkit - shared libraries
ii  libssl1.1:amd64             1.1.0d-2           amd64              Secure Sockets Layer toolkit - shared libraries
```
Using the following configure line (CC is clang or gcc):
```
CC=clang \
CFLAGS='-pipe -O2 -Wall -Wextra -march=native' \
LDFLAGS='-s' \
./configure --disable-docs --enable-warnings
```
The error message when compile using gcc:
```
~/src/megatools$ make
  CC       lib/sjson.gen.o
  CC       lib/http.o
  CC       lib/mega.o
lib/mega.c: In function ‘rsa_key_gen’:
lib/mega.c:820:20: error: dereferencing pointer to incomplete type ‘RSA {aka struct rsa_st}’
   k->p = BN_dup(key->q);
                    ^~
lib/mega.c: In function ‘update_pathmap_prune’:
lib/mega.c:1542:3: warning: multi-line comment [-Wcomment]
   //           /      \
   ^
lib/mega.c:1545:3: warning: multi-line comment [-Wcomment]
   //        /   \        \
   ^
Makefile:657: recipe for target 'lib/mega.o' failed
make[1]: *** [lib/mega.o] Error 1
Makefile:460: recipe for target 'all' failed
make: *** [all] Error 2
```
Compiling with clang:
```
$ make
  CC       lib/sjson.gen.o
  CC       lib/http.o
  CC       lib/mega.o
lib/mega.c:820:20: error: incomplete definition of type 'struct rsa_st'
  k->p = BN_dup(key->q);
                ~~~^
/usr/include/openssl/ossl_typ.h:110:16: note: forward declaration of 'struct rsa_st'
typedef struct rsa_st RSA;
               ^
lib/mega.c:821:20: error: incomplete definition of type 'struct rsa_st'
  k->q = BN_dup(key->p);
                ~~~^
/usr/include/openssl/ossl_typ.h:110:16: note: forward declaration of 'struct rsa_st'
typedef struct rsa_st RSA;
               ^
lib/mega.c:822:20: error: incomplete definition of type 'struct rsa_st'
  k->d = BN_dup(key->d);
                ~~~^
/usr/include/openssl/ossl_typ.h:110:16: note: forward declaration of 'struct rsa_st'
typedef struct rsa_st RSA;
               ^
lib/mega.c:823:20: error: incomplete definition of type 'struct rsa_st'
  k->u = BN_dup(key->iqmp);
                ~~~^
/usr/include/openssl/ossl_typ.h:110:16: note: forward declaration of 'struct rsa_st'
typedef struct rsa_st RSA;
               ^
lib/mega.c:826:20: error: incomplete definition of type 'struct rsa_st'
  k->m = BN_dup(key->n);
                ~~~^
/usr/include/openssl/ossl_typ.h:110:16: note: forward declaration of 'struct rsa_st'
typedef struct rsa_st RSA;
               ^
lib/mega.c:827:20: error: incomplete definition of type 'struct rsa_st'
  k->e = BN_dup(key->e);
                ~~~^
/usr/include/openssl/ossl_typ.h:110:16: note: forward declaration of 'struct rsa_st'
typedef struct rsa_st RSA;
               ^
6 errors generated.
Makefile:657: recipe for target 'lib/mega.o' failed
make[1]: *** [lib/mega.o] Error 1
Makefile:460: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by megous** [comment]
Looks like OPENSSL_VERSION_NUMBER from the header files on your system is indicating it is 1.0.0, while the rest of the code is 1.1.0. Can you please grep for  OPENSSL_VERSION_NUMBER in /usr/include to see what the value is?

**Comment by christarazi** [comment]
I can also confirm that megatools still compiles (with warnings as megous
mentioned), on fresh install of Debian sid with `openssl-1.1.0d` installed.
Running grep on `/usr/include` reveals my openssl version to be
`0x1010004fL`, which translates to `openssl-1.1.0d`.

**Comment by christarazi** [comment]
I can also confirm that megatools still compiles (with warnings as megous mentioned), on fresh install of Debian sid with `openssl-1.1.0d` installed. Running grep on `/usr/include` reveals my openssl version to be `0x1010004fL`, which translates to `openssl-1.1.0d`.

**Comment by artifexor** [comment]
@megous @christarazi thank you both. i will try tomorrow and report the results as here i have jessie which is using openssl 1.0 and megatools works flawless.

**Comment by artifexor** [comment]
@megous here is the result:
```
$ egrep -r 'define.*OPENSSL_VERSION_NUMBER' /usr/include
/usr/include/gnutls/openssl.h:#define OPENSSL_VERSION_NUMBER (0x0090604F)
/usr/include/gnutls/openssl.h:#define SSLEAY_VERSION_NUMBER OPENSSL_VERSION_NUMBER
/usr/include/openssl/opensslv.h:# define OPENSSL_VERSION_NUMBER  0x1010004fL
/usr/include/openssl/crypto.h:#  define SSLEAY_VERSION_NUMBER   OPENSSL_VERSION_NUMBER
```
strange. seems like two openssl.h exist.
```
$ dpkg -S /usr/include/gnutls/openssl.h
libgnutls28-dev:amd64: /usr/include/gnutls/openssl.h
$ dpkg -S /usr/include/openssl/opensslv.h
libssl-dev:amd64: /usr/include/openssl/opensslv.h
# apt-rdepends -r --state-follow=Installed --state-show=Installed libgnutls28-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libgnutls28-dev
  Reverse Depends: librtmp-dev (2.4+20151223.gitfa8646d.1-1)
librtmp-dev
```
there is an active dependency for libgnutls28-dev. libcurl4-openssl-dev suggests librtmp-dev so . at the moment the conclusion is that libgnutls28-dev include path has a higher priority than libssl-dev.

after removing libgnutls28-dev the status is the following:
```
$ egrep -r 'define.*SSL_VERSION_NUMBER' /usr/include
/usr/include/boost/asio/ssl/impl/context.ipp:#if (OPENSSL_VERSION_NUMBER >= 0x10002000L) && !defined(LIBRESSL_VERSION_NUMBER)
/usr/include/mbedtls/compat-1.3.h:#define POLARSSL_VERSION_NUMBER MBEDTLS_VERSION_NUMBER
/usr/include/openssl/opensslv.h:# define OPENSSL_VERSION_NUMBER  0x1010004fL
/usr/include/openssl/crypto.h:#  define SSLEAY_VERSION_NUMBER   OPENSSL_VERSION_NUMBER
$ make
  CC       lib/mega.o
lib/mega.c: In function ‘rsa_key_gen’:
lib/mega.c:820:20: error: dereferencing pointer to incomplete type ‘RSA {aka struct rsa_st}’
   k->p = BN_dup(key->q);
                    ^~
lib/mega.c: In function ‘update_pathmap_prune’:
lib/mega.c:1542:3: warning: multi-line comment [-Wcomment]
   //           /      \
   ^
lib/mega.c:1545:3: warning: multi-line comment [-Wcomment]
   //        /   \        \
   ^
Makefile:657: recipe for target 'lib/mega.o' failed
make[1]: *** [lib/mega.o] Error 1
Makefile:460: recipe for target 'all' failed
make: *** [all] Error 2
```
only one openssl header but the compiler error still exists. as you check for libressl i correct the egrep expression to see that version string.

**Comment by megous** [comment]
Did you re-run the configure after removing gnutls-dev? Nevertheless now it looks even more nonsensical. :)

**Comment by artifexor** [comment]
@megous yes, ran configure again each time i change something. once i rerun autogen.sh again to create all files from scratch. same result. if i look the source and know the information i have shared it seems that compiler goes into a wrong branch (#else instead of #if). i do not have any idea why.

ah. i find it. compared with my egrep results and it seems there is too much zeroes in ssl version when compare. i need to use 0x10100000L instead of 0x101000000L in mega.c line 807 here. still gives some warning but create binaries.

**Comment by artifexor** [comment]
according to this (MNNFFPPS: major minor fix patch status)
https://github.com/openssl/openssl/blob/master/include/openssl/opensslv.h#L19
the comparing is wrong and should be 0x10100000L here
https://github.com/megous/megatools/blob/master/lib/mega.c#L807

**Comment by artifexor** [comment]
@christarazi thank you and will try on monday. here i am running jessie which is using openssl 1.0 and can compile fine by default.

**Comment by christarazi** [comment]
Hmm...there does seem to be an extra zero in `lib/mega.c`. @megous was this intended?

**Comment by megous** [comment]
It was not, probably a typo. It was introduced here: 3111b1b11330feb8b81d163bce67c5579a289796

Thank you both for figuring out the issues with the bad condition and warnings.
