### ISSUE TITLE
ERROR: Can't login to mega.nz: API call 'us' failed: HTTP POST failed: CURL error: SSL connect error

### ISSUE THREAD

**Issue by ifantasy** [megous/megatools#268]
When I typed a command such as megals, megadf, etc, the same error was presented as follows:

```
ERROR: Can't login to mega.nz: API call 'us' failed: HTTP POST failed: CURL error: SSL connect error.
```

How to solve the problem? My OS is Centos 5.9. The username and password were both correct.

**Comment by megous** [comment]
You may try googling "CURL error: SSL connect error.". This is not specific to megatools.

It might be a lot of causes, from packaging issues, to the server/firewall blocking your connection.
