### ISSUE TITLE
megadl enters infinite loop if ethernet cable is disconnected

### ISSUE THREAD

**Issue by gradha** [megous/megatools#271]
Running 1.9.98 on OSX 10.11.6 El Capitan and removing the ethernet cable while a download is in progress makes the download display 0 bytes downloaded in an infinite loop. Reconnecting the cable doesn't help either, the process is stuck in a loop until Ctrl+C is pressed. Expected behaviour would be to abort the connection and remove the partial file as it seems to happen with downloads where the server closes/interrupts the connection.

**Comment by megous** [comment]
libcurl which megatools uses for HTTP connections allows to set: 

https://curl.haxx.se/libcurl/c/CURLOPT_LOW_SPEED_TIME.html

That should help. Or perhaps setting this option might be a better option in this case:

https://curl.haxx.se/libcurl/c/CURLOPT_TCP_KEEPALIVE.html

The issue is that TCP connection will never time out if it is only receiving data (which is the case of megadl).

**Comment by nyuszika7h** [comment]
This patch causes compilation to fail on older versions of libcurl.

```
  CC       lib/http.o
In file included from /usr/local/include/curl/curl.h:1982:0,
                 from lib/http.c:22:
lib/http.c: In function ‘http_new’:
lib/http.c:71:29: error: ‘CURLOPT_TCP_KEEPALIVE’ undeclared (first use in this function)
   curl_easy_setopt(h->curl, CURLOPT_TCP_KEEPALIVE, 1L);
                             ^
lib/http.c:71:29: note: each undeclared identifier is reported only once for each function it appears in
lib/http.c:72:29: error: ‘CURLOPT_TCP_KEEPIDLE’ undeclared (first use in this function)
   curl_easy_setopt(h->curl, CURLOPT_TCP_KEEPIDLE, 120L);
                             ^
lib/http.c:73:29: error: ‘CURLOPT_TCP_KEEPINTVL’ undeclared (first use in this function)
   curl_easy_setopt(h->curl, CURLOPT_TCP_KEEPINTVL, 60L);
                             ^
Makefile:648: recipe for target 'lib/http.o' failed
make[1]: *** [lib/http.o] Error 1
Makefile:450: recipe for target 'all' failed
make: *** [all] Error 2
```

curl version:

```
curl 7.38.0 (x86_64-pc-linux-gnu) libcurl/7.38.0 OpenSSL/1.0.1t zlib/1.2.8 libidn/1.29 libssh2/1.4.3 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API SPNEGO NTLM NTLM_WB SSL libz TLS-SRP
```

**Comment by megous** [comment]
Please make a patch. I don't have old debian around to test.

**Comment by nyuszika7h** [comment]
According to curl documentation, these options are supported since curl 7.25, so I assume it was disabled at compile time for some reason, though I can't find any option to disable keepalive support in the docs. A simple `#ifdef CURLOPT_TCP_KEEPALIVE` would probably do.
