### ISSUE TITLE
Ran updates, not I get segfaults no matter what

### ISSUE THREAD

**Issue by colemickens** [megous/megatools#273]
```
$ megadl 'https://mega.nz/#!redacted
[1]    27470 segmentation fault (core dumped)  megadl
```

Every single time. On single files, on directories, etc.

**Comment by colemickens** [comment]
I'm on Arch Linux with testing repositories enabled.

**Comment by colemickens** [comment]
```
git clone git@github.com:megous/megatools
cd megatools
./autogen.sh
./configure
make
./megadl ...
```

everything works fine. No idea what's going on.

**Comment by christarazi** [comment]
I just cloned the latest and followed your steps, but I was not able to reproduce. My guess is that you don't have the all the dependencies, or since you mentioned testing repos in Arch, you may have an incompatible version of a dependency somewhere.

**Comment by megous** [comment]
I would guess that some underlying library in testing is breaking its ABI (somewhat unlikely) in a subtle way and is only source compatible. Or perhaps fs/ram corruption.

**Comment by jomp16** [comment]
I think the only package that required a fully recompile of entire package that depends on it was OpenSSL (from 1.0.2.k to 1.1.0.e). I have rebuilt it and it works now.

You just need to bump the pkg rel.
