### ISSUE TITLE
megaput 64bit in Windows - max speed of around ~300KB/s?

### ISSUE THREAD

**Issue by nexxai** [megous/megatools#276]
I realize this sounds extremely unlikely, but I've tried using megaput on two different computers on two *completely* different internet connections (different ISPs, different medium, etc.) and no matter what, I cannot get the upload to go higher than 320KB/s.  Am I going crazy or is anyone else having the same issue?

**Comment by megous** [comment]
For me upload maxes out my connection at 10Mbps. Mega.nz has some options to limit upload/download speed. Do you have those enabled?

**Comment by nexxai** [comment]
Just checked, and no, they're all disabled.  And to confirm - I uploaded the same file from a Linux box here using megatools and it maxed out the pipe.

**Comment by megous** [comment]
I guess nobody else on windows has this issue, or cared to comment. I'll close this issue for now.
