### ISSUE TITLE
MegaFS: Will it be continued?

### ISSUE THREAD

**Issue by B1naryKill3r** [megous/megatools#277]
Hello megous!

I've seen that some time ago you completely remove megafs from source. Will it be continued?
I really need nice tool to "emulate" my folders in MEGA on my hard drives.

Unfortunately MEGAFuse (http://github.com/matteoserva/MegaFuse) doesn't work on arm devices.

Cheers!
Thanks anyway...

**Comment by megous** [comment]
I have no plans to continue it.

**Comment by megous** [comment]
I see no obvious reason why MegaFS should not work on ARM. It seems unmaintained, though.
