### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by falzard** [megous/megatools#278]
If I try to connect with megadf -u username:

```
Good, signing in...
ERROR: Can't login to mega.nz: API call 'us' failed: Server returned error ENOENT
```

If I try to connect with the .megarc file, it returns this:
`ERROR: Can't login to mega.nz: API call 'us' failed: Server returned error EARGS`

It's not related to the firewall, right?

**Comment by megous** [comment]
ENOENT is invalid username or password.

EARGS looks like invalid arguments to an API call. I have not seen that one yet.

**Comment by falzard** [comment]
You are right. I registered through megareg. I verified the link. I received the email. And I can't connect even through my browser. And now they tell me I tried to connect myself too many times...

I don't know if they messed up my password or if it's my fault.

**Comment by falzard** [comment]
I resetted my account, thank you for the ultra fast answer.

**Comment by megous** [comment]
In general you need to be careful with the shell quoting. Some characters may be interpreted by the shell, and not passed to the megatools.

That said, I haven't tested the registration workflow in a long time, so it might be that mega.nz chnaged the API and registration no longer works.
