### ISSUE TITLE
Move files and upload a remote file (not locally hosted)

### ISSUE THREAD

**Issue by falzard** [megous/megatools#280]
How to move a file? there is no megamv so I don't know how to do, it's annoying :(
_When I try to upload a file to a directory, it always end up in /Root/, it doesn't go into subdirectories i created so I need to move them but it's not possible. It's also impossible to reupload to the right directory because it says "file already exists" (EDIT: ok I found the "--path" option but still the questions remain)_

And how to upload a file which is hosted on another website? Do I need to download it first?

**Comment by megous** [comment]
> And how to upload a file which is hosted on another website? Do I need to download it first?

Yes.

> mv

You can use mega.nz website to do any non-ordinary file management. Megatools is mostly intended for automated use. There's mv implementation in the dev branch, I believe, but you'll not be able to do any file data operations with the dev branch version.

**Comment by falzard** [comment]
It's also useful to upload through your server and not screw up your home connection you know :P

**Comment by megous** [comment]
Nothing prevents you from doing that.

**Comment by falzard** [comment]
Yes but then you sometimes need to move a file from the command line, and it's not related to automating tasks.
