### ISSUE TITLE
limit speed of megadl 

### ISSUE THREAD

**Issue by gempir** [megous/megatools#282]
It would nice to limit the speed of megadl with a --speed-limit parameter. 
I thought at first this was supported, but I think the docs on the website are structered weird, making me think this is a feature.

If this is a feature nobody wants, is there a way to hack it in easily?

**Comment by megous** [comment]
See https://megatools.megous.com/man/megadl.html

You can use eg. megadl --speed-limit 1024 ..... to limit speed to 1MiB/s.

**Comment by gempir** [comment]
I just build the version of mega tools and this is not possible with megadl

**Comment by megous** [comment]
Sorry, the correct option is --limit-speed

**Comment by megous** [comment]
Fixed in https://github.com/megous/megatools/commit/b2750d22732eea11fc570514498ded933d2b5c05

**Comment by gempir** [comment]
Probably would make sense to add it here then https://github.com/megous/megatools/blob/master/docs/megadl.txt

**Comment by megous** [comment]
It is there via include::basic-options.txt[]
