### ISSUE TITLE
Any possibility for a GUI?

### ISSUE THREAD

**Issue by rayman3003** [megous/megatools#283]
Is there any possiblity to have a small & simple GUI for megatools?
It could make the work much easier for amateur users (like me).

PS> Im a GFX designer & can help for GUI if needed.

**Comment by megous** [comment]
Megatools internal implementation is not suited for making a GUI app out of it. You can perhaps create a GUI app, that would help with producing the right command line options for some specific use case and generating a .megarc file, but a simple guide on how to use megatools for beginners might be better.

**Comment by YashGulati** [comment]
maybe you can use MegaSync

**Comment by danlniel** [comment]
If you use MegaSync it would be same,
you still got restriction limit download,
I found this one
`https://github.com/jacquesCedric/Ananke`
But i dont know is this free from malware

**Comment by megous** [comment]
>  But i dont know is this free from malware

You can use brew, instead of the bundled megadl, perhaps, if you're afraid of malware.
