### ISSUE TITLE
Building from tar file requires me to build docs

### ISSUE THREAD

**Issue by mcarrilloco** [megous/megatools#284]
Hi,

I am trying to build the latest version `megatools-1.9.98` from the tar file available in `https://megatools.megous.com`. This version is asking me to install several dependencies to build the docs. In this machine I am unable to install anything, so I downloaded a previous version `1.9.97` which doesn't require such a thing. Is this a bug with the current tar file? Thanks, hope my info is useful.

**Comment by megous** [comment]
Please look at the configure options.

**Comment by mcarrilloco** [comment]
Got it. Yep, `./configure --enable-docs=no`. Sorry about that, I couldn't find a lot in the docs so I thought such option did not exists. Anyway, thanks!
