### ISSUE TITLE
Error 509 if you hit MEGA's 5GB download restriction

### ISSUE THREAD

**Issue by Cormak** [megous/megatools#286]
Not sure if this will ever work again but figured I'd start the issue about it. 

People are reporting that megatools and other downloaders are no longer able to bypass Mega's 5GB restriction.

**Comment by megous** [comment]
What's this restriction about? Single file or per account? Do you have a link to relevant discussion?

**Comment by WernerLi** [comment]
Here: https://www.reddit.com/r/megalinks/comments/6f0z7h/meta_megadownloader_and_megatools_are_no_longer/

**Comment by mariogamer2** [comment]
getting the same error here

**Comment by dbenoy** [comment]
Can this error be bypassed by purchasing an account? By that I mean, if you've paid for a legitimate download cap, does the megadl command connect to the server using your username/password to take advantage of your increased limit?

**Comment by megous** [comment]
Not at this moment. I'll try to get the feature into the next release.

**Comment by megous** [comment]
@dbenoy Now, megadl will optionally use your credentials, and should use the download cap of your account.

**Comment by mvegetto** [comment]
Thanks megous. I have done some testing. It worked on 1 file of 2 GB, after that I am receiving those 509 errors again. I have used megadl --username name --password password 'ddl'. The account plan I used is 'Pro Lite'.  I do see the authentication in the session history as active (Browser: Unknown). No issues when I download using a windows browser like Chrome.

**Comment by megous** [comment]
Thanks for testing, I guess I'll have to check if the browser client does something more than just issuing those same calls it does in unauthenticated mode with the authenticated session id and find the difference.

**Comment by megous** [comment]
There's extra {a:'qbq', s: file_size} call before the call to get a download link. I didn't find any docs for it.

**Comment by jumoog** [comment]
maybe "X-Forwarded-For" Header works?

**Comment by megous** [comment]
That should be set by a proxy server. I don't see it being set on mega.nz website requests in firefox.

**Comment by jumoog** [comment]
I mean "playing" proxy Server and change the IP Adress in X-Forwarded-For randomly

**Comment by nyuszika7h** [comment]
Yes, the point is some sites are dumb enough to blindly trust the X-Forwarded-For header and believe that's your real IP.

Could try `X-Forwarded-For: 1.2.3.4, 1.2.3.4, 1.2.3.4, 1.2.3.4` (the same IP 4 times) as well.

**Comment by megous** [comment]
Ah, I thought you meant it to slove the issue with non-working quota accounting when being logged in.

**Comment by megous** [comment]
You can try playing with this patch:

```patch
diff --git a/lib/http.c b/lib/http.c
index 4d11163..e17e6d6 100644
--- a/lib/http.c
+++ b/lib/http.c
@@ -78,6 +78,9 @@ http* http_new(void)
   http_set_referer(h, "https://mega.nz/");
   http_set_user_agent(h, "Megatools (" VERSION ")");
 
+  if (g_getenv("X_FORWARDED_FOR"))
+    http_set_header(h, "X-Forwarded-For", g_getenv("X_FORWARDED_FOR"));
+
   return h;
 }
 ```

You can set X_FORWARDED_FOR environment variable to add X-Forwarded-For header with the value of your choosing.

**Comment by nyuszika7h** [comment]
Nope, no luck with what I said either.

**Comment by JonasXPX** [comment]
I use `--proxy=` to solve it

**Comment by jumoog** [comment]
@JonasXPX but you use a real proxy?

**Comment by ahsis** [comment]
I get this even if I don't download files larger than 5GB, like for example this which is a lot of files adding up to 3 something GB.

https://mega.nz/#F!K4RmQITT!P8bFC9LFBO5-pI1PJjkYEA

**Comment by nyuszika7h** [comment]
@ahsis Are you using a public IP shared by other users? When you are not logged in, the 5 GB bandwidth quota is per IP. Also, it varies based on MEGA's load, but I think it's always been 5 GB lately.

**Comment by ahsis** [comment]
No, but my shitty isp might be doing some fuckery since I'm using their shitty router which automatically resets itselfs and enables other customers to connect to it even if protected by wpa2

**Comment by CGS-James-Lamberth** [comment]
Hey megous, I'm still having some problems with megatools 509 error. I tested by buying an account and signing in through the .megarc file but I still get the 509 error from "megadl". Tried testing with another account that is free and it seems as the download limit is independent of accounts. Tried using "megadl --username user --password pass link" as suggested above but was returned error "Unkown option --username". Anyone know how to fix it? Thank you.

**Comment by megous** [comment]
Hi, are you using the git version?

**Comment by megous** [comment]
This was solved by allowing megadl to use purchased account quotas.

**Comment by anirudhpulikonda** [comment]
Here's the Fix that I'm using to overcome this error: [Bypass Mega Download Limit](https://megadownloaderapp.com/mega-download-limit-transfer-quota/)

**Comment by tyeeman** [comment]
Megadownloader doesn't work anymore for me. Won't dl anything. Megatools works though!

**Comment by Qwerty-Space** [comment]
I get this too.  But megadl will just cancel it after a few tries, or move onto the next file.

Is there a way to keep trying until it works?
