### ISSUE TITLE
proxy support, is it working?

### ISSUE THREAD

**Issue by albaldi** [megous/megatools#287]
I tried to create an account using a proxy.

I test the proxy with:
`curl --url https://diagnostic.opendns.com/myip --connect-timeout 30 --proxy $PROXY`

then:
`megareg --proxy $PROXY --register --email your@email.com --name "Your Name" --password "Your Password"`
and then
`megareg --verify $STUFF --proxy $PROXY `

but once logged in the account [show](https://mega.nz/fm/account/history) it was created by my own ip, not the $PROXY

Am I missing something?
Is there a way to debug?

**Comment by megous** [comment]
It should be. What version of megatools and what OS are you using?

**Comment by megous** [comment]
Anyway, I have found the bug.

**Comment by megous** [comment]
Thanks for the report!

**Comment by albaldi** [comment]
you're welcome @megous 
There will be a new release with the fix? 
The other tools works fine with proxy?

thanks

**Comment by megous** [comment]
Yes, and yes.

**Comment by albaldi** [comment]
is there a ETA, or a way to build from git?

**Comment by megous** [comment]
You can build from git. Just install the basic development dependencies, and the instead of ./configure tun ./autogen.sh. The rest is the same as in the documentation.
