### ISSUE TITLE
Can't build the dev branch

### ISSUE THREAD

**Issue by Alexsaphir** [megous/megatools#288]
Hi 
`i'm trying to buildthe dev branch but when i launch ./autogen.sh, I have this error : 
checking for NETTLE... no
configure: error: Package requirements (nettle >= 2.7 hogweed >= 2.7) were not met:

Package # was not found in the pkg-config search path.
Perhaps you should add the directory containing `#.pc'
to the PKG_CONFIG_PATH environment variable
Package '#', required by 'hogweed', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.
`
Thanks

**Comment by megous** [comment]
Dev branch has different build requirements than the stable branch. You need to install mentioned packages.

**Comment by Alexsaphir** [comment]
I try with sudo apt install nettle and I don't find for hogweed
I also try with build from source nettle

**Comment by megous** [comment]
The names will depend on your distribution. It may be something like libnettle-dev libhogweed-dev. On Arch Linux, which I use, it's simply nettle and nothing else, because it doesn't split upstream packages into multiple distribution packages.

**Comment by megous** [comment]
hogweed is part of nettle

**Comment by jdknox** [comment]
On Ubuntu 17.04 you need to run the following (at least):
`sudo apt install libgnutls28-dev nettle-dev re2c`

I haven't tested other versions of Ubuntu.  Also, I needed re2c or else `make` would fail.  YMMV

**Comment by Alexsaphir** [comment]
Your my hero
