### ISSUE TITLE
Mega tools doesn't open on Win 7

### ISSUE THREAD

**Issue by CliveBarker** [megous/megatools#289]
Hi

I downloaded megatools-1.9.98-win64.zip for my Win 7 64, after extracting, and trying to run any of the exes, it just opens the command line for a second and it closes.

What am I doing wrong?

**Comment by christarazi** [comment]
Run it from the command line, not by double clicking.

**Comment by megous** [comment]
There is a bat script in the zip file that you can use to open the command line with the correct environment variables set. You can also use it for inspiration for your own scripting.

After opening the command line you can run the tools as per the documentation in the html files that are also part of the distribution zip file.

**Comment by CliveBarker** [comment]
Thanks, I understand now, sorry for wasting your time!

2017-06-16 20:24 GMT-05:00 megous <notifications@github.com>:
