### ISSUE TITLE
Create remote folder if it doesn't exist when using megacopy

### ISSUE THREAD

**Issue by combucha** [megous/megatools#292]
Hi, maybe I do something wrong, but why megacopy is not make remote dir itself (clone dir name from --local path)?
Seems I have to involve megamkdir always before using megacopy.
Are there any negatives of injecting this functionality into megacopy module?

**Comment by mcarrilloco** [comment]
Interested in the answer to this one. I currently have a wrapper script that runs both commands among other things, so it's only a cumbersome issue. But it seems natural that a `cp` like command should create the needed directories for such action. `megacopy` does create subdirectories, but not the main one if it doesn't exists.

**Comment by megous** [comment]
Megatools tries to not do much unless you explicitly ask it to. So yes, you need to create directory before uploading stuff into it.

Though in the case of megacopy, you may be right that megatools should perhaps create it (like for example cp -r), but there's no mv operation and users might want different names for local and remote dirs.

Also in this case it's already too late to do the change. It would need to be done in backward compatible way, which would mean a new command or extra option like --mkdir. Anyway it's perfectly fine to do this separately, and it has some benefits too, like a finer grained control over error handling in your scripts, between mkdir step and copy step.

**Comment by megous** [comment]
I guess it's best leaving this explicit, rather than dealing with confusion of where the dir would be created.
