### ISSUE TITLE
Remove download link without removing file.

### ISSUE THREAD

**Issue by Pratted** [megous/megatools#293]
I use the command  `$ megals -e /Root/myfile.txt` to create and get a download link for a specific file. 

However, sometimes I want to remove the public download link without removing the file all together. Is there functionality to remove a public download link without removing the file?

**Comment by megous** [comment]
This is implemented in the dev branch, I believe.

  megatools export --cancel /some/path

**Comment by megous** [comment]
See: https://github.com/megous/megatools/blob/dev/js/tools/export.js
