### ISSUE TITLE
Still in progress?

### ISSUE THREAD

**Issue by petrk94** [megous/megatools#294]
Hello @megous 
I would like to know whether the project is still in development, due megatools 2.0 should be available 2 years ago, regarding github.

My other question is, I can not get the progressbar in the cmd while uploading a file with megaput.exe
How to solve that?

Thanks

**Comment by megous** [comment]
There's no progress bar, only progress information displayed numerically.

You can see project history and progress in git and on https://megatools.megous.com/ in the news section or the NEWS file.

megatools 2.0 is on hold ATM, only stable version of megatools is being maintained.

**Comment by petrk94** [comment]
@megous 

> megatools 2.0 is on hold ATM

what you mean with it?

**Comment by megous** [comment]
It is not being actively developed. There's some unpublished work on making data transfer work (which is the only major missing functionality in 2.0), but I'm not working on that branch ATM, nor plan to in the short term. I'll be focusing on the stable branch.
