### ISSUE TITLE
Can't authenticate with `megadl`

### ISSUE THREAD

**Issue by colemickens** [megous/megatools#295]
`megadl` doesn't seem to do any of the auth steps. How can users use megatools to download a directory with an authenticated user?

Short of that, how does one workaround this issue? Can I get megadl to at least emit the individual links and then I can use `megaget`?

**Comment by megous** [comment]
Compare: https://megatools.megous.com/man/megaget.html
and: https://megatools.megous.com/man/megadl.html
and: https://megatools.megous.com/man/megacopy.html

**Comment by megous** [comment]
To export files use megals -e. Also see its manpage.

**Comment by colemickens** [comment]
Hm, I think I had missed that megacopy is similarly powerful/flexible as megadl, but with my own account. I got it now.

Thanks for the help and the very useful tool.

**Comment by colemickens** [comment]
@megous So how do I download files that are not in my own account with credentials? I can't seem to tell if it's possible or not...

**Comment by colemickens** [comment]
Heh, looks like my answer is here: https://github.com/megous/megatools/commit/087f1fcbcb84def710068db03f984102679b93d8

I'd tried to author a patch that looks very similar but never got it to work. I'll give it a shot.

**Comment by colemickens** [comment]
This still doesn't work for me:

```
~/c/m/megatools  master  $ git rev-parse --verify HEAD

46215802dd88a0274be93e4daf6db210c24e051d
```

```
~/c/m/megatools  master  $ cat ~/.megarc

[Login]
Username = johndough@<domain>.com
Password = <REDACTED>
```

```
~/c/m/megatools  master  $ megadl 'https://mega.nz/#F!xxxxxxxx!yyyyyyyyxxxxxxxxx'

F /home/cole/code/megous/megatools/FILE.mkv
ERROR: Download failed for FILE.mkv: Data download failed: Server returned 509
```

**Comment by colemickens** [comment]
Nevermind. Between testing an old build this morning and pulling `master` and testing again, my account had expired.

This is working as expected. Thanks.

**Comment by megous** [comment]
Good to know. Thanks.

**Comment by amper5and** [comment]
@colemickens I tried `megadl` with `-u` and `-p` options on 1.9.98-win32 and it didn't recognize those options. How are you getting this to work? Only with a .megarc file?

**Comment by megous** [comment]
Hi, this change is only in git, at the moment.

**Comment by megous** [comment]
Hi, this change is only in git, at the moment. I understand that building windows binaries is complicated, so I've uploaded the current git versions of windows binaries to: https://megatools.megous.com/builds/

**Comment by amper5and** [comment]
> I understand that building windows binaries is complicated, so I've uploaded the current git versions of windows binaries to: https://megatools.megous.com/builds/

@megous I really appreciate this, because I knew I would be waiting for 1.9.99 before being able to use this feature on Windows. I was just able to download >5 GB with my PRO account. This is really great. Thank you.

btw, I used 64 bit version, and Bitdefender didn't complain à la #302, so that's a plus

**Comment by megous** [comment]
Excellent. :)
