### ISSUE TITLE
Can't login to mega.nz

### ISSUE THREAD

**Issue by combucha** [megous/megatools#296]
Can't do anything since today/yesterday.
ERROR: Can't login to mega.nz: API call 'us' failed: HTTP POST failed: CURL error: SSL connect error
Is it temporary server side issue or something has been changed permanently?

**Comment by combucha** [comment]
Ok. working now.

**Comment by megous** [comment]
Yes, these are typically temporary errors with mega.nz servers.

**Comment by Riz-waan** [comment]
What command do you run to login into your previously created mega.nz account?

**Comment by megous** [comment]
All commands, check out

    man megarc

**Comment by Riz-waan** [comment]
Thank you I figured out to write a config file.
