### ISSUE TITLE
REnew: Remote file not found error #200

### ISSUE THREAD

**Issue by smx06** [megous/megatools#298]
I have the same "megaget" error "Remote file not found"
The answer to use "megadl" instead of "megaget" is not suitable cause megadl has not --username --password options.. This is esp. actual today when megadl can't download any file larger than 4-5Gb because of quotas .. 
So the only way is to use to use megaget with altered account (which has no 5Gb limit)

**Comment by megous** [comment]
Megaget is only for files on your account, or on accounts that shared files with you. (not via an export mechanism, but directly)

**Comment by smx06** [comment]
Ok. Thanks for answer. But anyway it could be very useful to add --username --password to "megadl" then, to utilize own account quotas (1Tb+) cause current "megadl"  is useless for files >5Gb

ThankYou

**Comment by megous** [comment]
Ah, I guess I understand what you mean now. When you're logged in, you can use the same API to download exported files without public traffic limits.

It should be possible to optionally log in in megadl to get over the public limits.

**Comment by smx06** [comment]
Yes, exactly

**Comment by megous** [comment]
Done.

**Comment by Stealthii** [comment]
I was additionally working on this on my own fork, but had yet to add optional auth support (mine was forced).

I've tested your upstream change and can confirm this works as expected, many thanks!
