### ISSUE TITLE
Overwrite / resume support

### ISSUE THREAD

**Issue by nyuszika7h** [megous/megatools#300]
When downloading a file that already exists locally, there should be an option to overwrite or resume the download instead of just erroring. Resume support would be especially nice to resume downloads after hitting the free bandwidth cap and changing IP (#286). Or simply if your connection gets interrupted and you don't want to redownload the whole thing again, obviously.

**Comment by nyuszika7h** [comment]
Sorry, duplicate of #252.

**Comment by megous** [comment]
No problem. Hopefully I'll find the time to finish the review of and merge that one in the next stable release.
