### ISSUE TITLE
Bitdefender 2017 Antivirus thinks megatools-1.9.98-win64 has a trojan

### ISSUE THREAD

**Issue by amper5and** [megous/megatools#302]
I downloaded megatools-1.9.98-win64.zip at https://megatools.megous.com/builds/megatools-1.9.98-win64.zip. 

Unzipped on my Windows 10 64-bit machine and Bitdefender 2017 immediately gave an `infected file detected` notification. The full output from Bitdefender is:

```
Bitdefender has detected an infected item in
c:\users\...\megatools-1.9.98-win64\libglib-2.0-0.dll.
Virus name: Trojan.Generic.20624498.

```

where `...` replaces part of the path to the folder.

Is this anything to truly be concerned about or just a false positive?

edit: I tried multiple times, and Bitdefender kept deleting libglib-2.0-0.dll. I tried copying the libglib-2.0-0.dll file from megatools 1.9.97 but got an error when running. Eventually, I downloaded the 32-bit version, unzipped, and no problems! Runs fine. Don't know what's wrong the 64-bit version.

**Comment by megous** [comment]
Hi, you can verify that the zip file is unmodified (from the time I built it) using the gpg signature provided along with it (the corresponding .asc file).

My key's fingerprint is:

pub   rsa4096 2016-05-23 [SC]
      9AB1 38B2 0691 621C D4CF  9202 6E64 26C6 77CF EFF1

You can get the ley from various places, for example from:

https://megous.com/pgp (it's the one on the top)

All the binaries in the zip file are built by me from the source code downloaded from the official sources (GNOME web servers in this case). Also, 32 and 64bit versions are built from the identical code, so it is unlikely that one would have malware and other would not.

So I would guess, unless the zip file got modified on the way to you, it's a false alarm.

**Comment by amper5and** [comment]
I confirmed the signature of the file. 

Now I know I got the zip file that you intended for me. However, I'm still not sure what to do with libglib-2.0-0.dll file with the supposed trojan. 

Building the project on my own machine is more than I want to get into. But no matter, I'll just use the 32-bit version for now.

**Comment by megous** [comment]
Trojan.Generic is probably not a known trojan, it just identifies a program that uses system/library calls/instructions in whatever way AV product deems unworthy of a normal program. From my POV it's certainly a false positive now that you verified the signature.

Given that the AV program doesn't explain what it actually doesn't like, all you can do is send the dll and a error message to your AV program vendor to further investigate and fix their heuristics.

**Comment by amper5and** [comment]
I agree. I couldn't find anything online about glib being infected.

> Trojan.Generic is probably not a known trojan, it just identifies a program that uses system/library calls/instructions in whatever way AV product deems unworthy of a normal program.

I agree that this is probably a one-off thing. It's just weird that the 32-bit version doesn't raise any flags. Presumably both versions would use the same system calls and everything else. 

Anyway, I don't see what else could be done with this issue, other than recompiling to see if anything changes, so I'm closing it. Thanks for your comments.

**Comment by megous** [comment]
I'll be doing a new release soon, and with that I'll update the windows dependencies as I always do. Perhaps it will go away after that. Newer gcc, newer glib2. Who knows...

**Comment by amper5and** [comment]
Sounds good. Thank you.
