### ISSUE TITLE
megadl doesn't use account session when downloading folder links

### ISSUE THREAD

**Issue by Stealthii** [megous/megatools#304]
#298 adds support for using account details if provided with `megadl`

Small issue noticed - the session doesn't exist when using `megadl` to grab folder links (example: https://mega.nz/#F!zzzZZZZZ!AAAAaA1aAA11aa1aaAAaaA)

When using this project's code, the session silently drops to public auth, and hits the 5GB limit. When using my code (forced auth requirement), we can see the session doesn't exist for individual downloads:

```
(megadl:1): Mega-CRITICAL **: mega_session_get_node_chilren: assertion 's != NULL' failed
```

**Comment by megous** [comment]
Thanks for the report. Can you please try again with the master branch?

**Comment by Stealthii** [comment]
Can confirm this is working now! Thanks

**Comment by megous** [comment]
Good to know. Thanks for testing.
