### ISSUE TITLE
change account password, name, etc

### ISSUE THREAD

**Issue by amper5and** [megous/megatools#308]
Is there a way to change an account password, or name, or anything else? I manage hundreds of mega accounts, so I need to do this through the command line.

**Comment by megous** [comment]
Change password: https://github.com/megous/megatools/blob/dev/js/tools/passwd.js

Changing user name should not be much harder than that. Though there's no tool for that in the 2.0 branch.

**Comment by amper5and** [comment]
Thanks for the reply, but it's not obvious to me how to use the js branch. Does it run in Node or something? If you can point me in the right direction, that would be much appreciated.

**Comment by megous** [comment]
It's just the same like with the stable branch. Compile it, [install it], run it. It uses embedded JS engine Duktape. It may have slightly different dependencies, but that's about it when it comes to the differences with build/installation.

**Comment by megous** [comment]
Just be careful, while many of the commands will work, the branch is in the middle of development and was not tested thoroughly.

**Comment by amper5and** [comment]
ok, I'll give it a whirl. Thanks.
