### ISSUE TITLE
Allow megals to list exported folders.

### ISSUE THREAD

**Issue by i30817** [megous/megatools#309]
This is needed for me to implement to myself the 'download everything new, delete everything deleted remotely' on public folders. As you probably know, i implemented this as a script using megals, only since megals only works on our mega account, i need to frivolously copy the public folder to my account.

I'm asking that either megals gets the ability to iterate over public folders, or megadl get the ability to delete files in --path that are not in the remote. Adding a small check option for overwrite if the size is different even if the name is the same, even if not having the certainty of checksums would be nice, but for my usecase, the first request suffices, since these files are name versioned.

**Comment by megous** [comment]
Megals will not get it. It is meant as a command that works only on account folders.

Though you can probably add this functionality to megadl. Something like megadl --list 'folder-link'

**Comment by i30817** [comment]
Eh, if a feature is going directly into megadl, i'd prefer if it was something like 'mirror-names' that deletes extra files directly. It seems to be more 'semantically appropriate' than having a random 'ls' function on a command to download, and it's what i 'actually' want.

**Comment by megous** [comment]
It might still be nice to have a preview of a content of a folder without the need to download it. It's also nicer to use than having it in multiple commands.

**Comment by i30817** [comment]
Yes, i agree. I could use it too for different behavior than simply delete, but to place in trash for example.

**Comment by i30817** [comment]
Rereading this, i actually want this for public folders, not my account so i'd want the feature in `megadl` itself. I only mentioned `megals` because importing public folders to my account is a workaround i currently use for lack of sync on public folders. If the public folder uses version versioning, megals after that import allows me to check what's new and download only that and check what's obsolete and download that.

But if megadl had a listing of the files on the public folder, i could do that directly and save major hassle (also i've found that mega account download bandwidth on registration expires and i don't have any anymore).

**Comment by megous** [comment]
Implemented via --choose-files. Sync like functionality is tracked as part of issue #20
