### ISSUE TITLE
IRC Channel

### ISSUE THREAD

**Issue by TerminalMan** [megous/megatools#312]
I don't think there is an IRC Channel yet, is there?

I opened #megatools on freenode.

Feel free to drop in.

**Comment by megous** [comment]
Hi, I don't do online chat if I can avoid it. :)

Anyway, I don't mind adding info about the channel to the README.md, so that people know that it's available, if you like.

**Comment by TerminalMan** [comment]
Can't hurt i guess.

In the meantime: 
I was trying to implement an IP reset option to circumvent the traffic limit cutoff. This failed because apparently a download in progress doesn't like to be continued on a new IP address. Interrupts without a new IP appear to resume fine.

Regaining a new IP between two file downloads appears to work fine as well. (That is my workaround for the time being.)

Therefore i conclude this is a problem caused by the mega server.
I know that JDownloader supports this feature, therefore there has to be a trick to restart the download at the cutoff point. Do you, by accident, happen to work on this very feature?

**Comment by megous** [comment]
No I don't. API-wise, you should be able to restart download at any point, with any address range. Or just request a new download for the same node and restart from where it stopped previously using new IP address.

Though the code is not very well structured for these kinds of tricks.

**Comment by megous** [comment]
The channel is long dead.
