### ISSUE TITLE
All commands except megareg output "ERROR: You must specify your mega.nz username (email)"

### ISSUE THREAD

**Issue by Raserhead** [megous/megatools#313]
Recently installed this to hopefully improve my backup processes but I haven't been able to get it to work beyond account creation and verification.

Each command other than megareg, regardless of what extra variable I use, just outputs the message:
"ERROR: You must specify your mega.nz username (email)"

Is there something I have missed?

**Comment by megous** [comment]
Here is the documentation:

https://megatools.megous.com/man/megarc.html
https://megatools.megous.com/man/megatools.html

You either want to provide your credentials on the command line or in the configuration file.

**Comment by Raserhead** [comment]
For some reason through all my documentation digging I could not find that page.
Thank you.
