### ISSUE TITLE
ERROR: Can't login to mega.nz: API call 'ug' failed: Server keeps asking us for EAGAIN, giving up

### ISSUE THREAD

**Issue by goodmind** [megous/megatools#314]
`megals` with `--debug api` infinitely prints
```
-> [{
	"a": "ug"
}]
<- -3
```

In the end
```
ERROR: Can't login to mega.nz: API call 'ug' failed: Server keeps asking us for EAGAIN, giving up
```

**Comment by megous** [comment]
Were you able to login before?

This looks like an issue with server being busy.

**Comment by megous** [comment]
Were you able to login before?

This looks like an issue with server being busy, or perhaps some IP specific limit on number of api calls.

**Comment by goodmind** [comment]
@megous well, I opened web version for a while and it loaded after 10 minutes or more

**Comment by megous** [comment]
I don't understand what you're saying. mega.nz web was loading for 10 minutes?

**Comment by goodmind** [comment]
@megous yes

**Comment by megous** [comment]
Then I guess it was some IP address based limit.
