### ISSUE TITLE
megadl can't to download

### ISSUE THREAD

**Issue by ericvipo** [megous/megatools#315]
**# megadl can't to download but via the web it is possible.**
I use Manjaro Linux.

When I execute: 
`megadl 'https://mega.nz/#!cA1xhIJK!jmeBp_mF3bfU-IQW8wlyM7haaE4bmnm1Z3dmMbEkhYM'`

Then I get this error:
`ERROR: Download failed for 'https://mega.nz/#!cA1xhIJK!jmeBp_mF3bfU-IQW8wlyM7haaE4bmnm1Z3dmMbEkhYM': Data download failed: Server returned 509`

![image](https://user-images.githubusercontent.com/25522126/30205928-159bb47c-9450-11e7-8806-8209db140e29.png)

**Comment by megous** [comment]
Mega.nz started enforcing IP address based quotas of 5GB. You can use premium account to wit megatools from git and megadl.

**Comment by andrewfashion** [comment]
@megous How do you login with megadl? I'm on 1.9.98 and I installed via Homebrew

megadl --username isn't working

**Comment by megous** [comment]
You need 1.9.99git. It can be found on the website, in the archive.
