### ISSUE TITLE
megadl doesn't login

### ISSUE THREAD

**Issue by asturel** [megous/megatools#316]
`h:\megatools-1.9.98-win64>megadl --config="h:\megatools-1.9.98-win64\mega.ini" --path="d:\series\Dragon Ball Super" https://mega.nz/.....`

after 5 files probably I reach the download limit so i got bunch of:
`ERROR: Download failed for /Dragon Ball Super 001-014/[Naruto-Kun.Hu] Dragon Ball Super 006 [720p].mp4: Data download failed: Server returned 509` which results lot of 0bytes files

**Comment by megous** [comment]
Login is supproted from 1.9.99+

**Comment by mqudsi** [comment]
Thanks for fixing this. Was it a bug or simply not implemented? Because `megadf` logged into the account just fine with 1.9.98. 

Using the git-master build now and all is well.

**Comment by megous** [comment]
It still works without an account though and with 1.9.99 you should be able to download files bigger than 5GB even using free quota limits, because of download resume functionality. You just restart the download command after waiting a few hours to get free quota refilled.

**Comment by mqudsi** [comment]
Thanks for the explanation, it makes sense.

**Comment by KrunchMuffin** [comment]
where do we get 1.9.99?

**Comment by megous** [comment]
On the official website. https://megatools.megous.com/builds/
