### ISSUE TITLE
megals doesn't work in rpi

### ISSUE THREAD

**Issue by alfredoivan** [megous/megatools#317]
I get the following when using megals:

pi@pi-NOMBRE:~/megacmd/megatools-1.9.98 $ ./megals
Segmentation fault

Notice that megadf works fine in this system:
pi@pi-NOMBRE:~/megacmd/megatools-1.9.98 $ ./megadf --human
Total: 50,0 GiB
Used:  24,3 GiB
Free:  25,7 GiB

So it must be something inherently to megals
The version i am using is the one that can be unzipped:
megatools-1.9.98.tar.gz

My .megarc config file is correctly configured

device:
$ uname -a
Linux pi-NOMBRE 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux

![megals_doesnt_work](https://user-images.githubusercontent.com/5880102/31057129-ddcb4956-a6b3-11e7-9769-367239dd3bec.png)

**Comment by CMoranO** [comment]
try 

$ megals --reload

**Comment by alfredoivan** [comment]
I did, same thing happened: Segmentation fault
I noticed that parts of the other commands (namely, megaput ) also throw errors (no picture available). Maybe it has something to do with raspberry being ARM

![megals_not_working_2](https://user-images.githubusercontent.com/5880102/31079207-2e59555a-a75b-11e7-95a7-fcfb035dad99.png)



Also, i tested the same commands in my Ubuntu 14.04 64bit and all of the commands work fine. So it might be something with the "Linux compilation of megatools" and "raspberry pi internal workings".

**Comment by megous** [comment]
Try running under gdb and when you hit a crash run a bt command (backtrace).

**Comment by zubinbt** [comment]
Just tested it on my RPi3 on Raspbian. It works fine for me.

**Comment by megous** [comment]
Power supply/USB cable issues? Is the machine otherwise stable when doing computing stuff/loading 1 core to 100%?

**Comment by megous** [comment]
Perhaps run memtest in combination with some cpuburn-like workload in the background.

If that doesn't break the machine, it would help to have a gdb output. Build megatools with export CFLAGS="-g -Og" and run them under gdb.
```
# gdb
load /path/to/megaget
set args /Root/some-file
r
```
and when it segfaults

```
bt
```

I'll close it for now, because the report is old, and it is pretty safe to assume it's a HW issue. Please, re-open it if you have new infomration.
