### ISSUE TITLE
Build for Node.JS?

### ISSUE THREAD

**Issue by k-miras** [megous/megatools#318]
I'm not good at C and C++ but it is possible to make a build for Node.JS and use all of Megatools through the JavaScript?

**Comment by megous** [comment]
If you're talking about the dev branch, then yes, but you'd need to implement a compatibility layer for the API that is currently implemented in C. That is all the C.* functions.

**Comment by k-miras** [comment]
Is there any plans to publish megatools as npm package at the next milestone or make branch that compatible with Node.JS?

**Comment by megous** [comment]
Not at all. I chose Duktape, because it is nicely embeddable.
