### ISSUE TITLE
Build for iOS ?

### ISSUE THREAD

**Issue by 48D4LW4H48** [megous/megatools#320]
Can someone build this tool for iOS clang 
It would be so useful

**Comment by zubinbt** [comment]
Or you can just use the [official app](https://itunes.apple.com/in/app/mega/id706857885?mt=8)?

**Comment by 48D4LW4H48** [comment]
it won't help me 
Because I need to upload multiple files using the terminal

**Comment by megous** [comment]
There'll be no official builds for iOS.
