### ISSUE TITLE
Server returned 509 when try to download big file

### ISSUE THREAD

**Issue by realKSMC** [megous/megatools#324]
I tried to download an file >30GB big. The server returns 509 as message.
Downloading the file using `megadl --config /home/mega.ini 'https://mega.nz/#!LINK'`

What am I doing wrong? :)

**Comment by megous** [comment]
Google says: Error 509 - Bandwidth Limit Exceeded

**Comment by nielsmittertreiner** [comment]
Megatools and Megadownloader are not able to download files bigger than the standard limit. This was a bug and MEGA fixed it

**Comment by PixiBixi** [comment]
Why do we have this error even if we are logged in with a premium account?

I couldnt download more than 3GB, like a free account...

**Comment by megous** [comment]
What version of megatools are you using? Try https://megatools.megous.com/builds/ 1.9.99git.

**Comment by PixiBixi** [comment]
I'll try it tonight, thanks! (I might have1.98 if i remember)

**Comment by PixiBixi** [comment]
Always have 509 w/ last version

```
megadl --version
megatools 1.9.99git - command line tools for Mega.nz
```

**Comment by megous** [comment]
Did you use your username and password with the megadl tool? It has new parameters for authentication. In the past it didn't. Sorry to be obtuse. :)

You can also use --debug=api to see if it is authenticating before downloading anything.

**Comment by megous** [comment]
Anyway, I have uploaded an updated 1.9.99git builds that reflect the latest git changes, including a fix for quota use with folder downloads with megadl. You may try to update.

**Comment by PixiBixi** [comment]
I've tried with .megarc and username and password, i'll try it again later

**Comment by PixiBixi** [comment]
Ok, i've compiled ure last version right now

```megadl --config /root/.megarc --debug api 'https://mega.nz/#F!x!x'
-> [{
	"a": "us",
	"user": "\"contact@x.fr\"",
	"uh": "WXUu5-L-meI"
}]
<- [
	-9
]
ERROR: Can't login to mega.nz: API call 'us' failed: Server returned error ENOENT

(megadl:37830): Mega-CRITICAL **: mega_session_watch_status: assertion 's != NULL' failed

(megadl:37830): Mega-CRITICAL **: mega_session_open_exp_folder: assertion 's != NULL' failed
[1]    37830 segmentation fault  megadl --config /root/.megarc --debug api```

My IDs are corrects

```.megarc
[Login]
Username = contact@x.fr
Password = "pwd
```

**Comment by anirudhpulikonda** [comment]
I think not Megadownloader is working fine. I'm using this guide: [Download Mega Files using IDM](https://megadownloaderapp.com/download-mega-files-idm-directly/) 

For faster downloads and resumable one's using IDM. Hope this helps. BTW, works with Megadownlader and not with megatools.
