### ISSUE TITLE
Critical: Implement size and checksum verification of downloaded files

### ISSUE THREAD

**Issue by i336** [megous/megatools#326]
Hello,

To download large directory trees from MEGA I have created my own account which I import data into, then I use `megacopy` against this personal account to actually sync the data to my own disk. (If there's a tool that will recursively download whole trees I'd love to know about it.)

**I've just realized that `megacopy` will very happily skip a file if *anything* with the same name exists on the local disk, even an incomplete/corrupt copy of the remote file. I proved this by repeatedly `^C`ing `megacopy` before it finishes downloading a given file and finding that it would promptly skip to the next file upon restart.**

I am so glad I discovered this early!! I now have about 60GB of data to work on slowly redownloading because I needed to `^C` megacopy several dozen times ***and I now have concrete proof that my local archives are corrupt because of this. :(***

The most basic solution I would strongly request be implemented is that the `s` field in the MEGA data be compared with the local file size, and that if the local file is different from the remote file then either the local file is resumed, or deleted and started again. Resumption is probably the better idea for users `megacopy`ing single multi-GB files on glitchy connections!

Beyond that, I would absolutely support a "checksum every file already found on disk" option (and, while I'm at it, a "checksum every newly-downloaded file" option as well). I recognize these would slow the sync process down and use a lot of CPU, and I completely accept that.

Alternatively megatools could maintain a small journal file, adding "file X checksum good"-type info once file *X* had been downloaded and verified. That would speed up restarts quite well.

Incidentally... after beginning to write this report I was shocked to remember/realize that several years ago I actually ran into this exact problem. I now vaguely recall that I looked into the MEGA protocol, found the checksum fields, ran one of the megatools programs with `--debug api`, captured the checksum data from stderr, and removed corrupted files manually. The program I wrote to do this is on a disk I haven't been able to access for some years and I totally forgot I even wrote it. I only just remembered as I wrote this report.

Few cloud storage providers offer checksum data, so all I often have to fall back on is an archive's "test integrity" option - if I'm downloading an archive in the first place. MEGA provides first-class support for universal file verification, and I am simply stunned that megatools ***still*** doesn't use this feature. I last used the aforementioned disk around 2013-2014, so that makes it 3 years without support for checksumming. Hence this strongly-worded ***bug*** report.

Yes; I am completely aware of the fact that this is a 3rd-party client developed by volunteers who do not have infinite time on their hands, and for the sake of argument I'll accept that. But still. D':

I cannot find a "get version" parameter in any megatools program, and the version is not printed in `--help-all` :( but I found that my package manager reports that I am using 1.9.98-2. I am not sure if I manually rebuilt a newer version over the top of that though. How do I get version information directly out of the binary?

If this bug report and megatools does provide checksum and size verification then this report is in error then I take it back and apologize.

**Comment by i336** [comment]
Ah, it does compare checksum! Very awesome!

Using temporary files is far better than my journal idea and is an excellent solution. That pretty much solves this entire issue.

Also, if megacopy finds a temporary file before downloading an item, a potential enhancement could be resuming downloading instead of removing potentially GBs of data and starting again.

In my case I'm downloading multiple GBs of many small files (<20MB) on a fast connection so removing and starting again works for me, but that's just this situation. If the MEGA API allows it (?), resuming a partial download would be a very nice user experience.

But having the functionality reach a consistent local state after interruptions would be great :+1:

**Comment by megous** [comment]
It should work fine now. For download resumption, there is another open issue.

**Comment by i336** [comment]
After a bit of makefile tinkering on FreeBSD, I got it rebult from git.

That is the fastest response time I've seen. Thanks so much!! :heart:

**Comment by megous** [comment]
Also, download resume should work now too.

**Comment by megous** [comment]
Let me know if it works. I tested it with randomly breaking the megadl/get many times, and so far I have not seen any issues.
