### ISSUE TITLE
master branch fails to build on fedora 25

### ISSUE THREAD

**Issue by khambrecht** [megous/megatools#328]
$ git branch -v
 * master e2829f9 Fix wrong order of put_compat arguments

$ make
  CC       lib/mega.o
lib/mega.c: In function 'mega_session_download_data':
lib/mega.c:3442:34: error: expected ')' before 'PRIu64'
     url = g_strdup_printf("%s/%" PRIu64 "-%" PRIu64, params->download_url, download_from, params->node_size - 1);
                                  ^~~~~~
lib/mega.c:3442:29: warning: format '%s' expects a matching 'char *' argument [-Wformat=]
     url = g_strdup_printf("%s/%" PRIu64 "-%" PRIu64, params->download_url, download_from, params->node_size - 1);
                             ^
lib/mega.c:3442:31: warning: spurious trailing '%' in format [-Wformat=]
     url = g_strdup_printf("%s/%" PRIu64 "-%" PRIu64, params->download_url, download_from, params->node_size - 1);
                               ^
Makefile:657: recipe for target 'lib/mega.o' failed
make[1]: *** [lib/mega.o] Error 1
Makefile:460: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by megous** [comment]
Looks like Fedora 25 is missing PRIu64 macro definition in inttypes.h.

**Comment by megous** [comment]
Ah perhaps try configuring and compiling with CFALGS="-std=c11"?

**Comment by megous** [comment]
Hmm,
```
#include <inttypes.h>
```

is missing in mega.c. I'm not sure why that doesn't matter on my machine, but perhaps adding that can fix it on yours?

**Comment by khambrecht** [comment]
yes, adding `#include <inttypes.h>` fixed it.

**Comment by megous** [comment]
Thanks, it should be fixed now.
