### ISSUE TITLE
megaput / megacopy , support for public Mega-links

### ISSUE THREAD

**Issue by sparomba** [megous/megatools#331]
Currently megaput and megacopy only support uploading of local files. The webinterface of Mega however also supports adding files/folders from public mega-links to one's private web storage without having to download and re-upload the file/s ("'Import to your Cloud Drive").

Under 9.3.15 in the Mega [documentation](https://mega.nz/doc) it only references the "import" function using their SDK. The whole process inside the SDK starts [here](https://github.com/meganz/sdk/blob/master/src/megaapi_impl.cpp) from function "MegaApiImpl::importFileLink".

There also is a Python implementation [here](https://github.com/richardasaurus/mega.py/blob/master/mega/mega.py) that contains the API request. Starting at function "import_public_url" and subsequent function "import_public_file", where the latter seems to form the api request.

It would be great, if importing public links would be supported in megatools 2.0!

**Comment by megous** [comment]
Well, it is. :) Checkout the dev branch.
