### ISSUE TITLE
Add mv like command for moving files

### ISSUE THREAD

**Issue by aranmohyeddin** [megous/megatools#333]
Please add an option for moving files like mv.

I think it's better to use mega with options instead of having different commands for each task

I think there is a bug. when I'm in an ssh session to a server and then I edit my .megarc in my local system and send it to the server mega won't recognize it unless I exit and ssh again. but this is not that big a deal.

thanks for your great tool:)

**Comment by megous** [comment]
Move command is already implemented in the dev branch.

I'm not sure about the other two issues. In the dev branch there's just a single megatools command, so you can use megatools like:

    megatools mv a b

Ssh issue needs more info.

**Comment by liar666** [comment]
Using "megatools 1.11.0" here. `megatools mv` does not exist. It has been removed (again)?
