### ISSUE TITLE
proxy with authentication

### ISSUE THREAD

**Issue by mikadoryu** [megous/megatools#334]
I'm trying to use a proxy with username and password but the only thing I get is an error:

this is the code that I am using:

megacopy --proxy mail@gmail.com:pass@proxy.com -u accountmega@yopmail.com -p pass --local / home / madoka / directory / upload --remote / Root / --download

when executing in the end you get this:

ERROR: Can not login to mega.nz: API call 'us' failed: HTTP POST failed: CURL error: Could not connect to server

Does megatools support proxy with authentication?

**Comment by megous** [comment]
You can't have @ in the username, as it is a character that marks the end of the username/password information. You need to urlencode your passwords/usernames.

Also if you don't provide a schema, it is assumed to be a http proxy, which I'm not sure is what you want.

**Comment by mikadoryu** [comment]
thanks for answering.

unfortunately the proxy asks for my email to authenticate, so I have the problem. the proxy works with http or sucks5

my main idea is to be able to download several accounts at the same time with the proxy. As I do with jdown, but when decrypting the files it takes more time than megatools does.

**Comment by megous** [comment]
Nothing unfortunate about that, you just have to urlencode the email address and it should work.

**Comment by mikadoryu** [comment]
thanks now if it works, try with all the mail code but it did not work. now just changing the first one @ works without problem
