### ISSUE TITLE
ESC_CLREOL sometimes not quite a correct solution

### ISSUE THREAD

**Issue by galtgendo** [megous/megatools#335]
I'm not sure if the problem is bash specific or generic, but as per definition, ESC_CLREOL clears one line only.
If for any reason the output is longer than that, only the last line is removed, causing console spam (in case of - for example - downloads).

**Comment by megous** [comment]
Yeah, corner cases abound. I also have issues with other tools that do something similar when resizing the console window while the progress is being shown.

It's not easy to fix, so I probably will not. :)
