### ISSUE TITLE
ERROR: Can't open folder 'https://mega.nz/#XXXXXXXXXX': API call 'f' failed: Server returned error EBLOCKED

### ISSUE THREAD

**Issue by dlo** [megous/megatools#336]

**Comment by megous** [comment]
Any more info?

**Comment by megous** [comment]
API_EBLOCKED (-16): User blocked

**Comment by dlo** [comment]
Is there a way to print debug info?

**Comment by megous** [comment]
Yes, but that will not help. I meant what command are you running, are you logging in or not, does it work on mega.nz website, etc. Some context.

Anyway, the error is saying that the user was blocked from mega.nz.

**Comment by dlo** [comment]
Got it, sorry about that! Not logged in, haven't tried downloading from mega.nz (don't have an account).

**Comment by megous** [comment]
Ok, so the best explanation is that user who uploaded the folder is blocked/banned from mega.
