### ISSUE TITLE
Allow download of individual files from folder?

### ISSUE THREAD

**Issue by mqudsi** [megous/megatools#337]
Hi there,

Curious if there's some way to use `megadl` to download individual files from a folder (without going through the whole "import to own folder, generate link, download" song-and-dance)?

This would be handy for an additional reason besides the obvious use case of only _wanting_ a single file from a folder: it could also be used to simultaneously download _n_ files in a folder with _n_ separate instances of `megadl`.

**Comment by megous** [comment]
Hi. There isn't ATM. API allows this, and it's not that hard. But someone has to implement it.

This feature request is already tracked in some other issue. (#83)

**Comment by svnpenn** [comment]
https://github.com/megous/megatools/issues/218
