### ISSUE TITLE
Upload whole directory with megaput

### ISSUE THREAD

**Issue by Feriman22** [megous/megatools#338]
How can I upload the whole directory to MEGA?

Currently I tried this below command, but I got an error message (no such file or directory )

megaput -u $USER -p $password --reload --path $MEGApath/ $localpath/*

Temporary I solved it, but this is not a good solution, because not all files contain "dot":

megaput -u $USER -p $password --reload --path $MEGApath/ $localpath/*.*

What is the solution for solve this issue?

**Comment by megous** [comment]
Use the megacopy command.
