### ISSUE TITLE
makeslice: len out of range

### ISSUE THREAD

**Issue by tb-303** [megous/megatools#339]
Copying /Backup-03_17_2018.tar.xz -> mega:/server/ # 0.00 % of 3.2GB at 0B/s 0s panic: runtime error: makeslice: len out of range

goroutine 28 [running]:
github.com/t3rm1n4l/megacmd/vendor/github.com/t3rm1n4l/go-mega.(*Mega).UploadFile.func2(0x19521d70, 0x193d7ac0, 0x195214a0, 0x1951ad30, 0x1940b0a0, 0x1940c734, 0x10, 0x40, 0x8385880, 0x1940b080, ...)
        /home/ncw/go/src/github.com/t3rm1n4l/megacmd/vendor/github.com/t3rm1n4l/go-mega/mega.go:954 +0x576
created by github.com/t3rm1n4l/megacmd/vendor/github.com/t3rm1n4l/go-mega.(*Mega).UploadFile
        /home/ncw/go/src/github.com/t3rm1n4l/megacmd/vendor/github.com/t3rm1n4l/go-mega/mega.go:941 +0x8df

**Comment by megous** [comment]
Incorrect project.

**Comment by tb-303** [comment]
actually, no, I compiled from just now to verify from
 https://github.com/megous/megatools/archive/master.zip

and

# megacmd put /test mega:/server/ -conf /root/.megacmd.json
Copying /test -> mega:/server/ # 0.00 % of 3.6GB at 0B/s 0s panic: runtime error: makeslice: len out of range

goroutine 28 [running]:
github.com/t3rm1n4l/megacmd/vendor/github.com/t3rm1n4l/go-mega.(*Mega).UploadFile.func2(0x1956dd90, 0x194d7ac0, 0x1956d4b0, 0x19566d40, 0x19503080, 0x19506734, 0x10, 0x40, 0x8385880, 0x19503060, ...)
        /home/ncw/go/src/github.com/t3rm1n4l/megacmd/vendor/github.com/t3rm1n4l/go-mega/mega.go:954 +0x576
created by github.com/t3rm1n4l/megacmd/vendor/github.com/t3rm1n4l/go-mega.(*Mega).UploadFile
        /home/ncw/go/src/github.com/t3rm1n4l/megacmd/vendor/github.com/t3rm1n4l/go-mega/mega.go:941 +0x8df
