### ISSUE TITLE
I can not download from MEGA

### ISSUE THREAD

**Issue by yonaikerlol** [megous/megatools#340]
The command I use to download from MEGA:

``megadl 'https://mega.nz/#!xXQmhDBK!2WFWQrfJHyT88BIteCMhJCLYh4kxd6hJZDOTL4IJL18'``

And I get the following error:

ERROR: Download failed for 'https://mega.nz/#!xXQmhDBK!2WFWQrfJHyT88BIteCMhJCLYh4kxd6hJZDOTL4IJL18': API call 'g' failed: Server returned error ETOOMANY

**Comment by megous** [comment]
What do you think the issue is?

**Comment by yonaikerlol** [comment]
I already solved it, it's not really Megatools problem, it's MEGA.NZ problem, I had to use a VPN so I could download the file.

You can close this issue.

**Comment by megous** [comment]
Ok. :+1:
