### ISSUE TITLE
compilation issue on aarch64 Qnap NAS libcurl not found in Prefix

### ISSUE THREAD

**Issue by nephaste** [megous/megatools#341]
Hi i am trying to pushing megatools on Qnap NAS, while all is ok on x64
compiling on aarch64 remins libcurl not found in my $PREFIX

compiled with 

```
export PREFIX=/opt/Megatools

git clone https://github.com/megous/megatools.git

cd megatools

./autogen.sh

export PKG_CONFIG_PATH="${PREFIX}/lib/pkgconfig"
export LIBCURL_CFLAGS="-I${PREFIX}/include"
export LIBCURL_LIBS="-L${PREFIX}/lib"
export GLIB_CFLAGS="-I${PREFIX}/include/glib-2.0"  
export GLIB_GENMARSHAL="${PREFIX}/bin/glib-genmarshal" 
export GLIB_MKENUMS="${PREFIX}/bin/glib-mkenums" 
export GOBJECT_QUERY="${PREFIX}/bin/gobject-query"

LIBS="-lffi" \
PKG_CONFIG_PATH="${PREFIX}/lib/pkgconfig"  \
CFLAGS="-O2 -I${PREFIX}/include " \
CXXFLAGS="-O2 -I${PREFIX}/include"     \
LDFLAGS="-L${PREFIX}/lib -Wl,-rpath,${PREFIX}/lib" \
CPPFLAGS="-O2 -I${PREFIX}/include"     \
./configure \
--prefix=${PREFIX} \
--bindir=${PREFIX}/bin \
--sbindir=${PREFIX}/bin \
--libexecdir=${PREFIX}/libexec \
--libdir=${PREFIX}/lib \
--datadir=${PREFIX}/share \
--datarootdir=${PREFIX}/share \
--sysconfdir=${PREFIX}/etc \
--sharedstatedir=${PREFIX}/com \
--localstatedir=${PREFIX}/var \
--includedir=${PREFIX}/include \
--oldincludedir=${PREFIX}/include \
--infodir=${PREFIX}/share/info \
--localedir=${PREFIX}/share/locale \
--disable-glibtest
```
always killing with 

checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.16... yes
checking for GLIB - version >= 2.32.0... yes (version 2.48.2)
checking for OPENSSL... yes
checking for LIBCURL... no
configure: error: Package requirements (libcurl) were not met:

No package 'libcurl' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables LIBCURL_CFLAGS
and LIBCURL_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

libcurl 1.59 is well embedded in my $PREFIX lib & include & lib/pkgconfig ...

i am stuck.. thanks for your help

[config.log](https://github.com/megous/megatools/files/1884908/config.log)

**Comment by megous** [comment]
Hi, do you have libcurl development package installed?

You need a package that has libcurl.pc file in it. That's what pkg-config is complaining about.

**Comment by megous** [comment]
Or perhaps don't set this:

    export LIBCURL_CFLAGS="-I${PREFIX}/include"
    export LIBCURL_LIBS="-L${PREFIX}/lib"

This should be set by the libcurl.pc if you compiled curl into different PREFIX.

**Comment by megous** [comment]
In your config.log:

    PKG_CONFIG_PATH=''

PKG_CONFIG_PATH is not being passed corectly to the configure script.

**Comment by nephaste** [comment]
yes i see that as well, that why i tried an export before launch ./configure

export PKG_CONFIG_PATH="${PREFIX}/lib/pkgconfig"
and also
export LIBCURL_CFLAGS="-I${PREFIX}/include"
export LIBCURL_LIBS="-L${PREFIX}/lib"

but really dont understand why it is doesnt take by the script...

i confirm all files are present inside the directories... i had no issue to compile it on x64 plateform
look like somethin in the autoconf script cannot find libcurl headers (may be related to the aarch64 )
i have really no clue...

**Comment by nephaste** [comment]
just saw at the moment .. glib2 isnt pickup to right location as well

`GLIB_CFLAGS='-pthread -I/usr/include/glib-2.0 -I/usr/lib/aarch64-linux-gnu/glib-2.0/include'
GLIB_COMPILE_RESOURCES='/usr/lib/aarch64-linux-gnu/glib-2.0/glib-compile-resources'
GLIB_GENMARSHAL='glib-genmarshal'
GLIB_LIBS='-lgio-2.0 -lgobject-2.0 -lglib-2.0'
GLIB_MKENUMS='glib-mkenums'`

while it is in my $PREFIX as well

**Comment by megous** [comment]
If you're trying to cross-compile you need to set --host

You also don't want these:

    export GLIB_GENMARSHAL="${PREFIX}/bin/glib-genmarshal" 
    export GLIB_MKENUMS="${PREFIX}/bin/glib-mkenums" 
    export GOBJECT_QUERY="${PREFIX}/bin/gobject-query"

Because you'll not be able to execute those binaries on your build machine.

You also don't want PKG_CONFIG_PATH, but PKG_CONFIG_LIBDIR so that you're not mixing up headers from the build system with headers from the host system.

Also drop all the hand modifications to CFLAGS, LDFLAGS and LIBS, except for perhaps optimization options in CFLAGS. Those should be handled by --host and pkg-config automatically.

**Comment by megous** [comment]
For example my cross-build for windows uses just this:

```
  export PKG_CONFIG_LIBDIR="/usr/x86_64-w64-mingw32/lib/pkgconfig/"
  unset LDFLAGS PKG_CONFIG_PATH CFLAGS

  ../configure \
    --prefix=/usr/x86_64-w64-mingw32 \
    --host=x86_64-w64-mingw32

...
```

And that's all you need.

**Comment by nephaste** [comment]
I think i found... it is just a crazy thing...

i thing something bad in my environment, interfering with your autoconf ... basically, I create a bash script which compile all dependencies in PREFIX... and call git clone for megatool... etc...

using my script it remains these erros.. the variable are not passed in autoconf...

if i launch manually all my export and launch the same ./configure all is ok...

first time i have this problem... the weird thing is the dependencies are well compiling with any issue...

think issue can be closed, unless you want more info

**Comment by nephaste** [comment]
I will double check with armv7l 32 bit version...

**Comment by megous** [comment]
Weird. Let me know if you find out the cause.

**Comment by nephaste** [comment]
same happen with ARMv7l in an Ubuntu 1404 chroot....

I am lost about this... anyway i compile it manually and all is ok...

**Comment by nephaste** [comment]
now available for Qnap  :)))

https://qnapclub.eu/fr/qpkg/564

**Comment by megous** [comment]
Good work!
