### ISSUE TITLE
Support for wildcards in megarm?

### ISSUE THREAD

**Issue by nexxai** [megous/megatools#342]
It would make my life infinitely easier if I could do something like:

`megarm filename-*.doc`

Is that possible?

**Comment by megous** [comment]
You need to  combine more tools to achieve that.

    megals | grep "filename-[^/]+\\.doc"

If you're happy with the list of files you may then do:

    megals | grep "filename-[^/]+\\.doc" | xargs -d\n megarm

Just be aware that the grep will match that filename in any directory. If you need something more specific you need to make a more specific regular expression.

**Comment by nexxai** [comment]
Perfect - got the script working.  Thank you!
