### ISSUE TITLE
 Can you hide the login data?

### ISSUE THREAD

**Issue by DevFabrizio** [megous/megatools#345]
Taking into account that to make "login" you have to place the data in the file "mega.ini" without any type of encryption, being able to be seen by anyone who accesses the file.
![screenshot_6](https://user-images.githubusercontent.com/38484233/38910712-4c1b0cf2-4290-11e8-815d-e0437297f897.png)

Will there be a way to login without writing the data in "mega.ini"?

**Comment by megous** [comment]
You can use ACL on the file to make it readable only by you.

**Comment by megous** [comment]
You can also enter your password to the password prompt if you leave it out from mega.ini.

**Comment by DevFabrizio** [comment]
¿ACL? 
I am not related to this term Will you have a reference link?

**Comment by DevFabrizio** [comment]
If I omit it
![screenshot_7](https://user-images.githubusercontent.com/38484233/38911383-782cc03e-4294-11e8-9d6f-e9c4b00eb992.png)
ill you ask me for the password when sending an application?
Will you have an example of the command?
