### ISSUE TITLE
Feature request: add option/tools to download & save backup/recovery key

### ISSUE THREAD

**Issue by liar666** [megous/megatools#346]
In the web interface, when you go to:
https://mega.nz/backup
you can download & save the backup/recovery key.

It would be very convenient to be able to key the key file in CLI rather than login in the website.

**Comment by megous** [comment]
This is already implemented in the dev branch.

https://github.com/megous/megatools/blob/dev/js/tools/info.js

**Comment by liar666** [comment]
Oh! Cool! Thanks!
I searhc whithin the previous issues, if someone already aksed the question, but didn't think of looking in the code :)

**Comment by megous** [comment]
No problem, dev branch is a bit hidden, anyway. :)
