### ISSUE TITLE
Add megatools to the chocolatey package manager repository

### ISSUE THREAD

**Issue by ERap320** [megous/megatools#347]
Because of its CLI nature it would be awesome to be able to install megatools with a package manager on Windows too.
Would you be able to distribute the Win version of this software through chocolatey?

I think it doesn't need introductions since it is well known, but here is the link, just in case: https://chocolatey.org/

**Comment by ERap320** [comment]
Then, if I have your approval and I happen to find the time in the next month or so, I'd be glad to look into packaging it myself and reporting back to you when/if it's done.

**Comment by ERap320** [comment]
I madre and submitted the Megatools package. Now it is availlable through chocolatey.
You can find its page at this link: https://chocolatey.org/packages/megatools/

**Comment by megous** [comment]
Thank you, I've added the information to the readme, and to the website.

**Comment by megous** [comment]
Megatools 1.10.0 will be released soon.

**Comment by ERap320** [comment]
I'll be ready to package it as soon as it's available

**Comment by ERap320** [comment]
The chocolatey package for version 1.10.0 will soon be approved and available for users.

**Comment by megous** [comment]
Thanks! :+1:

**Comment by megous** [comment]
Sorry for trouble, but I had to re-build the packages, because libcurl got built with a wrong ssl backend. I didn't bump the version for that, because the code is the same.

**Comment by ERap320** [comment]
No problem, will reupload the package as soon as I can

**Comment by alfredonodo** [comment]
Hi, the current chocolatey package uses a wrong URL to download megatools.
