### ISSUE TITLE
megatools mkdir error creating folder

### ISSUE THREAD

**Issue by CofeeSap** [megous/megatools#348]
Creating folder with slash:

    megamkdir /Root/newfolder
    ERROR: Can't create directory /Root/newfolder: Can't create toplevel dir: /newfolder

Creating folder without slash:

    megamkdir Root/newfolder
    ERROR: Can't create directory Root/newfolder: Parent directory doesn't exist: .

But after manually creating etc folder in mega.nz megacopy can create subfolders and managed to upload almost everything in /etc folder:

    megacopy  --local /etc --remote /Root/etc

**Comment by megous** [comment]
For your first example, you can not be passing /Root/newfolder for that error message to be printed. You're passing /newfolder, which is incorrect.

Please read `man megatools` _Remote filesystem_ section.
