### ISSUE TITLE
0 upload speed

### ISSUE THREAD

**Issue by Synyster1992** [megous/megatools#349]
i tried to upload a simple mp3 as a test and the upload will say 29 bytes/s then go straight 0 and hang on this C:\Users\Syn\Desktop\megatools-1.9.98-win32>megaput -u USER NAME -P 1235151
 C:\Users\syn\Desktop\FallingDown.mp3 megals /root
FallingDown.mp3: 2.40% - 64.0 KiB (65536 bytes) of 2.6 MiB (0 bytes/s))

**Comment by megous** [comment]
Perhaps mega.nz is a bit overloaded atm? Was upload from their website also slow at the time?

**Comment by Synyster1992** [comment]
i just checked the mp3 uploaded just fine thought the site

**Comment by megous** [comment]
You probably need to read through the docs a bit more. Also remote file/directory names are case sensitive, so you must use /Root, not just /root.

Error looks like you're trying to upload megals file, which doesn't exist.

Docs: https://megatools.megous.com/man/megatools.html

**Comment by megous** [comment]
The other error looks like `syn` is already uploaded. Megatools will not overwrite files.

**Comment by Synyster1992** [comment]
thanks for the help ill keep at and keep up the good work its a use full tool to have
