### ISSUE TITLE
Function not implemented error with megafs

### ISSUE THREAD

**Issue by richardbrinkman** [megous/megatools#35]
Mounting my mega.co.nz account to a local directory does not work as expected. The megafs command itself succeeds and I can use "ls" and "cd" to navigate the directories. However, every other file operation (like "mv", "cp", "less", etc) results in a "Function not implemented" error, making the megafs utility rather useless.

Steps to reproduce:
1. wget http://megatools.megous.com/builds/megatools-1.9.91-fedora-x86_64.tar.gz
2. tar xfz megatools-1.9.91-fedora-x86_64.tar.gz
3. mkdir account
4. usr/local/bin/megafs -u my.email@address.com -p mypassword account
5. cd account/Root
6. echo Test > test.txt

output:
bash: test.txt: Function not implemented

**Comment by megous** [comment]
Megafs support was dropped.
