### ISSUE TITLE
Help with Custom Megatools Script

### ISSUE THREAD

**Issue by Jimmy03** [megous/megatools#350]
I made the following script which makes megatools easier to use:

```
@echo off

SETLOCAL ENABLEDELAYEDEXPANSION

:start:

megals --reload /Root/

set /p var1="enter folder name: " & megals /Root/var1

for /f "tokens=1,* delims=:" %%A in ('megals -n /Root/!var1! ^|findstr
/n "." ') do (
set Link[%%A]=%%B
Echo %%A %%B
)

for /f "tokens=1,* delims=:" %%A in ('megals -n -e /Root/!var1! ^|findstr
/n "." ') do (
set Link[%%A]=%%B
)

set /p choice="Select Number for download: "
Call Set Link=%%Link[%choice%]%%

set "trimmedlink="
for %%h in (!Link!) do if not defined trimmedlink set "trimmedlink=%%h"
echo !trimmedlink! 
Megadl !trimmedlink! && goto :start:

ENDLOCAL


pause
```

But it's removing the exclamation mark from the link in !trimmedlink!

This code echos the trimmedlink link like this: https://mega.nz/#***********************
But It should echo it like: https://mega.nz/#!**********************

So the code is somehow removing the ! from the link url

This is a problem with using Delayed Expansion, but I need to use the Delayed Expansion to deal with Parentheses in filenames. If I don't use Delayed expansion then any filenames with parentheses will cause a crash.  So File1 will work, but File(1) will cause a crash.

Can you try out this batch file, and see what I mean?

**Comment by megous** [comment]
Sorry, my bat scripting skills are very 1998. I'll not be able to help, but I'll leave this open if someone else has something to say.

**Comment by Jimmy03** [comment]
This should be working now, paste in notepad and save as .bat
It lets you select a file by number instead of having to enter the link

```
@echo off

:start:


megals --reload /Root/

set /p var1="dir? " & megals /Root/%%var1%%

for /f "tokens=1,* delims=:" %%A in ('megals -n /Root/%%var1%% ^|findstr
/n "." ') do (
set Link[%%A]=%%B
Echo %%A %%B
)

setlocal DisABLEDELAYEDEXPANSION

set /a c=0

FOR /F "tokens=1 usebackq" %%i in (`megals -n -e /Root/%%var1%%`) do (
    set /a c+=1
    call set "string[%%c%%]=%%i"
)

set /P number="Enter number: "

FOR /F "tokens=*" %%g IN ('call echo %%string[%number%]%%') do (SET VAR2=%%g)
echo %Var2%
echo.

Megadl %VAR2% & echo. && goto :start:

pause
```
