### ISSUE TITLE
Downloads "Disappearing"

### ISSUE THREAD

**Issue by ferminschlottmann** [megous/megatools#351]
Hi,
I'll try to explain my problem the best i can, but i find a bit hard to choose the correct words.
Basically, every time i download somethin using megadl i can see the progress and everything in the cmd, but the files are not downloaded to the directory i chose. In fact, i cannot find them anywhere. Its like, they werent even downloaded. It's weird because everything worked perfectly last week.

Im on ubuntu 17.04, if its useful to note.

Thanks in advance

Update: I found them, but the files are downloaded to the root of my system, i dont know why...

**Comment by megous** [comment]
Hi, what version of megatools do you use?

**Comment by ferminschlottmann** [comment]
Latest on a 32 bit machine

**Comment by megous** [comment]
There are multiple definitions of latest though. :) Your own build from the master branch? Or latest from the distribution, in that case which version is there?

**Comment by megous** [comment]
Files are downloaded to the current working directory. I guess that depends on how you invoke the tools.
