### ISSUE TITLE
crontab: command not found

### ISSUE THREAD

**Issue by kidkami** [megous/megatools#352]
Hi,

I followed this tutorial here: http://www.matteomattei.com/backup-your-server-on-mega-co-nz-using-megatools/
and it works for a while, but since I moved my server to a newer one the script doesn't worked anymore?

Output from crontab says:
/root/megabackup.sh: line 50: megals: command not found
/root/megabackup.sh: line 50: megamkdir: command not found
/root/megabackup.sh: line 53: megals: command not found
/root/megabackup.sh: line 64: megacopy: command not found

on terminal everything works well and I'm using the latest version

**Comment by megous** [comment]
Check your PATH environment variable you're using in cron. It might not contain path to where megatools are installed. You can add it to crontab (see man crontab) or set it in megabackup.sh.

**Comment by kidkami** [comment]
Thank you!

**Comment by abazad** [comment]
you can use "full path"

example:
/usr/local/bin/megacopy

i have solved my proplem like this.
