### ISSUE TITLE
megaput error for "large" file

### ISSUE THREAD

**Issue by jcd717** [megous/megatools#354]
when the file to upload is at least 4G, there is an error message like this:
Data upload failed: Server returned 413
or
Data upload failed: CURL error: Failed sending data to the peer

via the web site, the upload works

**Comment by megous** [comment]
Website does multiple POSTs with smaller chunks of the data. Megatools does upload in one big POST. It looks like mega.nz doesn't support uploading more than 4GiB in a single POST.
Or perhaps Content-Length is garbled. Master branch has --debug http I believe. Can you please try uploading your big file with that to see what headers are sent for the data request. In particular if content-length and ranges look reasonable?

**Comment by jcd717** [comment]
thanks for the tip, I found:
```

Accept: */*
Accept-Encoding: deflate, gzip
User-Agent: Megatools (1.9.98)
Referer: https://mega.nz/
Content-Type: application/octet-stream
Content-Length: 5368709120

< HTTP/1.1 413 ( Request failed because the size of the request body is too large.  )
< Via: 1.1 SRV-S-TMG
```


so it's because of the firewall "srv-s-tmg", without it, works very well

**Comment by megous** [comment]
Ahh, interesting! Good the proxy advertises itself.
