### ISSUE TITLE
New Project (mega scripts) has been created to simplify and Automation using of megatools

### ISSUE THREAD

**Issue by Amourspirit** [megous/megatools#356]
I have created a new open source project [mega_scripts](https://github.com/Amourspirit/mega_scripts)
That were born out of my own needs to automate database backups.
These script will be added to as time goes on to include other automated features.
The Help docs can be found [here](https://amourspirit.github.io/mega_scripts/).

**Comment by megous** [comment]
Nice, I've added a link to your project to the README. If you'll find something irksome about megatools, let me know. I don't mind adding improvements that would help the use of megatools in scripts.

**Comment by Amourspirit** [comment]
Thanks, I could not ask for more.
