### ISSUE TITLE
server returned 509

### ISSUE THREAD

**Issue by redbarrol** [megous/megatools#357]
I use this comand to download these files:
megadl --username 's@hotmail.com' --password 't******y'  'https://mega.nz/#F!0zglDQBD!-CwoWgrYcvurqL2BY6074w'

and  get this:
F /home/punch/Downloads/Windows 10 PRO_X64_1803_Spanish(Mexico).part07.rar
ERROR: Download failed for /2/Windows 10 PRO_X64_1803_Spanish(Mexico).part07.rar: Data download failed: Server returned 509
F /home/punch/Downloads/Windows 10 PRO_X64_1803_Spanish(Mexico).part08.rar
ERROR: Download failed for /2/Windows 10 PRO_X64_1803_Spanish(Mexico).part08.rar: Data download failed: Server returned 509
F /home/punch/Downloads/Windows 10 PRO_X64_1803_Spanish(Mexico).part06.rar
ERROR: Download failed for /2/Windows 10 PRO_X64_1803_Spanish(Mexico).part06.rar: Data download failed: Server returned 509
F /home/punch/Downloads/Windows 10 PRO_X64_1803_Spanish(Mexico).part10.rar
ERROR: Download failed for /2/Windows 10 PRO_X64_1803_Spanish(Mexico).part10.rar: Data download failed: Server returned 509
F /home/punch/Downloads/Windows 10 PRO_X64_1803_Spanish(Mexico).part09.rar
ERROR: Download failed for /2/Windows 10 PRO_X64_1803_Spanish(Mexico).part09.rar: Data download failed: Server returned 509

What I can do?

**Comment by megous** [comment]
You're out of download quota.

**Comment by mirh** [comment]
Web interface lets you download anyway even in that situation (you might get your download stopped afterwards though). 
This is not allowed here instead.

**Comment by megous** [comment]
What do you suggest?

**Comment by mirh** [comment]
At least the first time error 509 appears, it's not "definitive". 
Not sure how the thing is arranged on the website, but as I said it's not a hard block.

**Comment by megous** [comment]
https://github.com/megous/megatools/blob/master/lib/mega.c#L4410

Megatools retries the chunk download for 640 minutes every 4 minutes for all errors, including 509 error. Original reporter was using older megatools version, where the download handling was different. I'd suggest that you try the latest experimental version if you haven't already, to test your hypothesis.

**Comment by mirh** [comment]
I'm talking about this. 
![](https://user-images.githubusercontent.com/9366725/47749076-9cdc1000-dc8c-11e8-98c3-7267935b22a1.png)

I am not doubting the program being correct over the fact I'm over quota (thus justifying the error 509). 
I'm saying that \*even then\* download is **still** *actually* possible. 
(you might get completely limited after some hundred of megabytes, but still, this choice is not left in megatools)

**Comment by megous** [comment]
Sure, that may be because megatools is requesting 256MiB sized chunks, so if you have 250 MiB left for example, the request will fail. mega.nz website is requesting 1MiB chunks, so it can exhaust the rest.

I can try reducing the chunk size after the first 509 error. That will slow down the transfer considerably, but it will allow to use the last ~128MiB of quota (on average). It doesn't seem that important, considering that the quota is like 5GiB? So this is 2% or so.

**Comment by mirh** [comment]
Uh.. But what if I just have to download a 20MB file (cannot test myself this now, since I got the limit restored)?

Or are you saying the warning (and error 509) appears when your remaining quota wouldn't be enough to *complete the download at once*?

**Comment by megous** [comment]
Nohing, megatools will request the size of a file. This is only relevant for big files.

**Comment by megous** [comment]
Anyway, you should be able to download smaller files already, while being close to the quota limit.
