### ISSUE TITLE
Is megatools project alive?

### ISSUE THREAD

**Issue by caspertone2003** [megous/megatools#358]
Hi,
Last release has already two years and there are more items changing in mega that imply elements of megatools stopping to work...
I appreciate the tool, while I am unable to contribute I believe is fair play to know as user if this project is dead or a realease will be issued sometime... and yes, I am unable to compile my private version...
TIA

**Comment by megous** [comment]
Hi,
it would help if you stated what exactly doesn't work, or what mega.nz API changes are causing the breakage. Megatools is being maintained, and I'm accepting contributions in any form.
Release can happen at any time enough changes accumulate. BTW, you don't need to compile your private version if you're on windows, the latest pre-release version is available on the offficial website. (1.9.99git)

    https://megatools.megous.com/builds/

**Comment by megous** [comment]
I'll close this. You can reopen it if you have more concerns, or want to contribute with actual bug reports.

**Comment by caspertone2003** [comment]
I just wanted to thank you for pointing me to builds.
I only had eyes for https://github.com/megous/megatools/releases where last one is 1.9.8 pre from 2016.
I had read meny issues (like proxies do not work...; megareg stopped working; ...) but I was not aware of those other builds.
Thanks again!
CT
