### ISSUE TITLE
Wrong comment syntax in megarc manpage

### ISSUE THREAD

**Issue by bertogg** [megous/megatools#359]
The example given in the megarc(5) manpage uses semicolons for comments:

```
[Network]
; 1MiB/s
SpeedLimit = 1024
; Use over TOR
Proxy = socks5://127.0.0.1:9050
```

This is however invalid syntax and the file can't be parsed correctly. Using '#' instead would solve the problem.

**Comment by megous** [comment]
Thank you for the report. Fixed.
