### ISSUE TITLE
Build in alpine

### ISSUE THREAD

**Issue by ruby232** [megous/megatools#361]
I tried build in alpine, but not find documentation, after many search and failures i did it. 

1. Download source code.

2. Crete docker-compose.yml in folder with source code.
```
	version: "3.2"
	services:
	  build:
	    image: alpine:3.6
	    volumes:
	      - ./:/var/app
	    working_dir: /var/app
	    command: tail -f /etc/hosts
```

3.  Up docker and execute command in container 
```
docker-compose -d up build
docker-compose exec build sh
```

4. In container install dependencies 
```
apk add --update build-base libcurl curl-dev asciidoc openssl-dev glib-dev glib libtool automake autoconf
```
5. Build megatools
```
./configure
make
```

**Comment by megous** [comment]
Thnaks.
