### ISSUE TITLE
megaput 1.9.99git doesn't use full --path

### ISSUE THREAD

**Issue by MrGALL** [megous/megatools#364]
Last stable version of megaput used full --path option (including file name).
Example: megaput --path /Root/folder/uploaded.file /tmp/original.file
Result:  /Root/folder/uploaded.file

Current git version uses the folder but doesn't rename the file.
Example: megaput --path /Root/folder/uploaded.file /tmp/original.file
Result:  /Root/folder/original.file

**Comment by megous** [comment]
Thanks for noticing. Fixed.
