### ISSUE TITLE
duplicate line in megacopy manpage

### ISSUE THREAD

**Issue by albaldi** [megous/megatools#367]
https://github.com/megous/megatools/blob/fc8adce4eb01ea45373616f4992efcabdd0c8a9b/docs/megacopy.txt#L47

is present in 

https://github.com/megous/megatools/blob/fc8adce4eb01ea45373616f4992efcabdd0c8a9b/docs/upload-options.txt#L6

**Comment by megous** [comment]
Thanks! It was also in megaput manpage.
