### ISSUE TITLE
Build

### ISSUE THREAD

**Issue by SSoft7** [megous/megatools#371]
Hi,

I am getting build error on centos 7.5.
Tried on centos 6.9, Debian Wheezy etc.
I have also tried a different version of glibc but same error. Please Check below error log.
https://pastebin.com/1QGbuWT9

Please hint me what I am doing wrong, Thank you.

**Comment by megous** [comment]
Thank you. Should be fixed now.

**Comment by SSoft7** [comment]
thanks, but now i am getting another error https://pastebin.com/raw/wKA4cf3J

**Comment by artifexor** [comment]
try to compile with -std=c99 which enable the requested C99 mode. might breaks other though...

**Comment by SSoft7** [comment]
Hi, while I am trying to compile on centos 6, I get https://pastebin.com/GxPnEi93
I guess its code related error?

(actually, I want to use it on both a machine of centos 6 and 7, I thought of using the compiled binary of centos 7 on centos 6 which did not work. :-( )

**Comment by megous** [comment]
Centos libcurl is too old. You can add some version dependent ifdefs around the keepalive options that are not supported by your libcurl version. Some are there already, so it should not be that hard.

**Comment by megous** [comment]
You just need too figure out since what version are those options mentioned in the error report supported in libcurl.

**Comment by SSoft7** [comment]
Ok, I have just built latest libcurl from source....
first, try - c99 error
after configuring with c99 flag I get this -   https://pastebin.com/raw/90qQG2xi

I don't any experience with C .so I am unable to fix these myself :-(
it would be nice if you decide to distribute static binaries in future since its hard for many people to troubleshoot this build issues which have dozens of dependencies.

**Comment by megous** [comment]
If you want to use current software on 8 year old systems you should be prepared for trouble and can't really expect much handholding.

Also megatools has 2-3 dependencies that might be an issue on ancient systems. Not dozens. So even if you use ancient system, you can just build the 3 packages (glib2, libcurl and perhaps openssl 1.0 or 1.1) in their current versions yourself into a HOME dir, and run it from there with some LD_LIBRARY_PATH or whatever.

I don't know what C compiler you're using so it might be so old it has incomplete support for compound literals, or it's that you're using -std=c99 vs the recommended -std=gnu99 or newer option. I don't know.

BTW, you can do a static build yourself on a newer system, too. I'd be fine with distributnig your static build script in the contrib directory. Perhaps something musl based. Might be useful for others in your situation too.

**Comment by SSoft7** [comment]
Ok, I have finally got it working. this might help others so I am posting.

OS: Centos 6.10
Steps:
1. Installed GCC 5.1.0 from source with default configure option. (you need to have GCC installed by yum first. Centos 6/7 have GCC 4.x which won't work properly. )
2. Compile Openssl 1.0.2 , glib 2.43.92 , libcurl 7.61 from sources with --prefix=/opt  (prefix can be any other nonstandard path )
3.  ```
export LD_LIBRARY_PATH=/opt/lib/
    export PKG_CONFIG_PATH=/opt/lib/pkgconfig
```

4. now you can build megatools as usual.

Note: Other version combination may work/may not.

@megous I don't have much experience with building binaries so I don't know a proper way making build script. it would be nice if you can point me some resources for all these building stuff.

Thanks.

**Comment by megous** [comment]
If you want a completely static build, you can try building musl C library. It has a wrapper for gcc, which you can use by setting CC variable, prior to building all the packages:

   export CC=musl-gcc

After that you can repeat your steps above and just pass --enable-static --disable-shared to configure everywhere.

Also to not mix in stuff from the base system accidentally, you should use PKG_CONFIG_LIBDIR instead of PKG_CONFIG_PATH.

https://www.musl-libc.org/

Musl should be installable via standard means, so you should not need to build it.

**Comment by megous** [comment]
Just build everything into /opt/static/ prefix or something like that. That should produce a set of protable static binaries in the end.

**Comment by megous** [comment]
@SSoft7 https://megatools.megous.com/builds/experimental/

**Comment by megous** [comment]
These are experimental static binraies, you can test them on your old systems if you like.

**Comment by SSoft7** [comment]
@megous Thank a lot for this, I hope you can release static builds for major upgrades (at least).
It is working fine on my system (tested upload, download & link export).
is it made by musl-cc ?

**Comment by megous** [comment]
It's made by https://github.com/richfelker/musl-cross-make/ toolchain and a re-build of all dependencies completely isolated from the host system. musl-cc is a bit hackish and doesn't work well recently and also depends on the current state of my Arch Linux installation. So it can break any time.

Nice thing is that the build should now work anytime, regardless of the current state of my linux distro, so I can set up some script to push the builds of the master branch fairly regularly.

The build pipeline is now also almost identical for windows, linuxes, etc. It all works very well.

The only downside (or is it?) of static builds is that they're not localized. But even the regular build is localized only partially, so...

**Comment by megous** [comment]
What kernel version do you use? It would be nice to know, because static binaries can fail if some syscall that was added only recently is used somehwere deep down. So it would be good to know what oldest version of the kernel it was tested on.

**Comment by SSoft7** [comment]
Centos 6.10 and Kernel version is 2.6.32-754.2.1.el6.x86_64 .
Also, it works on an android phone too (did not test upload but I get the help output)

**Comment by megous** [comment]
Ha, that's quite old :) Good!
