### ISSUE TITLE
Megaput sticks at %100 with transfer speed of 0 bytes per second 

### ISSUE THREAD

**Issue by nate2014jatc** [megous/megatools#373]
Trying to push files from my Linux server to my MEGA, and it has been failing like this recently
I've reached out to MEGA support as well

![sketch](https://user-images.githubusercontent.com/11836893/43112204-25def012-8eb2-11e8-98c7-6d5abd38787e.png)

**Comment by megous** [comment]
Which version?

**Comment by nate2014jatc** [comment]
Version 1.9.98
The latest version available on Ubuntu 18.04 LTS

**Comment by megous** [comment]
Ok, please look at recently closed issues first. Fixedin 1.10.0.
