### ISSUE TITLE
Peer certificate cannot be authenticated

### ISSUE THREAD

**Issue by M3T4LL1C4** [megous/megatools#374]
**Describe the bug**
megadl 1.10.00 for windows 32 bits doesnt't work. 1.9.98 version works

**To Reproduce**
megadl https://mega.nz/#!*******
ERROR: Can't login to mega.nz: API call 'us' failed: HTTP POST failed: CURL error: Peer certificate cannot be authenticated with given CA certificates

**Environment:**
 - windows 7 32 bits
 - megatools 1.10.00 win32

**Comment by megous** [comment]
Please run with --debug http and provide ouput.

**Comment by M3T4LL1C4** [comment]
*   Trying 31.216.147.134...
* TCP_NODELAY set
* Connected to g.api.mega.co.nz (31.216.147.134) port 443 (#0)
* ALPN, offering http/1.1
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
ERROR: Can't login to mega.nz: API call 'us' failed: HTTP POST failed: CURL error: Peer certificate cannot be authenticated with given CA certificates

**Comment by megous** [comment]
Got it. For whatever reason, new libcurl got build with two SSL backends (windows and openssl) at once, and openssl gets priority. Previously it used just windows ssl.

Re-uploaded updated builds.

**Comment by M3T4LL1C4** [comment]
I confirm it works now.
Thanks for the fix.
