### ISSUE TITLE
Server returned error code -4 (EFAILED)

### ISSUE THREAD

**Issue by Pinhcy** [megous/megatools#375]
**Describe the bug**
Uploading a directory returns the following error `Server returned error code -4 (EFAILED)` 
The error is consistent enough more than 5 times before you get a successful upload. 

**To Reproduce**
Following command is used 
megacopy --local PATH/"DIR" --remote /Root

**Expected behavior**
Successful upload with error or at least a successful upload after once or twice and not an inconsistent 5 failed retires one time and 9 failed retries the next time.

**Environment:**
 - Debian 9.4 
 - megatools 1.10.0

**Comment by Pinhcy** [comment]
Particular directory I was just now uploading which was 25GB in size took 4 tries.

1st:  Failed at 46% - Failed Data upload failed: Upload transfer failed: Server returned error code -4 (EFAILED)

2nd: Failed at 48% - FailedData upload failed: Upload transfer failed: Server returned error code -4 (EFAILED)

3rd: Failed at 26% - FailedData upload failed: Upload transfer failed: Server returned error code -4 (EFAILED)

4th:  100% - Success

**Comment by megous** [comment]
There's nothing I can do. You can reduce ParallelTransfers to 1 or 2, to reduce these errors.

**Comment by megous** [comment]
To be precise, it's an issue with mega's server(s). Client is uploading data correctly, mega just decides to return error -4 on one of the chunks, and refuses further transfers from then on. You can complain to mega.nz.

**Comment by hluaces** [comment]
We've been struggling with this for a while. Is it know why Mega returns a -4 error? is it arbitrary or does it have a reasoning behind it?

**Comment by megous** [comment]
It seems to happen [more often] if I don't upload the original sized chunks like in the algorithm for chunked CBC-MAC. 128 kiB 256kiB .... 1MiB 1MiB ....

They have some kind of boost mode in their web client, that uploaded differnt sized chunks, but disabled it as a hotfix shortly after introduction.

I guess there's some issue with their server infrastructure.

**Comment by megous** [comment]
Anyway, if you have more details, like when it happens, what size of the files is, if it's shortly after the start or later during the upload, etc. It might be useful to collect that information and notify them.

**Comment by hluaces** [comment]
Hey Megous. 

- It happens arbitrarily. Some times at 0.0x% upload progress the error triggers, sometimes it triggers at 100%.
- The file which is currently causing trouble is ~15GB. Smaller files seem to work OK.
- On 10.1 an error ERATELIMIT was given. There's no ratelimit on our account side.
- After upgrading to 10.2 the error switched to -4 (EFAILED). I guess this was some commit that I might have missed.
- ParallelTransfers on 1 didn't help.

This indeed seems to be something mega-related as this was working perfectly fine for a while, although trying to use another tool (rclone) to accomplish the same upload seems to work fine.

Thanks for your work and answer. I'll monitor this and see how it evolves.

**Comment by megous** [comment]
Mega has different error codes for upload server and api server. (probably, there's no detailed docs I could find) Megatools previously incorrectly used -4 ERATELIMIT api server error, where -4 means EFAILED when talking to upload server.

I'll look at rclone if it's doing something different.
