### ISSUE TITLE
Installing on CentOS

### ISSUE THREAD

**Issue by lukapaunovic** [megous/megatools#384]
IN order to run `./autogen.sh --prefix=$HOME/.local --disable-docs`
I needed to install, besides the packages you mentioned (`yum -y install gcc make glib2-devel libcurl-devel openssl-devel`).

`yum install autoconf automake libtool`

Just think this should be added to the manual

**Comment by lukapaunovic** [comment]
```
Run make now.

NOTE: On FreeBSD, you need to use GNU make (gmake)

[root@charles megatools-1.10.2]# make
  CC       lib/sjson.gen.o
  CC       lib/http.o
lib/http.c: In function ‘http_init’:
lib/http.c:67:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (int i = 0; i < G_N_ELEMENTS(http_locks); i++)
   ^
lib/http.c:67:3: note: use option -std=c99 or -std=gnu99 to compile your code
lib/http.c: In function ‘http_cleanup’:
lib/http.c:85:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (int i = 0; i < G_N_ELEMENTS(http_locks); i++)
   ^
make[1]: *** [lib/http.o] Error 1
make: *** [all] Error 2

```

**Comment by megous** [comment]
Thanks for the report, but most of it is already  addressed in the readme.

See:

> lib/http.c:67:3: note: use option -std=c99 or -std=gnu99 to compile your code

you need CFLAGS="-std=gnu99" before configure because your gcc is probably too ancient

> yum -y install gcc make glib2-devel libcurl-devel openssl-devel

https://github.com/megous/megatools/blob/master/README#L155

> IN order to run ./autogen.sh --prefix=$HOME/.local --disable-docs

https://github.com/megous/megatools/blob/master/README#L136

**Comment by lukapaunovic** [comment]
Thanks for the info. 
But i just want to state CentOS is not old :dagger:
Especially Centos 7.4
I love RHEL <3

**Comment by megous** [comment]
I don't know about CentOS, but gcc is old. -std=gnu11 or later should be default since gcc 5. So gcc there is at least 4 major releases of gcc behind. ;)
