### ISSUE TITLE
'megasync' command doesn't work for DL/UP folders

### ISSUE THREAD

**Issue by cirojr82** [megous/megatools#390]
Hello everybody.

Finally I get megatools working on my raspberry pi. I'm using megatools-1.10.2 version.

I can download single files via 'megaget' and 'megadl' commands.

But when I try to use 'megasync' command to download a entire folder, I get this message: │-bash: megasync: command not found

Am I missing something here, maybe someone could help me! Thanks!

**Comment by megous** [comment]
megasync was renamed to megacopy.
