### ISSUE TITLE
How to download multiple files in one line and put them to queue

### ISSUE THREAD

**Issue by tonyyang924** [megous/megatools#395]
The `megatools` is amazing that make me surprise to do these thing in command line

But I have a critical question that is how can I to download multiple files in one line and put them to queue?

Its just like `MegaDownloader app` that can put them in queue (even download multiple files at the same time)

I'm currently only download one files at one line
`
megadl https://mega.co.nz/\#\!XXXXXXXX
`
Is there any way to achieve this?  thanks you!

**Comment by megous** [comment]
That, and you should be able to just pass multiple links to megadl directly.

If you want parallel download, you can use xargs with a -P flag. For download it will work. For upload it's not a good idea, sice megaput is already uploading parts of the file in parallel.

**Comment by tonyyang924** [comment]
@mdirik thanks! i thought it works!
@megous if I used xargs with a -P flag, can I limited the maximum number of simultaneous downloads?

**Comment by megous** [comment]
Read:

    man xargs

For example 3 downloads:

  xargs -n1 -P3 megadl

**Comment by tonyyang924** [comment]
@megous thx~ I got it 👍
