### ISSUE TITLE
DNS Issues with v1.11.0-git-20180902 (EFAILED error)

### ISSUE THREAD

**Issue by blue240** [megous/megatools#398]
**Describe the bug**
When uploading a folder with megatools, other devices on the LAN cannot access the internet (browser reports that the DNS is down). When an upload is not taking place on another computer, internet for all LAN devices works perfectly. The EFAILED and DNS errors only happen after a certain amount of time has been spent uploading; approximately an hour.

**To Reproduce**
`megatools copy --local C:\Test --remote /Root/Test`

**Expected behavior**
Folder to upload without errors at max speed; other devices on LAN to have internet access while an upload is taking place.

**Environment:**
 - Windows 10.0.17134.286
 - **1.11.0-git-20180902**

**Debug output**
`WARNING: chunk upload failed (Server returned error code -4 (EFAILED)), aborting transfer`
`WARNING: Mega upload failed (Upload transfer failed: Server returned error code -4 (EFAILED)), retrying transfer (0 retries left)`
`Data upload failed: Upload transfer failed: Chunk upload failed: CURL error: Couldn't resolve host name`

**Comment by blue240** [comment]
> Please reduce number of ParallelTransfers to 1 and check if the problem persists.
> 
> You may also try --debug http to see if megatools is not doing anything obviously weird.
> 
> Though I'm not sure why would DNS resolver fail while megatools is running.

Setting ParallelTransfers to 1 works but is very slow (2 MB/s while max is 14 MB/s). This is a recent issue because before, I was able to upload with no problem with both 1.11.0-git-20180814 and 1.11.0-git-20180902

**Comment by megous** [comment]
So maybe it's something to do with your network? DNS resolve should not be failing.

**Comment by blue240** [comment]
> So maybe it's something to do with your network? DNS resolve should not be failing.

Thanks for all your help, it seems setting ParallelTransfers to 7 solved everything; I still get max speed without LAN errors.
