### ISSUE TITLE
Fails to build on Alpine (docker) - missing documentation dependency

### ISSUE THREAD

**Issue by voltagex** [megous/megatools#399]
**Describe the bug**
megatools fails to build, even when configure seems to succeed.

``
make[1]: *** No rule to make target 'docs/megatools.1', needed by 'all-am'.  Stop.
``

nb: why has --disable-docs (or --without-docs) been removed?

It seems like autoconf isn't picking up the required docbook-xml (?) dependency.

**To Reproduce**
Try to build the following Docker container (or replicate similar commands on your distro)

```
FROM alpine
RUN apk add --update git alpine-sdk
RUN apk add automake autoconf libtool file
RUN apk add openssl-dev curl-dev glib-dev
RUN mkdir /src
WORKDIR /src
RUN git clone --depth=1 https://github.com/megous/megatools
WORKDIR /src/megatools
RUN ./autogen.sh --disable-shared --enable-static
RUN make -j8
```

**Expected behavior**
A megatools binary is built

**Environment:**
 - OS and version: Alpine 3.6 via Docker
 - **Megatools version**: 
26a7a0d4bc7481de03436c676c47ecf0a1aedca0

**Debug output** (if appropriate)
 - Provide debug output by running the tool with --debug http,api
 - Sanitize it (remove session IDs, whatever other private info you want removed, etc.), or send it directly to megous@megous.com to avoid github.com. Most of the output is safe to be posted, except for session ids. Anyone can delete all your files, or cause some other mess just by knowing the session id.
 - Most of the debug output is already encrypted and useless on its own, without knowing the password. Alternatively, use an empty test account for debugging.

**Self help**
 - If it is a build issue, review the README file carefully, before submitting a bug report.
 - Did you donwload code from git (this is an unsupported build method, unless you want to contribute your code), or did you use a source code release tarball from https://megatools.megous.com?
 - If error seems transient (error 509, ERATELIMIT, ...), wait a bit and retry the command, before reporting issues.
 - Run megatools with --debug http,api and check if anything seems out of place (for CURL errors, certificate errors, API errors (EXXXXX), etc.)
 - Look through [recently closed issues](https://github.com/megous/megatools/issues?q=is%3Aissue+is%3Aclosed)
 - For compilation errors, if you're running an esoteric/old platform/OS, try to fix the error yourself and send the patch.

**Comment by megous** [comment]
https://github.com/megous/megatools/blob/master/README#L206

**Comment by voltagex** [comment]
Okay, fair enough.
