### ISSUE TITLE
Can we build without docs?

### ISSUE THREAD

**Issue by bparker06** [megous/megatools#400]
Having to install >1GB of dependencies for asciidoc just to build docs I will never read, seems a bit pointless.

Can we have an option disable the need to build docs?

**Comment by megous** [comment]
Docs are prebuilt in the release tarball. You don't have to build anyhting.

Seems like you're building from git which is unsupported. So the solution is to either build by a suggested method from a release tarball, or patch the code yourself.

**Comment by megous** [comment]
Just a general note to everyone reading this. Git (or SCM) code is only for developers to prepare the release source tarball, which is meant to be easy to build everywhere without too much dependencies. That's how it alway was in the GNU/Linux world with autotools build system. I don't get why everyone and their cat wants to build from git themselves these days, even if the experimental release tarballs are available for download.

**Comment by megous** [comment]
More infor here: https://github.com/megous/megatools/blob/master/README#L206
