### ISSUE TITLE
Sort order of downloads

### ISSUE THREAD

**Issue by RealDolos** [megous/megatools#401]
When megadl'ing  folder, it will download in "server order" (the order the server returns in API calls, which is not stable between successive calls, even).

This is a bit annoying, to be honest, Downloading in a stable sorted order would be appreciated.

I hacked something together, that goes like this:
```patch

+static gint sort_cmp(const struct mega_node *a, const struct mega_node *b)
+{
+       return g_ascii_strcasecmp(a->name, b->name);
+}
 
 GSList *mega_session_get_node_chilren(struct mega_session *s, struct mega_node *node)
 {
 // ...
 		struct mega_node *child = i->data;
 
 		if (child->parent_handle && !strcmp(child->parent_handle, node->handle))
-			list = g_slist_prepend(list, child);
+			list = g_slist_insert_sorted(list, child, (GCompareFunc)sort_cmp);
 	}
 
-	return g_slist_reverse(list);
+	return list;
 }
```

Right now, my code is too messy with all kinds of unorganized, unrelated tweaks, so no real patch, but you get the gist of it. 
`g_ascii_strcasecmp` isn't the best function to use either, but works reasonably well for what I do.
`g_slist_insert_sorted` isn't great either, complexity wise, but given that mega folders usually are just a couple of tens of thousands entries at most, this shouldn't really be an issue in practice.

**Comment by megous** [comment]
Thanks for the idea. Server returns UTF-8 strings, so it's better to use g_utf8_collate. It has the same interface as g_ascii_strcasecmp, so it will be an easy swap.

**Comment by RealDolos** [comment]
not well-versed in glib, so, yeah, that should be better.
Even better, according to docs, would be `g_utf8_collate_key_for_filename ()` I guess.
