### ISSUE TITLE
Hardcoded colors affects readability

### ISSUE THREAD

**Issue by N46AN** [megous/megatools#404]
See lib/tools.c, the colors seem to be hardcoded. 

For example, filename seems to be displayed in "ESC_WHITE", which is defined as "\x1b[37;1m"

This causes the filename to be completely invisible in white-backgrounded terminals, such as the default color scheme in gnome-terminal, or the built-in color scheme "Black on White" in xfce4-terminal.

It is not because of some fancy color schemes, the problem can be observed in the default configuration of regular desktop environments such as GNOME/gnome-terminal.

**Comment by megous** [comment]
Even if it was a fancy color scheme, this is a good reason to disable colors by default.
