### ISSUE TITLE
Remove files older than or support for wildcard

### ISSUE THREAD

**Issue by gmstam** [megous/megatools#407]
**Describe the bug**
I'm looking for a solution to remove older files. I read two previous issues #342 and #344 
but all the solutions don't work anymore.

**To Reproduce**
Here it is my script which found correctly the files of August 2018 (I exclude the first 9 characters because are always the same and I want filter only by month-year):
megals -h /Root/[path-to-my-folder] | grep -o -P '.{0,10}08-2018.*' | xargs -d\n megarm

I think there is something wrong with xargs. Someone can help, please?

**Expected behavior**
Remove all the files I found with grep. 

**Environment:**
 - OS and version: Debian 8 64bit
 - **Megatools version**: 1.10.2

**Debug output** (if appropriate)
 ERROR: Can't remove [first-filename-in-the-list]
[here the correct list]
: File not found: [first-filename-in-the-list]
[here the correct list another time]

**Comment by megous** [comment]
Try \\n

**Comment by megous** [comment]
Also add -r.

**Comment by gmstam** [comment]
where? to xargs? If yes, it's not working...

**Comment by gmstam** [comment]
If I add \\n and -r to xargs I receive in output for each file:
ERROR: Can't remove [filename]: File not found: [filename]

**Comment by megous** [comment]
That means xargs works.

With -d\n it splits output on 'n' for me. 

-d'\n' also works for me to split on new line.

**Comment by megous** [comment]
You can also use -0 for megals and -z for grep and -0 for xargs, to not have to mess with newlines escaping in shell. But it sounds like the files are already removed.

**Comment by gmstam** [comment]
It's working as you suggested (remove all files of August 2018):
megals -0 -h [my-path] | grep -z -P '.{0,10}08-2018.*' | xargs -0 megarm
Working also with --reload for megals.
