### ISSUE TITLE
megatools is not working in Windows XP

### ISSUE THREAD

**Issue by c-sanchez** [megous/megatools#408]
Latest megatools builds is not working in Windows XP

List of missing functions according to **Dependency Walker**
using **megatools-1.11.0-git-20181004-win32.zip**

in **IPHLPAPI.DLL**
-- CancelMibChangeNotify2
-- GetIpForwardTable2
-- NotifyRouteChange2
-- if_nametoindex

in **KERNEL32.DLL**
-- AcquireSRWLockExclusive
-- AcquireSRWLockShared
-- GetFileInformationByHandleEx
-- GetFinalPathNameByHandleW
-- InitializeConditionVariable
-- InitializeSRWLock
-- ReleaseSRWLockExclusive
-- ReleaseSRWLockShared
-- SetThreadErrorMode
-- SleepConditionVariableSRW
-- TryAcquireSRWLockExclusive
-- TryAcquireSRWLockShared
-- WakeAllConditionVariable
-- WakeConditionVariable

in **WS2_32.DLL**
-- inet_ntop
-- inet_pton

**Comment by megous** [comment]
Thanks for the symbols list, very useful! I combed through the current glib2 code and these functions are called from there.

Looking at git history, WinXP compatibility was removed during 2.57.x dev cycle.

The only way to get it back would be to compile with old glib version.

**Comment by megous** [comment]
Try the new winxp build, that uses glib 2.54.3.

**Comment by c-sanchez** [comment]
Sorry but I can't found any winxp build in the experimental builds or release builds page.
Where is located?

**Comment by megous** [comment]
Sorry, I forgot to upload it. It's there now.

**Comment by c-sanchez** [comment]
Thank you very much megous, that build works perfectly :D
