### ISSUE TITLE
downloads from folder

### ISSUE THREAD

**Issue by c-sanchez** [megous/megatools#410]
Hi, I wonder how I can download files from an mega folder, ie I know I can download the complete folder, but how I can choose what files I want download, how to setup the download order.
I know also it's possible importing files from how mega account and then download this from there, but is possible directly from megatools without import anything?
I'm sorry by make the issue, is my doubt :P

**Comment by megous** [comment]
https://megatools.megous.com/man/megatools-dl.html

Look at the  --choose-files option.
