### ISSUE TITLE
ERROR: Can't login to mega.nz: API call 'us' failed: Server returned error ENOENT

### ISSUE THREAD

**Issue by AMONRA75** [megous/megatools#413]
hi,
i try to connect to mega.nz account but i see this error

ERROR: Can't login to mega.nz: API call 'us' failed: Server returned error ENOENT

this is the debug api result

`
C:\MMEGA\megatools>megals -e -l -u inferitest@protonmail.com -p password75 --deb
ug=api
-> [{
        "a": "us",
        "user": "inferitest@protonmail.com",
        "uh": "nrL3kuuzflM"
}]
<- [
        -8
]
ERROR: Can't login to mega.nz: API call 'us' failed: Server returned error EEXPI
RED

`
i use latest megatools version under windows 7 32bit
anyone help me???

best regards

**Comment by megous** [comment]
Hi, have you read this? https://github.com/megous/megatools/issues/411

Is this new account?

**Comment by RedGrinGrumbler** [comment]
I had the same issue from a linux machine. 
what was the fix?
Also, this is a new account in Mega

**Comment by seliver** [comment]
This was happening to me because I was adding "" around the password. Removing them appears to solve the problem. 

Side note: Be sure to escape special bash characters with an \ before the character as well.

**Comment by VD171** [comment]
This still happening.
Any solution?

**Comment by MosEisley34** [comment]
This started happening for me as well @VD171

**Comment by VD171** [comment]
May login using session solve this problem?
https://github.com/megous/megatools/issues/468

**Comment by ahmedmoselhi** [comment]
I still have the same problem
