### ISSUE TITLE
Please add support for new file links

### ISSUE THREAD

**Issue by mdirik** [megous/megatools#416]
**Describe the bug**

There is a new (to me?) feature that allows getting a shared link for a single file inside a shared folder:

![share](https://user-images.githubusercontent.com/1767147/48967812-39c56b00-eff7-11e8-92f0-ee261b5694aa.png)

![link](https://user-images.githubusercontent.com/1767147/48967900-99704600-eff8-11e8-829c-30f11ba6227b.png)

**To Reproduce**
`megadl` can't process such links:

```
$ megadl ......
WARNING: Skipping invalid Mega download link: ...........
```

**Expected behavior**
The file (and only that file, not other files in the same shared folder) should be downloaded

**Environment:**
 - OS and version: Debian 9
 - **Megatools version**: 1.11.0-git

**Comment by megous** [comment]
I guess, user still has access to the entire folder. It's just that the ui downloads the particular file specified after '?' in the url?
