### ISSUE TITLE
ERROR: Upload failed for ***: Invalid upload handle

### ISSUE THREAD

**Issue by vebmaster** [megous/megatools#419]
**Describe the bug**
When synchronizing the folder, the error "ERROR: Upload failed for ***. Sql.gz: Invalid upload handle" pops up.
The error does not always appear.

**To Reproduce**
megacopy --no-progress --local /tmp/site --remote /Root/site >> $LOG 2>&1

**Environment:**
 - Ubuntu 18.04.1 LTS
 - megatools/bionic,now 1.9.98-1build2 amd64

**Comment by megous** [comment]
Use the current version. 1.9.98 has comaptibility issues with recent mega.nz server changes.
