### ISSUE TITLE
Does megatools support OTP?

### ISSUE THREAD

**Issue by niheaven** [megous/megatools#422]
Hi,

Does megatools support mega.nz's OTP feature? Or maybe I must turn off OTP to use megatools?

**Comment by megous** [comment]
It does not.

**Comment by megous** [comment]
It does not support accounts created with a new registration method either. See: https://github.com/megous/megatools/issues/411

**Comment by niheaven** [comment]
Okay, it's just fine when I turn off TFA. btw, why are the commands name in the [online menual](https://megatools.megous.com/man/megatools.html) outdated, that make me confused at the first time.

**Comment by megous** [comment]
The latest version is 1.11.0-something. In this version megatools changed to use a single binary, instead of one for each command.
