### ISSUE TITLE
'megatools get', Output to STDOUT not working (--path="-")

### ISSUE THREAD

**Issue by sparomba** [megous/megatools#423]
**Describe the bug**
When using "-" as --path value, 'megatools get' and 'megaget' don't write anything to stdout. 

The debug log (I think) shows that megatools requests the file location on the remote server correctly. The tool itself is also busy for quite a while, so maybe it is downloading the file but not redirecting it to stdout properly?

Using "-" as --path value in 'megatools dl' and 'megadl' works fine, both write the file to stdout.

**To Reproduce**
does not work:
megatools get --ignore-config-file --username="+user+" --password="+pass+"  --path="-" "/Root/video.mp4"
megatools get --ignore-config-file --username="+user+" --password="+pass+"  --path="-" "/Root/video.mp4" > output.mp4

does work:
megatools get --ignore-config-file --username="+user+" --password="+pass+"  --path="output.mp4" "/Root/video.mp4"
megatools dl --ignore-config-file  --path="-" "+mega-share-link+"
megatools dl --ignore-config-file  --path="-" "+mega-share-link+" > output.mp4

**Environment:**
- tested on Debian 9.6(stable) and Debian 10(testing), x86_64
- Megatools version: 1.11.0-git-20181216 and 1.10.2

**Debug output**
[debug.txt](https://github.com/megous/megatools/files/2732073/debug.txt)  (--debug http,api)

**Comment by megous** [comment]
Thanks for the bugreport. Fixed.
