### ISSUE TITLE
ERROR: Can't login to mega.nz: API call 'us' failed: Server returned error EUNKNOWN

### ISSUE THREAD

**Issue by FrankSansC** [megous/megatools#424]
**Describe the bug**
Can't login

**To Reproduce**
megadf -u username@email.com -p password

**Expected behavior**
Login successfull

**Environment:**
 - OS and version: macOS
 - **Megatools version**: megatools 1.10.2

**Debug output** (if appropriate)
megadf -u username@email.com -p password
-> [{
	"a": "us",
	"user": "username@email.com",
	"uh": "XXXXXXXXX"
}]
<- [
	-26
]
ERROR: Can't login to mega.nz: API call 'us' failed: Server returned error EUNKNOWN

**Notes**
I have 2FA enabled
Account creation date: January 19, 2013

**Comment by megous** [comment]
2FA is not supported.
