### ISSUE TITLE
ERROR: Can't login to mega.nz: API call 'us' failed: Server returned error EEXPIRED

### ISSUE THREAD

**Issue by 1405040117** [megous/megatools#425]
Issue：ERROR: Can't login to mega.nz: API call 'us' failed: Server returned error EEXPIRED
megatools version：megatools 1.11.0-git-20190107
Operating system version：centos7 64bit
![image](https://user-images.githubusercontent.com/9691891/51368746-a195bf00-1b2b-11e9-9e75-211643f977f1.png)

**Comment by david-macharia** [comment]
what is the solution of this

**Comment by bsudhanva** [comment]
still not fixed even in the latest build
megatools-1.11.0-git-20200503-linux-x86_64
debug- -> [{
	"a": "us",
	"user": "voediv533@gmail.com",
	"uh": "Zz3eUNO0ZWw"
}]
<- [
	-8
]
ERROR: Can't login to mega.nz: API call 'us' failed: Server returned error EEXPIRED

**Comment by maltfield** [comment]
See also https://github.com/megous/megatools/issues/411
