### ISSUE TITLE
Procedure to empty trash

### ISSUE THREAD

**Issue by caspertone2003** [megous/megatools#429]

**Comment by megous** [comment]
Megatools will not login for each invocation of a command. There's no overhead.

There's no special command to remove the contents of the trash folder.

**Comment by caspertone2003** [comment]
@megous 
Thanks
In windows I tried
"megatools -rm /Trash" and I got a reply saying that I cannot delete /Trash
"megatools -rm /Trash/*" was also rejected
Is the only way to do

"megatools ls /Trash > file.txt" and then iterate (read line into %i from file.txt and do "megatools -rm /Trash/%i) ?

Thanks again

**Comment by megous** [comment]
Sorry, I don't know much about windows scripting. On Linux, you'd do:

    megatools ls -0 /Trash | xargs -0r megatools rm

That would be a safe way to empty the trash. It would take care of handling spaces in paths correctly, so that there's no chance of unintentionally removing things that shouldn't be removed.

**Comment by caspertone2003** [comment]
@megous 

> Sorry, I don't know much about windows scripting. On Linux, you'd do:
> megatools ls -0 /Trash | xargs -0r megatools rm
> ```

For those interested in a windows solution:

megatools ls /Trash -u user -p pass>List.txt
FOR /F "tokens=*" %%k in (List.txt) DO (
				megatools rm "%%k" -u user -p pass
)

This goes very slowly as deletes one file at a time...

**Comment by megous** [comment]
You can/should pass multiple paths to `megatools rm`. That should be somewhat faster. Here's xargs batch file that does that:

https://superuser.com/questions/652492/windows-equivalent-to-xargs#652510

**Comment by caspertone2003** [comment]
Pending to try xargs @ windows
a) The best I located (no dependencies) http://www.pirosa.co.uk/demo/wxargs/wxargs.html 
b) https://github.com/DoctorLai/BatchUtils/blob/master/xargs.cmd
