### ISSUE TITLE
Resume support to megaget

### ISSUE THREAD

**Issue by alfredoivan** [megous/megatools#431]
OS: Linux fsname 4.14.52-v7+ #1123 SMP Wed Jun 27 17:35:49 BST 2018 armv7l GNU/Linux
Using megatools-1.9.98

Similar to the resume support done to megadl, it would be a nice feature to be able to resume download from a megaget command.

At the moment, with an incomplete download, when trying to resume:
$ ./megaget /Root/filename.rar

ERROR: Download failed for '/Root/filename.rar': Local file already exists: ./filename.rar

**Comment by megous** [comment]
megaget already has resume support. You just have to use non-ancient version of megatools.

See the official website for the current versions.
