### ISSUE TITLE
megadl --choose-files fail to recognize many keys or keys combinations

### ISSUE THREAD

**Issue by Porkepix** [megous/megatools#433]
**Describe the bug**
`megadl --choose-files` fails to recognize many keys or keys combinations

**To Reproduce**
Run `megadl --choose-files` with a Mega directory. Once the prompt is here, type a few characters, then try to hit backspace, it's gonna fail. Same goes with arrow keys or other key combinations like ^u for example. Therefore it seems user can't correct what he typed.

**Expected behavior**
User should be able to use backspace, arrows, maybe some keyboard shortcuts like ^u to clear the whole input.

**Environment:**
 - OS and version: ArchLinux
 - **Megatools version**: 1.10.2

**Comment by megous** [comment]
Thanks for the report. It's the same input mechanism like with other common apps without a line editor, like pacman, etc. That is, only backspace is expected to work.

Using readline would imrpove this, but it's a big dependency, which needs runtime support files (terminals database), and that would make static binaries harder to make.

I think basic interface is enough to input a few numbers, so I'm against this.

**Comment by Porkepix** [comment]
> That is, only backspace is expected to work.
> 
Well, backspace currently doesn't work, it only prints `^?` in the terminal.

**Comment by megous** [comment]
Might be a problem with your terminal emulator? It works fine in urxvt, for example.

**Comment by Porkepix** [comment]
> Might be a problem with your terminal emulator? It works fine in urxvt, for example.

Hem. You're right, and that's sad: good news is that out of 5 terminals I just tested on, only one got this bad behavior. Bad news is that it's probably the most used of the 5: it's gnome-terminal.

**Comment by megous** [comment]
Hmm, haven't used that for quite a while. It might have some config option that fixes this though.

**Comment by megous** [comment]
https://en.wikipedia.org/wiki/Gnome-terminal

Check out the compatibility section.

**Comment by Porkepix** [comment]
> Hmm, haven't used that one for quite a while. It might have some config option that fixes this, though.

It offers 5 options for `Backspace key generates`.
Default is `ASCII DEL` which leads to `^?`;
`Automatic` leads to the same result;
`Control-H`, well… leads to `^H`
`Escape sequence` leads to `^[[3~`
Finally, `TTY Erase` again prints `^?`

And so… none of the five options works :(

**Comment by megous** [comment]
I don't think this can be fixed in megatools. Megatools just uses standard fgets(...stdin) to read the input. Something is wrong with gnome terminal or vte or pseudo tty connfiguration here.
