### ISSUE TITLE
[FR] Option to succeed on `File already exists`

### ISSUE THREAD

**Issue by vitorgalvao** [megous/megatools#434]
*I’ve deleted the template since this is a feature request and not a bug report. I found no template for feature requests.*

I have a script that downloads several links in a row and only goes forward when the current one is successful. It runs while it can, typically bumping into `Data download failed: Server returned 509 (over quota)` (exit status `1`). However, since downloads are interrupted before they finish and files may download out of order, it’s possible to bump into `ERROR: File already exists at` (exit status also `1`).

I do understand why you consider this an error — in case a different file with the same name was present. But I don’t, as (in my case) it means “this one was already done”. And in my case this means the script will stop when it should have continued.

Could we get an option to ignore the `ERROR: File already exists at` error (returning `0` when it happens)?

**Comment by megous** [comment]
How about returning 2 instead? It would not need an option and you'd be able to check for this conodition via $?.

**Comment by vitorgalvao** [comment]
> How about returning 2 instead? It would not need an option and you'd be able to check for this condition via $?.

Sure, that works. Initially I was going to suggest something similar; that every error used a different exit status (e.g. `over quota` could return `509`, it seems fitting). Returning `2` on `File already exists at`, if it’s the only error with that exit code, will work fine for my case.

Thank you for the fast reply.

**Comment by megous** [comment]
Which command are you using? get?

**Comment by vitorgalvao** [comment]
> Which command are you using?

`megadl`

**Comment by tukusejssirs** [comment]
I think all errors (in all `megatools` commands) should have a unique return code.

**Comment by vitorgalvao** [comment]
@tukusejssirs There’s no point to commenting on this repo anymore, since it’s no longer monitored (check the README).
