### ISSUE TITLE
megareg --verify

### ISSUE THREAD

**Issue by tomdoe420** [megous/megatools#436]
I'm trying to run megareg --verify VERIFICATIONLINK

I get 
ERROR: You must specify signup key and a link from the verification email

man megatools has me a bit confused with megareg --verify STATE LINK

so I tried megareg --verify EMAIL PASSWORD VERIFICATIONLINK
I get 
ERROR: You must specify signup key and a link from the verification email

megareg --verify PASSWORD VERIFICATIONLINK

ERROR: Failed to decode registration state parameter, make sure you copied it correctly

To register I used megatools:
megareg --register --email EMAIL --name FIRSTNAME LASTNAME --password PASSWORD

For VERIFICATIONLINK I am copying the link that I get in my email (the one that asks me to input my password in html firefox for verification purposes)

**Comment by megous** [comment]
Have you read this?

https://megatools.megous.com/man/megatools-reg.html

See the example section.

**Comment by tomdoe420** [comment]
Yes I have read that. It's a bit outdated megatools reg --verify gives me

bash: megatools: command not found

In the example I'm guessing vbFFFv7AFM25etzkFXLs9A==:Z7FFbgAAAAAAAAAArL33eA==:inEONh3tmwY

should be PASSWORD followed by verificationlink

so megareg --verify PASSWORD VERIFICATIONLINK

I  also tried typing megareg --verify PASSWORD \
> VERIFICATIONLINK

ERROR: Failed to decode registration state parameter, make sure you copied it correctly

**Comment by megous** [comment]
It's not a password. You should literally run what `megatools reg` command tells you to.

**Comment by tomdoe420** [comment]
If I type in 
megatools reg --verify PASSWORD \
>VERIFICATIONLINK

bash: megatools: command not found

If I type in  megatools reg --verify vbFFFv7AFM25etzkFXLs9A==:Z7FFbgAAAAAAAAAArL33eA==:inEONh3tmwY \
>VERIFICATIONLINK
bash: megatools: command not found

**Comment by megous** [comment]
You have to replace the command name based on what version of megatools you use. The point is to do what the `reg` command tells you to, exactly, when you run the --register step.

**Comment by tomdoe420** [comment]
I have https://megatools.megous.com/builds/megatools-1.10.2.tar.gz. This is what I get when I run man megatools. How would I write it? I think in this version I have to use megareg --verify STATE LINK. But what do I put for state?

MEGATOOLS(7)            Megatools Manual            MEGATOOLS(7)

NAME
       megatools - Mega.nz command line tools

SYNOPSIS
       megadf [--free|--total|--used] [--mb|--gb|-h]
       megals [-e] [-h] [--header] [-l] [-R] [-n] [<remotepaths>..
.]
       megaput [--no-progress] [--path <remotepath>] <paths>...
       megamkdir <remotepaths>...
       megamkdir /Contacts/<contactemail>
       megaget [--no-progress] [--path <path>] <remotepaths>...
       megaget --path - <remotefile>
       megarm <remotepaths>...
       megarm /Contacts/<contactemail>
       megadl [--no-progress] [--path <path>] <links>...
       megadl --path - <filelink>
       megareg [--scripted] --register --email <email> --name <rea
lname> --password <password>
       megareg [--scripted] --verify <state> <link>

DESCRIPTION
       Megatools is a collection of programs for accessing Mega
       service from a command line of your desktop or server.

       Megatools allow you to copy individual files as well as
       entire directory trees to and from the cloud. You can
       also perform streaming downloads for example to preview
       videos and audio files, without needing to download the
       entire file.

       Megatools are robust and optimized for fast operation -
       as fast as Mega servers allow. Memory requirements and
       CPU utilization are kept at minimum.

       You can register account using a megareg(1) tool, with
       the benefit of having true control of your encryption
       keys.

       Mega website can be found at http://mega.nz.

       Megatools can be downloaded at
       http://megatools.megous.com
TOOLS OVERVIEW
       megareg(1)
           Register and verify a new mega account

       megadf(1)
           Show your cloud storage space usage/quota

       megals(1)
           List all remote files

       megamkdir(1)
           Create remote directory
 megarm(1)
           Remove remote file or directory

       megaput(1)
           Upload individual files

       megaget(1)
           Download individual files

       megadl(1)
           Download file from a "public" Mega link (doesn’t
           require login)

       megacopy(1)
           Upload or download a directory tree

CONFIGURATION FILES
       See megarc(5) for information about mega configuration
       file.

       Each of the individual tools have help that can be
       accessed using --help parameter.

SESSION CACHE
       If you modify cloud filesystem from the Mega.nz website
       or from another computer, you’ll need to refresh your
       session cache. This can be done by using the --reload
       option to any tool, or by waiting for a cache timeout
       (default timeout is set to 10 minutes).

REMOTE FILESYSTEM
       Mega.nz filesystem is represented as a tree of nodes of
       various types. Nodes are identified by a 8 character node
       handles (eg. 7Fdi3ZjC). Structure of the filesystem is
       not encrypted.

       Megatools maps node tree structure to a traditional
       filesystem paths (eg. /Root/SomeFile.DAT).

       NOTE: By the nature of Mega.nz storage, several files in
       the directory can have the same name. To allow access to
       such files, the names of conflicting files are extended
       by appending dot and their node handle like this:

           /Root/conflictingfile
           /Root/conflictingfile.7Fdi3ZjC
           /Root/conflictingfile.mEU23aSD
      You need to be aware of several special folders:

       /Root
           Writable directory representing the root of the
           filesystem.

       /Trash
           Trash directory where Mega.nz web client moves
           deleted files. This directory is not used by
           megatools when removing files.

       /Inbox
           Not sure.

       /Contacts
           Directory containing subdirectories representing your
           contacts list. If you want to add contacts to the
           list, simply create subdirectory named after the
           contact you want to add.

       /Contacts/<email>
           Directories representing individual contacts in your
           contacts list. These directories contain folders that
           others shared with you. All shared files are
           read-only, at the moment.

SEE ALSO
       megatools(7), megarc(5), megadf(1), megadl(1),
       megaget(1), megals(1), megamkdir(1), megaput(1),
       megareg(1), megarm(1), megacopy(1).

MEGATOOLS
       Part of the megatools(7) suite.

BUGS
       Report bugs at https://github.com/megous/megatools or
       megous@megous.com.

AUTHOR
       Megatools was written by Ondrej Jirman
       <megous@megous.com>, 2013-2016.

       Official website is http://megatools.megous.com.

**Comment by megous** [comment]
Exactly what the:

    megareg --register --email EMAIL --name FIRSTNAME LASTNAME --password PASSWORD

told you.

**Comment by tomdoe420** [comment]
I try megareg --register -email EMAIL --name FIRSTNAME LASTNAME --password PASSWORD 

To complete registration, you must run:

  megareg --verify fYGDBb+FNNQEG42eNHYqnQ==:nnzSYAAAAAAAAAAAi+1SSw==:hV0B5xPj3VE @LINK@

so I run megareg --verify fYGDBb+FNNQEG42eNHYqnQ==:nnzSYAAAAAAAAAAAi+1SSw==:hV0B5xPj3VE VERIFICATIONLINK


ERROR: Verification failed: Invalid challenge response

**Comment by megous** [comment]
Did you put the link in quotes? Also you've just published your password key to the public, so perhaps start over with a different password?

**Comment by megous** [comment]
# is a comment character in most (all) shells, so I guess you need to quote the link. BTW, I just tried to register a new account via megatools, and it works.

**Comment by tomdoe420** [comment]
I notice I made a typo in FIRST NAME so I resubmitted and got  megareg --verify fYGDBb+FNNQEG42eNHYqnQ==:n99ZvAAAAAAAAAAAcilP4A==:pp_M65cQHyk

I tried putting VERIFICATIONLINK in "" but still getting 
ERROR: Verification failed: Invalid challenge response
I logged in firefox, verified it and drastically changed my password. No one will be able to crack my account now. I don't know why megatools is yielding errors I guess I'll just use firefox html for verification. I did notice my last name was removed after I verified my account when I logged in.

**Comment by megous** [comment]
That error means that "session self challenge" verification failed. Megatools is just checking that the random challenge string that was generated during `--register` can be verified with your master key that was generated during registration.

It serves to check that you've finished your registration with the same password key used in `--register`.

I don't know how mega's servers are implemented, but if you've run `--register` step multiple times, that could be an issue here.

Anyway, supported use case is to run --register and --verify exactly once for one account (e-mail address).
