### ISSUE TITLE
how to force ipv6 connection when downloading file?

### ISSUE THREAD

**Issue by korangu** [megous/megatools#438]
how to tell megatools to download via ipv6 connection? such option there?

**Comment by megous** [comment]
No, but you can modify http.c and add some curl option to do it. There should be some CURL option to prefer name resolution of IPv6 addresses if they are available.

Perhaps this: https://curl.haxx.se/libcurl/c/CURLOPT_IPRESOLVE.html

**Comment by korangu** [comment]
@megous can you please implement this as feature(additional params for `dl ` operation) ? and also ability to input ip interface like, if we have multiple ips in server use specific ip for downloading file? 
mega.nz now a days seems to have very tight download limits. cant download more than 2-3 files in a day per ip. :(

**Comment by megous** [comment]
Implemented in the master branch.

**Comment by korangu** [comment]
thank you very much. :heart:
