### ISSUE TITLE
Global config?

### ISSUE THREAD

**Issue by BarbzYHOOL** [megous/megatools#440]
Is there a way to have a global config file? like in /etc/megatools or smthg?

**Comment by megous** [comment]
No, would it be useful?

**Comment by BarbzYHOOL** [comment]
well, in my case I use the same user account on both my general user and on my root user (to upload something for example), so i had to create the same config file on both users

**Comment by megous** [comment]
You can create a symlink from /home/user/.megarc to /root/.megarc. Root will be able to read it. That should solve your problem.

**Comment by BarbzYHOOL** [comment]
ye
