### ISSUE TITLE
Give list of urls to download from a text file

### ISSUE THREAD

**Issue by ahmedtds** [megous/megatools#441]
Hi

Is it possible to make megatools dl download from urls from a file?

I mean like wget's -i argument?
We can do this with wget:
`wget -i list.txt`
and it will download all urls from that list

So I want to do same with megatools like this:
`megatools dl -i list.txt`

Thanks

**Comment by megous** [comment]
You can probably use `xargs -a file megatools dl`

**Comment by ahmedtds** [comment]
can't you add such a function to megatools? I use megatools on windows a lot as well. Need this feature a lot

**Comment by megous** [comment]
You can use xargs on windows too:

https://github.com/megous/megatools/issues/441#issuecomment-475494779

**Comment by ahmedtds** [comment]
Why not add such a simple and useful feature so we can use it without hassle?

**Comment by megous** [comment]
Because it can already be done other way. You just need a better shell/utils than `cmd` to control megatools. `cmd` is quite limited. I think msys2 has bash and xargs and gives a much more featured way to control processes from command line on windows.

https://www.msys2.org/

**Comment by ahmedtds** [comment]
Why wget has a built-in feature for this then? Or other tools like aria2 etc.. They all have a feature like this which makes things so much easier.

What hurt it has to add it to program?

**Comment by megous** [comment]
There's not much hurt. If someone will write a proper implementation that will handle the URL parsing, character encoding issues, and will be multi-platform, I'll merge it.

I just don't want to deal with it myself.
