### ISSUE TITLE
improved stream from mega

### ISSUE THREAD

**Issue by caspertone2003** [megous/megatools#444]
When streaming to vlc such as

megatools dl --path - publiclink | vlc.exe -

FF or skipping does not work

Nevertheless, using streaming with Megasync, it works properly, allowing rewind, FF, skips, etc.

So, the server is not the issue...

Could megatools be upgraded to perform in streaming as megasync does?

TIA

(using last available experimental compilation @ W10)

**Comment by megous** [comment]
There's no way to do it. When you use | (pipe) you only get a sequential stream of data. There's no seeking or anything else possible. Megatools just sends file data to stdout.

VLC and other players would need to communicate in some way with the piping process, and I'm not aware of any commonly used standard mechanism to do that. I don't have any clue what megasync does here.

**Comment by caspertone2003** [comment]
@megous 
Now is when I am sad because I have not enogh knowledge to dive into megasync source code... I just searched for "stream" in their github and I was unable to understand anything at all.
But I assure you that it works... one can skipp and FF, so there is a mechanism of communicating vlc to megasync... perhaps stdout is not the way but an established streaming protocol.
Again dived in VLC https://wiki.videolan.org/Hacker_Guide/Input/ and there are many alternatives...
And also checked FFMPEG https://trac.ffmpeg.org/wiki/StreamingGuide 
But I cannot go further.

**Comment by megous** [comment]
There are multiple definitions of streaming. One is where the vlc itself is reading some data from a remote resource, and drives the process, so it can request data at different timestamps, seek, etc.

What megatools calls streaming is just sending the remote file's contents to stdout without downloading it first and storing it locally in full. In this way, programs that are receiving the stream from megatools have almost no control. They can accept the data or not read from the stream, when they don't need to (effectively stopping or slowing the stream of data). But that's all.

There's not much that can be done. The pages you linked are yat about something else. For example ffmpeg one is for creating a video stream out of your webcam and streaming the video to other people.

**Comment by caspertone2003** [comment]
@megous 
Thanks again, I understand.
Sorry to point to useless pages, I was spending some time to find a solution of streaming (with full control) from mega not using megasync, to no aval, and I found those that though perhaps could be relevant.
Just to point that megasync streaming does NOT download the file, somehow megasync streams megamagically it directly from mega and with full control. So the point is, if megasync can, it means it can be done... but I have not the knowledge to look for it in megasync code and to submit you a patch...
Thanks again, I close the issue.
CT

**Comment by megous** [comment]
MEGASync creates a http server and provides decrypted video data as a HTTP resource there. It then translates http requests into respective mega.nz API calls, and performs decryption as required.

Video players can then be pointed to the local url of the proxy server.

It's probably implementable with something like libsoup in megatools.

**Comment by caspertone2003** [comment]
@megous 

Any plan to queue this to the to be done feature list?

TIA

**Comment by megous** [comment]
No plan. I'm not interested in this feature.

**Comment by caspertone2003** [comment]
Thanks for the answer.
Bye

**Comment by Ammadkhalid** [comment]
@megous is the feature still available for streaming to stdout? i tried but there are two seems to available `megadl` and `megaget`.
