### ISSUE TITLE
Megaget: Remote file not found + Megadl: Invalid download link

### ISSUE THREAD

**Issue by mooooonbaby** [megous/megatools#447]
I tried to download this LineageOS-Image from Mega.nz with Megatools to my Raspberry Pi: https://forum.xda-developers.com/thinkpad-tablet/development/lineageos-14-1-lenovo-tab4-10-plus-t3899560

When i try

`megaget -u <email@adress> -p <password> 'https://mega.nz/#F!hMNgzQSR!9MWp0sgNqeAwsXhsBLs41Q?pQEQFaTY'`

i have the error

> ERROR: Download failed for 'https://mega.nz/#F!YEFQwITC!ldqf0SE44v3zK_EHBphr8w?ZY0hmY6': Remote file not found: https://mega.nz/#F!YEFQwITC!ldqf0SE44v3zK_EHBphr8w?ZY0hmY6

When i try 

`megadl 'https://mega.nz/#F!hMNgzQSR!9MWp0sgNqeAwsXhsBLs41Q?pQEQFaTY'`

i have the error

> WARNING: Skipping invalid Mega download link: https://mega.nz/#F!hMNgzQSR!9MWp0sgNqeAwsXhsBLs41Q?pQEQFaTY

I tried the link to the directory or to the image file directly, it the same with both links. Is there a problem with the link? i can download them via browser without problems. There is the same problems with the link to TWRP.

**Comment by megous** [comment]
You miss A at the end of the first link. It should be: https://mega.nz/#F!YEFQwITC!ldqf0SE44v3zK_EHBphr8w?ZY0hmY6A

Second link works fine. You just have to use latest megatools version.

**Comment by mooooonbaby** [comment]
i've installed megatool with apt and that version is an older one. i tried to install it from source but it failed with make -j4. This is the error

```
make  all-am
make[1]: Entering directory '/home/pi/megatools'
make[1]: *** No rule to make target 'docs/megatools.1', needed by 'all-am'.  Stop.
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/pi/megatools'
Makefile:430: recipe for target 'all' failed
make: *** [all] Error 2
```

I don't unterstand what it means.

**Comment by megous** [comment]
Follow the README, and let me know which step fails for you.

https://megous.com/git/megatools/tree/README#n143

**Comment by mooooonbaby** [comment]
i follow the readme and 'make -j4' failed with the posted error.

**Comment by megous** [comment]
What tarball version did you download?

**Comment by mooooonbaby** [comment]
I used this command from the readme

git clone git://megous.com/megatools

I did not download something manually.

**Comment by megous** [comment]
https://megous.com/git/megatools/tree/README#n211

**Comment by mooooonbaby** [comment]
I could build and install the last version using the tar file instead of cloning git. but the links still doesn't work. i don't know what you mean with "missing A at the end of the link". the link you posted is different from mine. you used the link to the lineage-image, i used the link to twrp-image.

i tried all links again but none worked. i have the same error then before.

installed version is 1.10.2.

**Comment by megous** [comment]
You have  wrong link. Last segment must have 8 characters. In the link you posted last segment has 7 characters and is thus invalid.

**Comment by megous** [comment]
Last version is 1.11.x from the experimental directory.

**Comment by hendranata** [comment]
simillar issue

megadl https://mega.co.nz/folder/WLwREI4D#CrauZanq_KYpUL9o7sGNfg/file/OOJSWAaB
WARNING: Skipping invalid Mega download link: https://mega.co.nz/folder/WLwREI4D#CrauZanq_KYpUL9o7sGNfg/file/OOJSWAaB


i have using version 1.11.0

**Comment by neel04** [comment]
@megous Same issue with me. Any possible fix?

**Comment by chapmanjacobd** [comment]
looks like it only works like this

```
megadl --choose-files https://mega.co.nz/folder/xxxxxxxxxxxxx
```
