### ISSUE TITLE
Creating old style accounts

### ISSUE THREAD

**Issue by stachu2k** [megous/megatools#451]
Can I still register old style accounts with permanent 50 GB storage via MegaTools? Because I have tried recently creating new account in MegaTools and ended up with new style account which is 15 GB after 30 days.

**Comment by megous** [comment]
I have no idea. I haven't created an account in quite a few years.

**Comment by stachu2k** [comment]
I'm asking because on your website there is a statement: 

> if you've registered an account via mega.nz web client since 11/6/2018. You'll not be able to use your account with megatools. You can still use megatools to download publicly exported files for free, or use accounts created before 11/6/2018. You may also be able to register accounts with megatools, and those will work with megatools. You just can't use the new style accounts that mega's website creates now.

So I was thinking, that megatools still creates old style accounts with 50 GB permanent.

**Comment by megous** [comment]
Old style there means "using old style authentication method". Not old style limits.

**Comment by stachu2k** [comment]
Ok. Thank you for explanation.
