### ISSUE TITLE
Issue downloading possibly new link structure

### ISSUE THREAD

**Issue by Fragception** [megous/megatools#453]
When creating links for folder they now are in the format https://mega.nz/folder/* for me at least and megadl simply calls them invalid

**Comment by hiiragizawakun** [comment]
megatools 1.10.3 - 2020-04-15
=============================

This is a bugfix release.

Fixes:
- Add support for new format of mega.nz links (by Alberto Garcia)

As per https://megatools.megous.com/builds/NEWS

**Comment by megous** [comment]
Fixed.
