### ISSUE TITLE
WARNING: Skipping invalid Mega download link

### ISSUE THREAD

**Issue by hendranata** [megous/megatools#454]
helo 
i cant use megadl..
seems the link is invalid

megadl --version
megatools 1.11.0 - command line tools for Mega.nz

Written by Ondrej Jirman <megous@megous.com>, 2013-2018
Go to http://megatools.megous.com for more information

megadl 'https://mega.nz/folder/WLwREI4D#CrauZanq_KYpUL9o7sGNfg/file/OOJSWAaB'
WARNING: Skipping invalid Mega download link: https://mega.nz/folder/WLwREI4D#CrauZanq_KYpUL9o7sGNfg/file/OOJSWAaB

any idea? i have tried both: link with key and without key.. same result

**Comment by hendranata** [comment]
how do we get latest version 1.11.x ??

i am using this method:

  git clone https://megous.com/git/megatools
  cd megatools
  meson b
  ninja -C b
  sudo ninja -C b install

it used version 1.11.0

**Comment by megous** [comment]
Fixed in master:

https://megous.com/git/megatools/commit/?id=e4e849585dc5888031e1886636f295e5fce7fe50

**Comment by hendranata** [comment]
do i need to update the version again?
i still confuse which version is the latest one?
i am using git clone and it show version 1.11.0

**Comment by MarioVilas** [comment]
This would be a lot more flexible if the list of regular expressions was defined in a configuration file. :)
