### ISSUE TITLE
Incompatibility with ancient glib versions

### ISSUE THREAD

**Issue by mckaygerhard** [megous/megatools#458]
using a enoght recent version of libglib2.0-dev (2.42.1) it gives me linking errors:

```
[   78s]   CC       lib/tools.o
[   79s]   AR       libmega.a
[   79s]   CCLD     megadf
[   79s] libmega.a(mega.o): In function `mega_download_data_free':
[   79s] /usr/src/packages/BUILD/lib/mega.c:4501: undefined reference to `g_clear_pointer'
[   79s] /usr/src/packages/BUILD/lib/mega.c:4502: undefined reference to `g_clear_pointer'
[   79s] /usr/src/packages/BUILD/lib/mega.c:4503: undefined reference to `g_clear_pointer'
```

seems pretty related to #66 but i'm using stable branch and glib 2.41

**Comment by adga137** [comment]
It happens to me exactly the same

**Comment by adga137** [comment]
please correct this error

**Comment by mckaygerhard** [comment]
maybe this:

```
--- megatools-1.10.3.orig/lib/mega.c
+++ megatools-1.10.3/lib/mega.c
@@ -4498,10 +4498,22 @@ err_noremove:
 
 void mega_download_data_free(struct mega_download_data_params *params)
 {
+  if (GLIB_CHECK_VERSION (2, 34, 0))
+{
 	g_clear_pointer(&params->download_url, g_free);
 	g_clear_pointer(&params->node_handle, g_free);
 	g_clear_pointer(&params->node_name, g_free);
 }
+else
+{
+    &params->download_url = NULL;
+    &params->node_handle = NULL;
+    &params->node_name = NULL;
+    free(&params->download_url);
+    free(&params->node_handle);
+    free(&params->node_name);
+}
+}
 
 // }}}
 // {{{ mega_session_get
```

**Comment by megous** [comment]
That patch is wrong, it uses wrong pointers and doesn't clear the struct members. megatools doesn't support ancient glib versions.

Anyway, better way to acchieve the compatibility is to avoid changing megatools code, and just copy the g_clear_pointer function from glib to megatools. (and gate it with version checking macro).

**Comment by mckaygerhard** [comment]
**oh i forgotten to paste here the fixed one.. sorry.. so then can you fix that?** in fact this is not the only part that need a patch.. there's antoher one.. 

> Anyway, better way to achieve compatibility is to avoid changing megatools code, and just copy the g_clear_pointer function from glib to megatools. (and gate it with version checking macro).

**Comment by megous** [comment]
I will not fix it of course, because I don't have any system with such an old glib version. If you come up with a reasonable patch as suggested, I'll merge it.

**Comment by megous** [comment]
If you do, send the patch to megatools@megous.com as suggested on the megatools website.

I have github notifications blocked, and only come here very sporadically.

**Comment by vegnuli** [comment]
> g_clear_pointer function

ugg i need to search the source code.. i was busy.. i will paste here that!
