### ISSUE TITLE
megaput/megaget should handle directories

### ISSUE THREAD

**Issue by redneb** [megous/megatools#61]
I think the choice of having `megaput`/`megaget` handle only individual files and `megasync` of handle directories is very unfortunate and unnatural. I propose the following:
1. If one of the arguments given to `megaput` is a directory, it should upload its contents recursively.
2. Similarly, `megaget` should be able to download directories recusively.
3. `megasync` should only be used for directory synchronization (as proposed in #20), not for just uploading/downloading directories recursively. This is what the word synchronization really means.

Functionalities 1 & 2 could be provided by a command line, e.g. `-r`, similarly to standard unix tools like `cp`, but I would personally prefer if the recursive mode was the default, just like how `megarm` can be used to remove directories without additional flags.

**Comment by megous** [comment]
Megasync has been named megacopy for quite a few years already. So it's more sensible now.
