### ISSUE TITLE
Megals folder link export

### ISSUE THREAD

**Issue by yairh** [megous/megatools#67]
Hi Megous,
I have an issue using megals.
When I choose to export the links, it should also export a link to folders.
This is an option I have with the web ui. Please fix this :)
Thanks in advance!

**Comment by megous** [comment]
Implemented in 2.0.

**Comment by thefoofighter** [comment]
Hi I was just wondering is this already fixed on the master? If i built for linux would it include this folder link retrieval? Thanks

**Comment by megous** [comment]
Hi. Nope, master will not get this.

**Comment by thefoofighter** [comment]
Ah a pity, I guess i have to wait until 2.0 to use this feature?
