### ISSUE TITLE
Resume support for megadl

### ISSUE THREAD

**Issue by neuromancer** [megous/megatools#7]
Is it possible to resume a download with megadl?. 
I don't really know if such thing is supported by the mega server.

**Comment by Fitito** [comment]
Thanks for the program!
It would be nice to stop and resume downloads. So much for the next version?
Another thing, I could use (free, not commercial) for any project?
Thank you for your work

**Comment by megous** [comment]
Yes, you can. You only need to abide by the terms of GPLv2 license.

**Comment by pasnox** [comment]
+1 for resume support, very annoying on systems like rpi where the usb disconnect regulary.

**Comment by didix16** [comment]
So @megous , you have already coded the download resume function? I'm just downloading a file and then I lost my Internet connection. After it comes back, I tried to resume by getting the last command line from history and then the megadl outputs an error saying:
ERROR: Download failed for <file_mega_path>:  Can't open local file <file_name> for writing. File already exists.

So the file exists but is not fully completed. I have had to remove the file and then execute again the command. So is there an option to resume the download or is not implemented yet?

Thanks in advance.

**Comment by megous** [comment]
It's not implemented yet.

**Comment by didix16** [comment]
Ok. I hope it come soon. Thanks.

**Comment by megous** [comment]
Resume is implemented.
