### ISSUE TITLE
libressl/nss support

### ISSUE THREAD

**Issue by vaygr** [megous/megatools#70]
It would be nice to have non-gnutls systems able to use megatools as well.

**Comment by vaygr** [comment]
I believe, because megatools relies on curl since 1.9.97, this issue no longer relevant.
Tested it just fine (curl itself support 5 different TLS implementations: openssl, libressl, nss, polarssl, gnutls.

Correct me if I'm wrong.

**Comment by megous** [comment]
For TLS yes, for other crypto openssl is still needed.
