### ISSUE TITLE
"Password =" field is forward-slash sensitive

### ISSUE THREAD

**Issue by i336** [megous/megatools#71]
Each forwardslash (\\) in a Mega account password currently must be specified twice (thus, '\\\\'), both in the configuration file and at the commandline.

Confused me to bits for quite a while xD Utterly out of ideas, I was like "......it caaan't be tha--ooh. Hm, well, I &#x2a;*have*&#x2a; been meaning to create a GitHub account for a while now..."

Apart from that, truly awesome app :) thanks for making it! :D

**Comment by megous** [comment]
Documented.

**Comment by nyuszika7h** [comment]
Sorry for bumping an old thread, but that's a backslash, not a forward slash. ;)
