### ISSUE TITLE
"Network is unreachable" on ARM platforms?

### ISSUE THREAD

**Issue by papst01** [megous/megatools#72]
megatools 1.9.93 installed on a Debian Wheezy ARM platform via 
apt-get -t unstable install megatools
apt-get -t unstable install glib-networking
~/.megarc present with correct credentials.

When I run any mega command I get this:
ERROR: Can't login to mega.co.nz: API call 'us' failed: HTTP POST failed: Connection failed: Could not connect to eu.api.mega.co.nz: Network is unreachable

It looks like a platform problem because my virtual machine with debian wheezy has no problem with this.
The platforms (uname -a):
Working: Linux vmdebian2 3.2.0-4-686-pae #1 SMP Debian 3.2.46-1 i686 GNU/Linux
Not Working: Linux debian1 3.2.0-4-kirkwood #1 Debian 3.2.51-1 armv5tel GNU/Linux

Both "machines" are in the same subnet and using the same gateway and DNS-Servers.

Maybe a ldd of the machines (as example I used megadf) helps.
First the not working pc:
root@debian1:~# ldd /usr/bin/megadf
        libmega.so.0 => /usr/lib/arm-linux-gnueabi/libmega.so.0 (0xb6ef0000)
        libgio-2.0.so.0 => /usr/lib/arm-linux-gnueabi/libgio-2.0.so.0 (0xb6d9b000)
        libgobject-2.0.so.0 => /usr/lib/arm-linux-gnueabi/libgobject-2.0.so.0 (0xb6d3e000)
        libglib-2.0.so.0 => /lib/arm-linux-gnueabi/libglib-2.0.so.0 (0xb6c36000)
        libcurl.so.4 => /usr/lib/arm-linux-gnueabi/libcurl.so.4 (0xb6bd3000)
        libssl.so.1.0.0 => /usr/lib/arm-linux-gnueabi/libssl.so.1.0.0 (0xb6b82000)
        libcrypto.so.1.0.0 => /usr/lib/arm-linux-gnueabi/libcrypto.so.1.0.0 (0xb6a16000)
        libpthread.so.0 => /lib/arm-linux-gnueabi/libpthread.so.0 (0xb69ed000)
        libc.so.6 => /lib/arm-linux-gnueabi/libc.so.6 (0xb68a7000)
        /lib/ld-linux.so.3 (0xb6f14000)
        libgmodule-2.0.so.0 => /usr/lib/arm-linux-gnueabi/libgmodule-2.0.so.0 (0xb6893000)
        libz.so.1 => /lib/arm-linux-gnueabi/libz.so.1 (0xb6875000)
        libselinux.so.1 => /lib/arm-linux-gnueabi/libselinux.so.1 (0xb6850000)
        libresolv.so.2 => /lib/arm-linux-gnueabi/libresolv.so.2 (0xb682b000)
        libffi.so.6 => /usr/lib/arm-linux-gnueabi/libffi.so.6 (0xb681b000)
        libpcre.so.3 => /lib/arm-linux-gnueabi/libpcre.so.3 (0xb67da000)
        libidn.so.11 => /usr/lib/arm-linux-gnueabi/libidn.so.11 (0xb67a1000)
        libssh2.so.1 => /usr/lib/arm-linux-gnueabi/libssh2.so.1 (0xb6776000)
        liblber-2.4.so.2 => /usr/lib/arm-linux-gnueabi/liblber-2.4.so.2 (0xb6762000)
        libldap_r-2.4.so.2 => /usr/lib/arm-linux-gnueabi/libldap_r-2.4.so.2 (0xb6718000)
        librt.so.1 => /lib/arm-linux-gnueabi/librt.so.1 (0xb6701000)
        libgssapi_krb5.so.2 => /usr/lib/arm-linux-gnueabi/libgssapi_krb5.so.2 (0xb66c9000)
        librtmp.so.0 => /usr/lib/arm-linux-gnueabi/librtmp.so.0 (0xb66aa000)
        libgcc_s.so.1 => /lib/arm-linux-gnueabi/libgcc_s.so.1 (0xb6680000)
        libdl.so.2 => /lib/arm-linux-gnueabi/libdl.so.2 (0xb666d000)
        libgcrypt.so.11 => /lib/arm-linux-gnueabi/libgcrypt.so.11 (0xb65ec000)
        libsasl2.so.2 => /usr/lib/arm-linux-gnueabi/libsasl2.so.2 (0xb65cc000)
        libgnutls.so.26 => /usr/lib/arm-linux-gnueabi/libgnutls.so.26 (0xb6510000)
        libkrb5.so.3 => /usr/lib/arm-linux-gnueabi/libkrb5.so.3 (0xb6461000)
        libk5crypto.so.3 => /usr/lib/arm-linux-gnueabi/libk5crypto.so.3 (0xb6431000)
        libcom_err.so.2 => /lib/arm-linux-gnueabi/libcom_err.so.2 (0xb6426000)
        libkrb5support.so.0 => /usr/lib/arm-linux-gnueabi/libkrb5support.so.0 (0xb6416000)
        libkeyutils.so.1 => /lib/arm-linux-gnueabi/libkeyutils.so.1 (0xb640b000)
        libgpg-error.so.0 => /lib/arm-linux-gnueabi/libgpg-error.so.0 (0xb6400000)
        libtasn1.so.3 => /usr/lib/arm-linux-gnueabi/libtasn1.so.3 (0xb63ea000)
        libp11-kit.so.0 => /usr/lib/arm-linux-gnueabi/libp11-kit.so.0 (0xb63a6000)

Working machine:
vmdebian2:~# ldd /usr/bin/megadf
        linux-gate.so.1 (0xb77b5000)
        libmega.so.0 => /usr/lib/i386-linux-gnu/libmega.so.0 (0xb7799000)
        libgio-2.0.so.0 => /usr/lib/i386-linux-gnu/libgio-2.0.so.0 (0xb75e3000)
        libgobject-2.0.so.0 => /usr/lib/i386-linux-gnu/libgobject-2.0.so.0 (0xb7584000)
        libglib-2.0.so.0 => /lib/i386-linux-gnu/libglib-2.0.so.0 (0xb745c000)
        libcurl.so.4 => /usr/lib/i386-linux-gnu/libcurl.so.4 (0xb73da000)
        libssl.so.1.0.0 => /usr/lib/i386-linux-gnu/i686/cmov/libssl.so.1.0.0 (0xb7381000)
        libcrypto.so.1.0.0 => /usr/lib/i386-linux-gnu/i686/cmov/libcrypto.so.1.0.0 (0xb71c3000)
        libpthread.so.0 => /lib/i386-linux-gnu/i686/cmov/libpthread.so.0 (0xb71a6000)
        libc.so.6 => /lib/i386-linux-gnu/i686/cmov/libc.so.6 (0xb6ffb000)
        libgmodule-2.0.so.0 => /usr/lib/i386-linux-gnu/libgmodule-2.0.so.0 (0xb6ff6000)
        libz.so.1 => /lib/i386-linux-gnu/libz.so.1 (0xb6fdd000)
        libselinux.so.1 => /lib/i386-linux-gnu/libselinux.so.1 (0xb6fbd000)
        libresolv.so.2 => /lib/i386-linux-gnu/i686/cmov/libresolv.so.2 (0xb6fa5000)
        libffi.so.6 => /usr/lib/i386-linux-gnu/libffi.so.6 (0xb6f9d000)
        libpcre.so.3 => /lib/i386-linux-gnu/libpcre.so.3 (0xb6f5f000)
        libidn.so.11 => /usr/lib/i386-linux-gnu/libidn.so.11 (0xb6f2c000)
        librtmp.so.1 => /usr/lib/i386-linux-gnu/librtmp.so.1 (0xb6f0c000)
        libssh2.so.1 => /usr/lib/i386-linux-gnu/libssh2.so.1 (0xb6ee1000)
        libgssapi_krb5.so.2 => /usr/lib/i386-linux-gnu/libgssapi_krb5.so.2 (0xb6e91000)
        libkrb5.so.3 => /usr/lib/i386-linux-gnu/libkrb5.so.3 (0xb6dbb000)
        libk5crypto.so.3 => /usr/lib/i386-linux-gnu/libk5crypto.so.3 (0xb6d88000)
        libcom_err.so.2 => /lib/i386-linux-gnu/libcom_err.so.2 (0xb6d83000)
        liblber-2.4.so.2 => /usr/lib/i386-linux-gnu/liblber-2.4.so.2 (0xb6d73000)
        libldap_r-2.4.so.2 => /usr/lib/i386-linux-gnu/libldap_r-2.4.so.2 (0xb6d21000)
        libdl.so.2 => /lib/i386-linux-gnu/i686/cmov/libdl.so.2 (0xb6d1c000)
        /lib/ld-linux.so.2 (0xb77b6000)
        libgnutls-deb0.so.28 => /usr/lib/i386-linux-gnu/libgnutls-deb0.so.28 (0xb6bda000)
        libhogweed.so.2 => /usr/lib/i386-linux-gnu/libhogweed.so.2 (0xb6ba9000)
        libnettle.so.4 => /usr/lib/i386-linux-gnu/libnettle.so.4 (0xb6b74000)
        libgmp.so.10 => /usr/lib/i386-linux-gnu/libgmp.so.10 (0xb6ae5000)
        libgcrypt.so.11 => /lib/i386-linux-gnu/libgcrypt.so.11 (0xb6a60000)
        libkrb5support.so.0 => /usr/lib/i386-linux-gnu/libkrb5support.so.0 (0xb6a53000)
        libkeyutils.so.1 => /lib/i386-linux-gnu/libkeyutils.so.1 (0xb6a4e000)
        libsasl2.so.2 => /usr/lib/i386-linux-gnu/libsasl2.so.2 (0xb6a31000)
        libgnutls.so.26 => /usr/lib/i386-linux-gnu/libgnutls.so.26 (0xb6968000)
        libp11-kit.so.0 => /usr/lib/i386-linux-gnu/libp11-kit.so.0 (0xb6925000)
        libtasn1.so.6 => /usr/lib/i386-linux-gnu/libtasn1.so.6 (0xb6911000)
        libgpg-error.so.0 => /lib/i386-linux-gnu/libgpg-error.so.0 (0xb690d000)
        libtasn1.so.3 => /usr/lib/i386-linux-gnu/libtasn1.so.3 (0xb68fa000)

**Comment by megous** [comment]
May it be that the DER error was because of mixing stable/unstable packages?

**Comment by megous** [comment]
I've pinned IPv4 in the code now.

**Comment by purexo** [comment]
No one fond a solution of this matter ?
i've the same on Debian 7 (stable, unstable activate just for installation)

**Comment by megous** [comment]
Solution for what problem are you looking for? This issue had a few subproblems.

**Comment by purexo** [comment]
root@starbound-fr:~# megadf
ERROR: Can't login to mega.co.nz: API call 'us' failed: HTTP POST failed: Connection failed: Error performing TLS handshake: ASN1 parser: Error in DER parsing.

**Comment by megous** [comment]
It may be that the certificate you're using is broken in some way. You can search the web for "ASN1 parser: Error in DER parsing" to find several suggestions. There was a bug in fedora that was fixed in fedora 20 (01/2014). libtasn1 may be incompatible between stable/unstable debian. I don't know.

**Comment by purexo** [comment]
So, I've not found the solution with this Error in DER parsing.
I've compiling from source : (with root account)
```bash
wget http://megatools.megous.com/builds/megatools-1.9.94.tar.gz
tar -zxvf megatools-1.9.94.tar.gz
cd megatools-1.9.94
./configure
make
make check
make install
make installcheck
make clean
ldconfig #thanks http://blog.hbautista.com/linux/megatools-en-debian-jessie/
ldconfig.real #thanks http://blog.hbautista.com/linux/megatools-en-debian-jessie/
```

And now it work. I think that "http://blog.hbautista.com/linux/megatools-en-debian-jessie/" error come from very specificly bad compilation from debian unstable package

**Comment by megous** [comment]
Good to know, thanks!

**Comment by papst01** [comment]
I could confirm the solution of porexo.. Now it works! Thanks man!
I have the same problems like https://github.com/megous/megatools/issues/13 but that's manageable.

**Comment by megous** [comment]
I found a way to avoid those dbus warnings in #13 too. It's in megatools 2.0. I can backport it to stable.
