### ISSUE TITLE
Remote directory not found /Root/

### ISSUE THREAD

**Issue by svaningelgem** [megous/megatools#77]
I have the following:
`megals  --username '<user>' --password '<pass>'`

Which returns the following:
```
/Contacts
/Inbox
/Root
/Root/test.txt
/Trash
```

So far so good...

`megasync --remote /Root/ --local downloads2/ --download  --username '<user>' --password '<pass>'`

Returns:
`ERROR: Remote directory not found /Root/`

I'm at a loss here... First ls says it's there, and there is a file in there. Then sync says it's not there?

How would I be using this? Or is it a bug?

**Comment by hberg539** [comment]
I'm trying to use megasync as backup for my Mega Account and i ran into the same issue as svaningelgem. megaous, is this know issue server-side or client-side? Thanks!

**Comment by megous** [comment]
This is client side. I'll look into it.

2015-01-01 19:46 GMT+01:00 hberg539 <notifications@github.com>:

> I'm trying to use megasync as backup for my Mega Account and i ran into
> the same issue as svaningelgem. megaous, is this know issue server-side or
> client-side? Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/megous/megatools/issues/77#issuecomment-68494432>.
>



-- 
Ondřej Jirman, http://megous.com, 799 794 947

**Comment by megous** [comment]
Fixed in stable branch.

**Comment by hberg539** [comment]
Can confirm, works like a charm. Thank you for this great tool.

**Comment by megous** [comment]
Great, thanks for the confirmation.

**Comment by svaningelgem** [comment]
I checked it too, but I can't get it to work?
```
$ megasync --remote /Root/ --local downloads/ --download
ERROR: Remote directory not found /Root/
```

I used svn to update the tree, not git, but by now (9h since commit) it should have been ok no?

**Comment by megous** [comment]
Did you use stable branch? Is the above mentioned commit present?

**Comment by svaningelgem** [comment]
I used the stable branch yes. But weird thing:
`$ megasync --remote /Root/ --local downloads/ --download`
==> error
`$ megasync --remote /Root --local downloads/ --download`
==> works

(notice the last slash behind Root)

**Comment by megous** [comment]
Found the bug. Should work now.

**Comment by svaningelgem** [comment]
Hmmm, seems not?
```
megasync --remote /Root/ --local downloads/ --download
ERROR: Remote directory not found /Root/
```

Ok, I did "make clean && make install" now, and it worked. Before I just did make install.

Strange.
