### ISSUE TITLE
Bad configuration file

### ISSUE THREAD

**Issue by leowzukw** [megous/megatools#78]
When there is a (little) synthax error in the configuration file, `megadf` ask for an e-mail.

In this way, on my use of the software, I wrote (with the right values) : 
```ini
[login]
Username = MY_E-MAIL
Password = MY_PASSWORD
```
`megadf` may display a message, to say that there is an error in rc file and that therefore it needs an e-mail.

**Version used : 1.9.93**

**Comment by megous** [comment]
Documented in the man page.
