### ISSUE TITLE
megastream?

### ISSUE THREAD

**Issue by xiconet** [megous/megatools#79]
Hello,
Thanks for your very nice program. However, I can't find any "megastream" tool in my win32 package. Should I build it from source?

**Comment by megous** [comment]
Megastream has been removed, and the functionality merged into megaget and megadl. See their respective man pages.

**Comment by xiconet** [comment]
I should have read the doc better. Thank you again for these very useful and reliable `megatools`.
Now I also have an enhancement request proposal:
 At least in my hands (WinXP-sp3), megaget/dl speeds are significantly lower than what can be achieved with e.g. firefox (which also happens to use way too much memory). Do you plan to implement some kind of "multi-connection" segmented download?

**Comment by megous** [comment]
Hi.

Yes. I do.

regards,
  o.j.

2015-01-03 13:33 GMT+01:00 xiconet <notifications@github.com>:

> I should have read the doc better. Thank you again for these very useful
> and reliable megatools.
> Now I also have an enhancement request proposal:
> At least in my hands (WinXP-sp3), megaget/dl speeds are significantly
> lower than what can be achieved with e.g. firefox (which also happens to
> use way too much memory). Do you plan to implement some kind of
> "multi-connection" segmented download?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/megous/megatools/issues/79#issuecomment-68593578>.
>



-- 
Ondřej Jirman, http://megous.com, 799 794 947

**Comment by xiconet** [comment]
Great news!
