### ISSUE TITLE
selectively download files from a public folder given its URL

### ISSUE THREAD

**Issue by nnectic** [megous/megatools#83]
Given a public folder URL, megadl will always download the entire contents of the folder, there doesn't seem to be a way of only downloading selected files, like you can with the Mega web interface.
Obviously, this would require the ability to list the contents of a public folder beforehand, see issue #82.

**Comment by megous** [comment]
Thaks, this will be possible in 2.0.

**Comment by svnpenn** [comment]
https://github.com/megous/megatools/issues/218

**Comment by svnpenn** [comment]
https://github.com/megous/megatools/issues/337

**Comment by megous** [comment]
Implemented via --choose-files.

**Comment by cup** [comment]
https://github.com/megous/megatools/blob/89b4ca84664b377bf68875b9815e633af537c01f/docs/megadl.txt#L46-L47
