### ISSUE TITLE
Cannot pass CPPFLAGS to files in libtools/

### ISSUE THREAD

**Issue by bertogg** [megous/megatools#85]
There's something wrong in the way the Makefile.am file is written, if I try to build megatools setting the CPPFLAGS variable (what's what we do in Debian for setting the hardening flags) those flags are not used for the files under libtools/

From what I can see in the Makefile those files don't get their own compilation rule, but they rather use the default one.

Since the files are used by all command-line tools, wouldn't it make sense to build libtools as an internal library (either static or dynamic) and link it to each one of the tools?

**Comment by bertogg** [comment]
In the case of Debian, since we're not shipping libmega separately and it's just an internal library, I think I quick solution is to add the whole libtools/ directory to libmega.so (e.g. replacing TOOLS_SOURCES = ... with libmega_la_SOURCES += ...). That has the side effect of making the command-line tools much smaller. Do you see any problem with that approach?

I also noticed that LDADD should include $(GLIB_LIBS), else the code will not link after re-running autoconf.

**Comment by megous** [comment]
Good idea about the shared library. Though even if I move libtools/*.c there, individual tools are still not built with passed CPPFLAGS. Weird.

**Comment by megous** [comment]
I tested that while flags may not be printed to the stdout during compilation, they are in fact used.

You can put for example:
```
#ifdef TESTCPPFLAGS
#error We are fine
#endif
```
into any file under libtools/

And add CPPFLAGS="-DTESTCPPFLAGS" to test it.

**Comment by bertogg** [comment]
Ah, you're right, somehow hardening-check still complains, but I guess that's because the code in those files doesn't need to be protected.

Thanks and sorry for the noise.

**Comment by megous** [comment]
No problem, thanks for the report. :)
