### ISSUE TITLE
Option to disable the colored output

### ISSUE THREAD

**Issue by juanfra684** [megous/megatools#86]
Can you add an option to disable the colored output?.

**Comment by megous** [comment]
In megatools 2.0 coloring will be automatic (based on the terminfo database and isatty(1)).

I'll probably forcefully disable it when --batch option will be used (option that disables all user interactivity, to enable easy scripting). Would that be enough?

**Comment by juanfra684** [comment]
I don't know. I use the "solarized" color scheme and I can't see the output. Look the screenshot:
![output](https://i.imgur.com/VVaCpWc.png)

If your changes fix my problem, it would be enough.

**Comment by megous** [comment]
Perhaps the problem is with your color scheme, because it doesn't transform colors correctly.

**Comment by juanfra684** [comment]
Just tell me when the new code is finished and I will give a try. Thanks! :)

**Comment by megous** [comment]
Colors are disabled automatically in dev branch. No plan to do anything about this in stable. But patches are welcome.
