### ISSUE TITLE
megatools cant fetch remotes folders

### ISSUE THREAD

**Issue by jemartins** [megous/megatools#87]
I use Linux Mageia 4 and just compiled megatools from megatools-1.9.94.tar.gz. 

I have valid username/password in ~/.megarc

I try megals in console command line, but after a long time I get that response:

ERROR: Can't read filesystem info from mega.co.nz: API call 'f' failed: Server keeps asking us for EAGAIN, giving up

The same issue logged in https://mega.co.nz and another android app. It only works in megasync-1.0.37-3.1 rpm pkg by mega downloads site.

I will appreciate any hint.

Att,

**Comment by megous** [comment]
Does it still happen? It might have been some transient overload on the mega.co.nz servers.

**Comment by jemartins** [comment]
Yes! I already tried several times on differents days. It always happens in megatools, browser and android app.

**Comment by megous** [comment]
Please contact the mega support then and tell them what you're experiencing. They may be able to help with their website app, which should solve the problem with other tools too, because it seems to be some API issue, that may be relevant only to you or your geographical area.

**Comment by jemartins** [comment]
OK. Thanks!

**Comment by wingedfox** [comment]
Any news on this issue? I getting the same problem since yesterday.

**Comment by jemartins** [comment]
I had problem to empty my "so big" trash folder. I can't did that in any way, include via mega site.
I had wrote to mega team and they made the clean on my trash (syncDebris) by hand and site admin privilegies.
After that I have not had more problems.

**Comment by leandropc** [comment]
Hi, I have the same problem using 1.9.97 version. I have plenty of space in my account. 
Any ideas?
