### ISSUE TITLE
Not run after install

### ISSUE THREAD

**Issue by ET-NiK** [megous/megatools#88]
```
megaput: error while loading shared libraries: libmega.so.0: cannot open shared object file: No such file or directory

**Comment by megous** [comment]
You've probably installed to --prefix=/usr/local (default for configure) and you don't have your system set to pickup shared libraries from /usr/local/lib.

Easy fix is to reinstall with --disable-shared option to configure.

**Comment by deltagreen88** [comment]
Hey there, sorry to write into an already closed thread:
i've got the same problem with `megals` (already existing account; set up on Ubuntu server 14.10 w/o gui); I've put a new mega.conf file into /etc with just the login&pass (don't know if anything i did here is right): 
```
# cat /root/.megarc
[Login]
Username=abc@xyz.com
Password=xyz
```
After trying to use the command `megals`, `megals /root`or whatever i get the same error mentioned by Et-NiK stated above..
`megals: error while loading shared libraries: libmega.so.0: cannot open shared object file: No such file or directory`
I don't really understand what you meant by 
> Easy fix is to reinstall with --disable-shared option to configure

If possible i'd need some help with this, i'm quite a noob..

**Comment by megous** [comment]
How did you install megatools?

**Comment by deltagreen88** [comment]
Hey thanks for your quick reply, well i did it this way: 
```
sudo apt-get install libtool libglib2.0-dev gobject-introspection libgmp3-dev nettle-dev asciidoc glib-networking
wget http://megatools.megous.com/builds/megatools-1.9.94.tar.gz
zcat megatools-1.9.94.tar.gz > megatools-1.9.94.tar
tar -xf megatools-1.9.94.tar
cd megatools-1.9.94/
./configure
make
sudo make install
```
Along the way i did install this too, thought it might be useful:
`sudo apt-get install exfat-utils exfat-fuse`
So basically i installed all this as shown [here on ask Ubuntu](http://askubuntu.com/questions/547481/is-there-a-form-to-upload-files-to-megamega-co-nz-from-ubuntu-serverssh)
I tried several install methods in the last few days, but it never would install correctly (adding ppa to sources.list manually, using add-apt-repository from somewhere - all didn't work)..

**Comment by megous** [comment]
You did everything right. All you need to change is to run:

./configure --disable-shared --enable-static

instead of plain:

./configure

**Comment by deltagreen88** [comment]
Thanks a lot for your help, well i'm getting closer now :) `megals` actually is recognized now, but still getting a little error when trying to use it while connecting i get:
```
~$ megals -u /Root
Enter password for (/Root): 
Good, signing in...
ERROR: Can't login to mega.co.nz: API call 'us' failed: Server returned error EARGS
```
or this
```
~$ megals -u <email address>
Enter password for (<email address>): 
Good, signing in...
ERROR: Can't login to mega.co.nz: API call 'us' failed: Server returned error ENOENT
```
I'm still not getting how the actual connection is done..? Does the login/password only have to be defined once (using `megals'), or are the options `-u` and/or `-p` always necessary to add to the syntax? Cause without the option -u at least i'm asked to add it
```
~$ megals
ERROR: You must specify your mega.co.nz username (email)
```
Maybe i could precise that during the ./configure --disable-shared --enable-static, FUSE was not indicated as present, but the installation ignored this and there was no problem.. i added `s3fs-fuse` from `git` afterwards, i mean after installation but i don't think that it was usefull..

**Comment by megous** [comment]
Please read the documentation. 

http://megatools.megous.com/man/megarc.html

**Comment by deltagreen88** [comment]
Tanks so much for all your valuable info, i'm so sorry to not have read the whole documentation beforehand - i can connect now without problems, i just have to play around a bit though with the `/.megarc` file since it's not quite working yet but i won't bother you more than that, again thanks alot! If there's anything i can do like paying credits somewhere feel free to tell me..

**Comment by megous** [comment]
I'm glad you made it work. :) If you have issues with .megarc file let me know. You just have to put it in your home directory  (~/.megarc), and use an example from the man page. It should work then.

**Comment by carlzoo** [comment]
hello sorry to open this again, 
i am compiling megatools-1.9.95 from debian 7 with
./configure --disable-shared --enable-static
make
sudo make install

however i still get that error
megadl: error while loading shared libraries: libmega.so.0: cannot open shared object file: No such file or directory
