### ISSUE TITLE
Can't download exported folder: multiple toplevel nodes

### ISSUE THREAD

**Issue by viric** [megous/megatools#90]
Running megadl 'URL' for a folder (which has no files, but multiple subfolders), I get this message:

ERROR: EXP folder fs has multiple toplevel nodes? Weird!

**Comment by megous** [comment]
Thanks for the report. It's a regression from the recent optimization work.

**Comment by megous** [comment]
Fixed in the master branch.

**Comment by quammy** [comment]
Just happened to me on Ubuntu 22.04 fully updated. Is there a resolution for this case?
