### ISSUE TITLE
rogue convert process. Why convert at all?

### ISSUE THREAD

**Issue by haayman** [megous/megatools#91]
Hi,

I just have a question.

My megasync process takes ages, becaus it spawns 'convert' processes that spawn 'gs' (ghostscript) processes to convert PDF-files to something, that are apparently too heavy for my machine. My question is: why should there be a convert at all? Why not just encrypt and send? I don't want converted files on my mega-drive.

**Comment by megous** [comment]
It's done to support file previews in mega.co.nz web client. Perhaps this option should be opt-in.

**Comment by haayman** [comment]
I'm searching the code, but so far I haven't found where it is done. Could you give me some pointers?

**Comment by megous** [comment]
https://github.com/megous/megatools/blob/master/libtools/oldmega.c#L2767

**Comment by haayman** [comment]
So I can set disable-previews = true in .megarc? I'm going to try that.

**Comment by haayman** [comment]
yup, that does seem to do the trick. Thanks.

**Comment by megous** [comment]
No, that will not work. You can --disable-previews on command line.

**Comment by haayman** [comment]
But it does work...
Op 25 jan. 2015 17:20 schreef "Ondřej Jirman" <notifications@github.com>:

**Comment by megous** [comment]
Sorry, it can not.

**Comment by haayman** [comment]
well, if I look in tools.c the option 'disable-previews' is in auth_options[] (strangely enough). Since I don't give username & password on the command-line either I figured I could put this option right next to my credentials. And it worked...

**Comment by haayman** [comment]
I'm sorry, you're right. I don't know why I didn't see any conversions going on this time though. Oh well. I moved the option to the command line now.

**Comment by megous** [comment]
Ok.
