### ISSUE TITLE
What IPs/Ports should it have access to?

### ISSUE THREAD

**Issue by ghostku** [megous/megatools#93]
Hi
A have a workstation with no Internet (totally blocked on router). I need to have megaput.exe working on this workstation. I have router with OpenWRT and iptables on it. So what expternal IPs/Ports should be allowed?
Thanks

**Comment by megous** [comment]
You'll need HTTP, HTTPS, and DNS.

**Comment by ghostku** [comment]
Ok. But what about IPs? I discovered that at least it should access
mega.co.nz and *.api.mega.co.nz. I allowed them but it is still not
working.

**Comment by megous** [comment]
There's no fixed set of IP's. Mega API is made so that it can return arbitrary host names client is supposed to connect to.
