### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by magamig** [megous/megatools#94]
It would be nice to have a progress bar for both upload and download, since the percentage is already shown I think it won't be a hard feature to implement.
This could be standard or an option.

**Comment by mrjohnr** [comment]
Hi,I'm also interested in this feature,where I can get binary for version 2.0,I found only some source code,thanks!

**Comment by megous** [comment]
Something like that is in the stable version now thanks to RealDolos.

**Comment by mrjohnr** [comment]
Hi,I use megaput.exe and there is just a percentage value shown in command window

**Comment by megous** [comment]
The change is in git. It will be in the next released version.

**Comment by mrjohnr** [comment]
k,thanks for the info
