### ISSUE TITLE
error adding symbols: DSO missing from command line

### ISSUE THREAD

**Issue by driesken** [megous/megatools#95]
I've installed all required packages and retrieved the latest code using git.

The autogen goes well, but 'make' is throwing me this error:

libtools/oldmega.c:1419:15: warning: variable ‘prev’ set but not used [-Wunused-but-set-variable]
   GSList *i, *prev, *next;
               ^
  CC       libtools/tools.o
  CCLD     megadf
/usr/bin/ld: libtools/oldmega.o: undefined reference to symbol 'g_input_stream_get_type'
//usr/lib/x86_64-linux-gnu/libgio-2.0.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[1]: *** [megadf] Error 1
make: *** [all] Error 2

Is this some kind of bug?

**Comment by megous** [comment]
What OS are you using?

**Comment by driesken** [comment]
Currently Ubuntu 14.04

**Comment by megous** [comment]
Weird, build works for me on that system. Though I'm only using the official tarball. Can you please confirm that official tarball build works on your system?

Can you also run make with:

  make V=1

and paste the output before the error happens.

**Comment by megous** [comment]
Might be you're missing some autotools related stuff on your system, before running autogen.sh. I've seen issues where ./autogen.sh succeeds but results in unusable Makefile/configure.

**Comment by driesken** [comment]
Here is the output you requested:
root@thinkpad:/home/ddegendt/Documents/megatools# make V=1
libtool: link: gcc -pthread -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I./libtools -I./mega -I. -g -O2 -Wall -Wextra -Wno-unused-parameter -Wno-unused-variable -Wno-unused-local-typedefs -Wno-sign-compare -Wno-pointer-sign -Wno-missing-field-initializers -o .libs/megadf tools/df.o libtools/sjson.gen.o libtools/http.o libtools/oldmega.o libtools/tools.o  ./.libs/libmega.so -pthread
/usr/bin/ld: libtools/oldmega.o: undefined reference to symbol 'g_input_stream_get_type'
//usr/lib/x86_64-linux-gnu/libgio-2.0.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[1]: *** [megadf] Error 1
make: *** [all] Error 2

Have never used autogen before so I don't have any experience with it.

The tarball works fine, thanks!

**Comment by megous** [comment]
Yeah, I have no clue. Most probably it is some missing dependency.

Ubuntu/Debian is kind of fragile in this, because it splits packages into many pieces, and if you don't know exactly what you're doing, you'll get bitten like this.

**Comment by crabkalash** [comment]
Hey, got the same error on 14.04. Installed from tarball went flawlessly.

**Comment by gnwp** [comment]
try:  ./configure --disable-shared --enable-static

this has worked for me.

**Comment by mathstuf** [comment]
(Found this searching for what ended up causing these issues.)

Anyways, the problem here is that the link line is missing `-lgio` because you use symbols from it. It used to be that the linker would see that some other library linked gio and the linker would be happy with that. Now, you use those symbols, so you must link `gio` specifically.
