### ISSUE TITLE
tool to upload thumbnail

### ISSUE THREAD

**Issue by Senover** [megous/megatools#96]
It would be nice if there was tool which allows you to update file with thumnail (i.e. when your image doesn't have thumbnail MEGA.co.nz generate it when you double click it).

**Comment by megous** [comment]
Nice idea.

**Comment by megous** [comment]
Though, for command line tools, thumbnail is a bit meaningless, unless there's also a tool to show thumbnails of selected images. :)

**Comment by Senover** [comment]
Viewing them could be implemented as separate directory, i.e. /Thumbnails/ This way you could link them to ~/.thumbnails when using megafs.

**Comment by megous** [comment]
Out of scope for me.
