### ISSUE TITLE
unable to launch megacli and megasimplesync

### ISSUE THREAD

**Issue by dancri77** [megous/megatools#99]
I have compiled mega skd on debian, no errors.
when I try to launcg megacli and megasimplesync I get the same error:

error while loading shared libraries: libmega.so.500: cannot open shared object file: No such file or directory

I checked and the file exists in /usr/local/lib/libmega.so.500.

**Comment by megous** [comment]
I think you want to report error somewhere else, because this has nothing to do with megatools.

Anyway, you can either build with --disable-shared or do 

  export LD_LIBRARY_PATH=/usr/local/lib

before launching megacli.
